### ISSUE TITLE
Changing title and menu Item color

### ISSUE THREAD

**Issue by cerobe** [mmistakes/minimal-mistakes#1000]
- [X] This is a question about using the theme.
- [ ] This is a feature request.
- [X] I have updated all gems with `bundle update`.
- [X] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:** 4.4.1
- **`github-pages` or `jekyll` gem version:** gem version
- **Operating system:** Windows 10

---

## Expected behavior

Change the color of the title and menu item

## Steps to reproduce the behavior

I copied the file _masthead.scss (found in _sass\minimal-mistakes\ in the gem installation) into my site under a newly created directory_sass\minimal-mistakes\_masthead.scss.
Then I change  .masthead__menu { } and added color: red;
I rerun locally using bundle exec jekyll build.
But the title didn't change color.

I also try to completely removed the content of my _masthead.sass but I still had the same website. Normally with all the sass removed the theme should be broken...

I guess I didn't override correctly or missed a step, but I cannot find what I missed. Any help would be welcome.

**Comment by mmistakes** [comment]
Overriding Sass partials found in a theme gem is somewhat limited due to how Jekyll processes them. They're not like `_includes` and `_layouts` where you can override a specific file by adding it to your root folder.

To override the Sass you need to copy the entire `_sass` folder, which defeats the purpose of using a theme gem since you'll have to stay in sync with any changes.

The alternative is to copy [`/assets/css/main.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/css/main.scss) to the same location locally. And then add any style overrides after `@import "minimal-mistakes";`.

In your case it would look something like this:

```scss
---
# Only the main Sass file needs front matter (the dashes are enough)
---

@charset "utf-8";

@import "minimal-mistakes";

// your styles here
 .masthead__menu { 
  color: red;
}
```

**Comment by cerobe** [comment]
Thanks for you quick answer. 

I tried to copy locally and change main.scss. (Literally copied your code above).
But the color didn't change. I tried to clear the cache but didn't change anything.

**Comment by mmistakes** [comment]
I was just pasting in the CSS you wrote as an example. You'll need write CSS that will actually do something like.

To override the masthead link color you'll need something like `.greedy-nav a { color: red; }`.

**Comment by cerobe** [comment]
All right, thanks. That' really shows that my skills in css are really low...
You right with your latest code it works perfectly.
I'll now focus on the other changes I need to do in the main.scss file.

Thanks again for your quick help.
You can close this ticket.
