### ISSUE TITLE
Broken link and question about table of contents 

### ISSUE THREAD

**Issue by Stelios3g** [mmistakes/minimal-mistakes#1013]
Hey mm its me again.While i was reading your documantation i tracked a broken link at: Quck-Start Guide->CONTENT->Helpers->Table of Contents -Link : (auto-generated table of contents) 
[ http://kramdown.rubyforge.org/converter/html.html#toc ]

I've also got a question about table of contents.I can't really find a way to use {% include toc %} without it being autogenerated, more specifically I would like to do it inside of an HTML file if possible.

**Comment by mmistakes** [comment]
Thanks, the link has been corrected. https://kramdown.gettalong.org/converter/html.html#toc

The TOC helper only works in a Markdown file because that's how it is created. Kramdown (the Markdown parser used by Jekyll) creates it automatically using the headings in your `.md` file.

There are handful of [JavaScript solutions](https://www.google.com/search?q=jquery+table+of+contents&oq=jquery+table+of+contents) out there you could use if needed, but not something I'm interested in adding to the theme.
