### ISSUE TITLE
changing color on the underline on menu item when hover

### ISSUE THREAD

**Issue by cerobe** [mmistakes/minimal-mistakes#1026]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:** 4.4.1
- **`github-pages` or `jekyll` gem version:** gem version
- **Operating system:** Windows 10

---

## Expected behavior

On the menu item, when you hover them, I would like to change the color of the underlying line that appears.

## Steps to reproduce the behavior

Hover one menu item, then a underline will appear. I would like to change the default color.

**Comment by mmistakes** [comment]
You'll need to modify/override the theme's CSS to do this. The CSS you'll need to change is in [`_sass/minimal-mistakes/_navigations.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_navigation.scss#L240)

Since you're working with the theme gem version you'll need to follow the relevant instructions on this [page in the docs](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/).

Essentially...

1. Copy the contents of `/assets/css/main.scss` from the theme gem to <your_project>.
2. Add your CSS overrides to `<your_project>/assets/css/main.scss`.

The CSS will end up being something like this, where you change the `background-color` to whatever color you want the underline.

```css
.greedy-nav a:before {
  background: mix(#fff, $primary-color, 50%);
}
```

**Comment by cerobe** [comment]
Hi thanks for your answer,

I tried this in the <your_project>/assets/css/main.scss:

$red: rgb(233,87,110); 

.greedy-nav a:before {
   background: mix(#fff, $red, 50%);
   background-color: $red;
}

It's bit more than what you suggest but I wanted to try more according too
but it's not changing anything on the color of the under line.

if i try  with :
.greedy-nav a:hover:before {
   background: mix(#fff, $red, 50%);
   background-color: $red;
}

It's' working but I still have the grey color a split second when the mouse leave the menu item and just at the beginning. I guess there is still something else that I missed, if you have any idea?

**Comment by mmistakes** [comment]
Try this:

```css
.greedy-nav .visible-links a:before {
  background-color: red;
}
```

If you use your browser's web developer inspector tool you can right click any element and it'll give you a hint as to what you need to override. 

![inspector](https://cloud.githubusercontent.com/assets/1376749/26405915/afbb992c-4064-11e7-94b8-04f13f6cf468.jpg)

Also you don't need both `background` and `background-color`. Just use `background-color` since it's more specific. [`background` is a shorthand](https://css-tricks.com/almanac/properties/b/background/) for a bunch of other properties that might override things you don't want.

Closing as this is CSS related and better suited for a forum like Stackoverflow.
