### ISSUE TITLE
no-cache for specific page

### ISSUE THREAD

**Issue by Sciss** [mmistakes/minimal-mistakes#110]
hello,

I have a `_layout/home.html` that contains an index and iterates over the past posts. Now when I upload that to my website, the browser caches that page, so without an explicit reload the new posts don't show up.

I'm not an HTML expert, but reading for example [this page](http://www.i18nguy.com/markup/metatags.html), I should probably include the following to things in 'head':

    <META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
    <META HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE">

Do you have any experience with this? Would that be the preferred way to prevent caching a dynamic page? Thanks!

**Comment by Sciss** [comment]
Any news on this? I have added this to my pages, but it has no effect:

```html
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">
<meta http-equiv="PRAGMA" content="NO-CACHE">
```

That is, if I have a page that aggregates the latest posts for example, Firefox caches that pages, and when I add a new post it doesn't show up unless I explicitly reload the page :-( Any way to force the browser to never cache a page?

**Comment by mmistakes** [comment]
Nope no experience with it, I don't have any dynamic pages with Jekyll. I self-host and use a `.htaccess` file for setting the cache on assets and such. And then use Cloudflare to cache the full pages. I haven't had problems with anything being so aggressively cached that the latest content doesn't always show.

Occasionally an image or two doesn't update, and in that case I kill the page cache with Cloudflare.

I generally let browsers cache how they're going to cache to avoid http requests and increasing a sites performance. I'd bump around Stackoverflow since this really has little to do with my theme and is more suited for a web dev forum.

**Comment by Sciss** [comment]
Ok, thanks for the hint with `.htaccess`, might look into it. I get it mostly to work with the above META additions, but not 100% reliably it seems.
