### ISSUE TITLE
Javascript function being push down

### ISSUE THREAD

**Issue by nelsonmestevao** [mmistakes/minimal-mistakes#1126]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

--

## Expected behavior

I have added some custom *javascript* and it's working just fine. However, when I call the function which creates an animated image, this image goes to the bottom of the page.

What I added was [this](http://cube.crider.co.uk/twistysim.js) code and after I added in the custom head the following line:

```html
<script type="text/javascript" src="/assets/js/twistysim.js"></script>
```

And in a blog post I call a function like this:

```markdown
## Some title

blah blah blah

<script type="text/javascript">
TTk.AlgorithmPuzzle(3)
.alg("R")
.showAlg(true)
.controls(true)
.hoverButtons(true)
.hoverAlg(false)
('#ap1');
</script>
```

However the image created by that code inside of ```<script>``` tag instead of showing after `blah blah blah` text, shows up after every element of the page. An example is found [here](http://estevao.xyz/puzzles/notation/).

**Comment by mmistakes** [comment]
Sorry not familiar with that script. My guess is you need to specify an empty element or selector to inject that content into. Not seeing that in your init function so maybe it's just defaulting it to the bottom of the page.

**Comment by nelsonmestevao** [comment]
I have tested it with regular html and it worked, like [here](https://nelsonmestevao.github.io/main/index).

So I was thinking it was some option that was added to the sass's files or something. Thank you anyway.

**Comment by mmistakes** [comment]
That regular page doesn't have any other content on it so it's not exactly a true test. The script content appears at the bottom of the page and nothing follows it. Still think there's something missing to tell it where to insert the content instead of the bottom of the page.

I seriously doubt it's anything to do with the theme's stylesheets.

**Comment by nelsonmestevao** [comment]
It has other h2 tags, and the <br> tags are working as expected. However it's not the same in the theme. Do you think its jekyll's related and not the theme? I will test it with the default theme.

**Comment by mmistakes** [comment]
The issue is your script for whatever reason is building all of the `svg` elements outside of the main content `article`. Which is why the puzzles are all showing up at the bottom of the page.

I know absolutely nothing about the script you're using, but I would start with their docs. Scripts of this nature should allow you to assign a selector when you configure it to tell the script where it should build. I can see in your source you have the script in the main content, but if you inspect the DOM you'll see it's putting the puzzles in the wrong location.

![svgs](https://user-images.githubusercontent.com/1376749/28268331-eb21b780-6acb-11e7-9b9d-0622928156ca.jpg)

The theme has nothing to do with that, which tells me its 100% an issue with the custom script. This isn't happening with your simple test because there isn't a complex layout or additional content like a footer or page navigation like the MM theme.

**Comment by nelsonmestevao** [comment]
Thank you. Now I see it... Do you have any suggestion how to force it? 

I will contact the [creator](http://cube.crider.co.uk/twistysim.html) of the script. Thank you very much for your help!

**Comment by mmistakes** [comment]
The creator of the script is probably your best bet. Other than some basics, JavaScript really isn't my thing so I won't be much help on fixing it.

**Comment by nelsonmestevao** [comment]
Dear Michael,

You can now close this issue.

The last element is ('#ap1') and it's an identifier. I didn't know that. So basically I just need to place `<div id="ap1"/>` wherever I want it to show. The [author](https://github.com/Cride5) of the script bring that out.

Thank you very much for the help.

**Comment by mmistakes** [comment]
Glad you got it sorted out.
