### ISSUE TITLE
Gen 4.5 requirements 

### ISSUE THREAD

**Issue by justinrummel** [mmistakes/minimal-mistakes#1154]
Tried to do a bundle update, but it seems 4.5 has some new requirements that domino to one specific issue: version of ruby. 

MacOS Sierra has ruby 2.0.0, while Jekyll/liquid are pushing forward to at least 2.1. 

How are you managing your version of ruby?

**Comment by mmistakes** [comment]
Sounds like a Jekyll issue. For macOS I use rvm to manage Ruby but I haven't messed with it in years. I'll have to check what version I'm using. 

Same for Windows. In definitely not using anything recent there since it's sort of a pain to install Ruby on Windows 7.

The only dep that was bumped with this MM release was Jekyll to 3.5. Which also bumps Liquid from 3 to 4 I believe. Not aware of any new Ruby requirements but maybe check their issues to see if it's a known problem. 

3.5 and 3.5.1 have been out for awhile.

**Comment by mmistakes** [comment]
https://github.com/jekyll/jekyll/issues/6216

**Comment by justinrummel** [comment]
Definitely a Jekyll/OS issue.

[Followed these instructions](http://railsapps.github.io/installrubyonrails-mac.html) to get ram installed along with [this for using rvm with fish shell].  Still having issues with fish shell, but that is happening more and more... may just remove that shell as my default.

**Comment by mmistakes** [comment]
Ok. Don't have experience with fish shell so I'll be of little help. 

Closing as this isn't theme related.
