### ISSUE TITLE
Owner avatar and bio are not shown on homepage in mobile view

### ISSUE THREAD

**Issue by AndreiDev** [mmistakes/minimal-mistakes#117]
Hi!
When using the blog on mobile, the homepage (and the about page) are loading without the owner avatar or the bio. Is there a way to embed them nicely into the mobile view?
Thanks,
Andrei.

**Comment by mmistakes** [comment]
I purposely removed it because it felt more like a distraction on those pages and I wanted the designs to focus on the content. The site's author info is less important on an post index page than on the actual posts.

You can certainly add them back though. You'll need to take this bit of HTML and Liquid from the `_layouts/post.html` and repurpose it into `page.html`, `home.html`, and the `post-index.html` Jekyll layouts.

``` html
<footer role="contentinfo">
  <div class="article-author-bottom">
    {% include _author-bio.html %}
  </div>
  <p class="byline"><strong>{{ page.title }}</strong> was published on <time datetime="{{ page.date | date_to_xmlschema }}">{{ page.date | date: "%B %d, %Y" }}</time>{% if page.modified %} and last modified on <time datetime="{{ page.modified | date: "%Y-%m-%d" }}">{{ page.modified | date: "%B %d, %Y" }}</time>{% endif %}.</p>
</footer>
```

There's probably some CSS and other markup finessing you'll need to do, but should be a good start.
