### ISSUE TITLE
reduce font size 

### ISSUE THREAD

**Issue by germayneng** [mmistakes/minimal-mistakes#1184]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

i have searched for previous solution on reducing font size. Tried both methods but still the font did not change. For reference, my site is here: 
https://github.com/germayneng/germayneng.github.io

I tried the reset.scss method 

```
 @include border-box-sizing;

html {
  /* apply a natural box layout model to all elements */
  box-sizing: border-box;
  background-color: $background-color;
  font-size: 8px;

  @include breakpoint($medium) {
    font-size: 10px;
  }

  -webkit-text-size-adjust: 80%;
  -ms-text-size-adjust: 80%;
}
```

hope you can provide me a solution since the font is too huge. Ideally, i want to reduce the font size of posts. an example: 
https://germayneng.github.io/Elastic_Net_Regularization.html

**Comment by mmistakes** [comment]
Editing the `font-size`s in reset.scss is the right way. The reason it's not working for you is due to misconfiguration and the location of the CSS files.

Reference the [documentation about structure](https://mmistakes.github.io/minimal-mistakes/docs/structure/) and [MM repo](https://github.com/mmistakes/minimal-mistakes). Not sure why you moved `_sass` inside of `assets/` but that needs to live at the root. Also `assets/css/main.css` shouldn't existed in your repo. That's the compiled stylesheet which is what the theme is using. That's why your changes aren't appearing.

Get rid of that and replace with [`assets/css/main.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/css/main.scss). If you make those two changes correctly `main.scss` will load all of the Sass partials in `_sass`... which you can customize and Jekyll will build a new `_site/assets/css/main.css`.

**Comment by germayneng** [comment]
hello, 

i have made the changes you mentioned. Now i have this error 

>  Your site is having problems building: Your SCSS file assets/css/main.scss has an error on line 3: File to import not found or unreadable: minimal-mistakes. Load path: /hoosegow/.bundle/ruby/2.4.0/gems/jekyll-theme-primer-0.5.0/_sass. For more information, see https://help.github.com/articles/page-build-failed-invalid-sass-or-scss/.

**Comment by mmistakes** [comment]
Still looks like you don't have the `_sass` folder setup correctly. I would suggest starting over and fork the theme so you have all the correct files. 

Then make your edits, set the config, add content, etc.
