### ISSUE TITLE
Adjusting site title in top navigation menu

### ISSUE THREAD

**Issue by straurob** [mmistakes/minimal-mistakes#1192]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment information

- **Minimal Mistakes version: 4.5.1** 
- **`github-pages` or `jekyll` gem version:** 
- **Operating system:** 

---

## Usage Questions

I'm setting up my blog with minimal-mistakes and there are two questions about the navigation. Pleae see https://straurob.github.io for a development version (GitHub repo: https://github.com/straurob/straurob.github.io).

1. I'd like to move the title "Thoughts About Testing" more to the left but cannot find information how to do that.
2. Is it possible to include the site description below the site's title?

**Comment by justinrummel** [comment]
1.
I believe the title is due to the max-width on masthead__inner-wrap.  If you change that to something larger such as 1900px it looks correct.  To do this you will have to create a new CSS overwrite.  [Read this conversation](https://github.com/mmistakes/minimal-mistakes/issues/957) all the way to the end to best understand what file needs to be created and how it works. 

![](http://cl.rummel.co/2J3D3D2d2p0B/Image%202017-08-21%20at%207.46.30%20AM.png)

2.
The great thing about gem themes is you can always overwrite the default files with your own.  Download the [_includes/masthead.html](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/masthead.html) file and update it so it appears the way you want.  Your local version will overwrite what is default coming from the gem.

**Comment by straurob** [comment]
1. Thanks to your hint I found that the file _variables.scss contains a variable $x-large which value can be changed to e.g. 1920.
2. Still looking for a nice styling but I got the point.

Thanks @justinrummel for your support.
