### ISSUE TITLE
Display most recent posts on home page

### ISSUE THREAD

**Issue by eroth** [mmistakes/minimal-mistakes#1251]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: 4.4.1
- **Jekyll version: 3.4.3
- **GitHub Pages hosted: yes
- **Operating system: macOS 10.12.6 (Sierra)

---

Hi, I'm using your theme on my home page in a pretty standard way (site at http://hex00sells.com/fresh-start/, repo at https://github.com/eroth/fresh-start).  For the `feature_row` I'm using on my home page, I'd like it to be populated with the 3 most recent posts from my `_posts` directory.  Can I access the `feature-row` object in Liquid under the YAML front matter and modify it? The Jekyll docs (https://jekyllrb.com/docs/frontmatter/) seem to say you can (although in their examples the HTML is being built directly under the front matter and not in another file, as happens in this case), but I'm not able to.

Just to test what I want to do, I tried deleting the `url` and `btn_label` from the front matter for `feature_row` and adding it in the Liquid code underneath—you can see this in my https://github.com/eroth/fresh-start/tree/feature-row branch:

~~~
---
layout: splash
permalink: /
header:
  overlay_color: "#5e616c"
  overlay_image: /assets/images/homepage/homepage-holiday-lounge.jpg
  cta_label:
  cta_url:
  caption:
excerpt: 'Stories of bartenders and service industry workers who have gone through the difficult process of transitioning to new careers and marking major life changes. A source of inspiration and a resource for others looking to do the same.'
intro:
  - excerpt: 'Recent stories:'
feature_row:
  - image_path: /assets/images/homepage/homepage-featured-story-1.jpg
    alt: "customizable"
    title: "Evan Roth"
    excerpt: "I bartended in nightclubs and restaurants for eight years, went back to school for a degree, and now work in tech."
  - image_path: /assets/images/homepage/homepage-featured-story-2.jpg
    alt: "fully responsive"
    title: "Emily Moore"
    excerpt: "I've been bartending since college and felt like I would never be able to stop. Now I'm working towards doing Acupuncture."
    btn_label: "Read More"
  - image_path: /assets/images/homepage/homepage-featured-story-3.jpg
    alt: "100% free"
    title: "Rick McNulty"
    excerpt: "After a long struggle trying to figure out what I wanted to do next, I eventually went back to school and got a degree."
---
{% for f in feature_row %}
  {% assign f.title='test' %}
  {% assign f.url='test' %}
  {% assign f.btn_label='Read More' %}
{% endfor %}

{% include feature_row id="intro" type="center" %}

{% include feature_row %}
~~~

Can what I'm trying to do be done, or am I just going about it the wrong way? Or do I need to take a different approach? I've also tried putting that Liquid snippet after `{% include feature_row %}` and accessing `feature_row` with `page.feature_row`, but that didn't work either.  Alternatively, I could create a new modified `feature_row` layout that would do this, but thought I'd be able to do it this way. Thanks!

**Comment by mmistakes** [comment]
It's possible, but not without some work on your part. I can give you some hints to get you started.

If you look at the [feature row include](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/feature_row) you'll see I'm creating a variable called `feature_row` that is grabbing all of the data in the current page's YAML Front Matter.

Since you want to grab that same data from a set of posts and not the current page, you need to scope it differently.  To start you'll need to modify `/_includes/feature_row`. If you only plan to use this on a page or two then you could dump the HTML/Liquid directly in the body of the page. Otherwise I'd create a new include to use (e.g. `feature_row_posts`).

You can keep the [meat of the feature row](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/feature_row#L11-L47) logic, but ditch the 5 [if/assign lines at the top](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/feature_row#L1-L5). Then loop over `site.posts`, place a limit of `3` (or however many posts you want to show up), and you should be good to go.

```html
<div class="feature__wrapper">

  {% for f in site.posts | limit:3 %}
     <!-- can stay the same as the current feature_row include -->
  {% endfor %}

</div>
```

As long as your posts have [Front Matter data](https://mmistakes.github.io/minimal-mistakes/docs/helpers/#feature-row) that correspond with what `feature_row` expects, you'll be fine. Of course this is untested so I might have missed something. But should be enough to get you started.

**Comment by mmistakes** [comment]
You can also use the [grid view include](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#grid-view) to do something similar. It's almost the same visually as a feature row, just 4 items across instead of 3, and not button.

Best part you don't have to modify any of the includes to use it.

![grid view](https://mmistakes.github.io/minimal-mistakes/assets/images/mm-archive-grid-view-example.jpg)

**Comment by eroth** [comment]
Thanks! I'll have a look at both ideas.

**Comment by eroth** [comment]
Thanks for the suggestions! I ended up going the route of creating a new `feature_row` include, since I just wanted 3 posts across.  Using `{% for f in site.posts limit:3 %}` in the logic worked great.
