### ISSUE TITLE
Conflicting quick-start instructions about assets

### ISSUE THREAD

**Issue by asarkar** [mmistakes/minimal-mistakes#1268]
I'm migrating a GitHub pages site to the Gem version. The [Quick-Start](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/) instructions say:
> Start by removing _includes, _layouts, _sass, assets folders

Later it says:
> The preferred location is now /assets/images/

Obviously, if the location of images is supposed to be `/assets/images/`, the `assets` directory shouldn't be removed. But if the `assets` directory is not deleted, `bundle exec jekyll serve` fails with the following error:

```
      Generating... 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    File to import not found or unreadable: variables. Load path: /var/lib/gems/2.3.0/gems/minimal-mistakes-jekyll-4.6.0/_sass on line 14
jekyll 3.5.2 | Error:  File to import not found or unreadable: variables.
Load path: /var/lib/gems/2.3.0/gems/minimal-mistakes-jekyll-4.6.0/_sass on line 14
```

**Comment by mmistakes** [comment]
You want to remove all of the files/folders within `/assets`, except anything you added as content. Meaning if you added images for posts and pages you'd leave those.

CSS, JavaScript, and fonts that are part of the forked theme need to be removed. Otherwise if you keep them and they exist in the gem version, they will be overrided. 

Here's what's in the theme gem, if you have any of these files/folders in `/assets`, remove them.

https://github.com/mmistakes/minimal-mistakes/tree/master/assets
