### ISSUE TITLE
What to do with _pages directory if migrating to Gem version?

### ISSUE THREAD

**Issue by asarkar** [mmistakes/minimal-mistakes#1270]
The instructions don't mention `_pages`. Do I keep it or delete it? There are various `*-archives.html` files in it that seem to be useful.

**Comment by mmistakes** [comment]
They're not mentioned because `_pages`, `_posts`, and any collections you've created are all content. The theme gem is layout and style only. You don't have to do anything with them, unless you're migrating from a really old version of the theme and the `layout` changed.

If that's the case you'll want to consult the content sections of the docs.

- [Working with Posts](https://mmistakes.github.io/minimal-mistakes/docs/posts/)
- [Working with Pages](https://mmistakes.github.io/minimal-mistakes/docs/pages/)
- [Working with Collections](https://mmistakes.github.io/minimal-mistakes/docs/collections/)

**Comment by asarkar** [comment]
Ok, thanks.
