### ISSUE TITLE
Move "On This Page" to left "column" and let content spread further to right

### ISSUE THREAD

**Issue by sdruskat** [mmistakes/minimal-mistakes#1298]
- [X] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** (4.6.0, 4.5.2)
- **Jekyll version:** 3.6.0
- **GitHub Pages hosted:** yes
- **Operating system:** Ubuntu 16.04

---

I have tried figuring out flexboxes and susy, but I'm afraid I have too little knowledge about modern CSS to figure out how to achieve the following for my pages using the `single` layout.

- I'd like to move the "On this page" aside to the left "column" and make it sticky (i.e., let it replace the author info or custom nav box).
- I'd then like to have the content to spread all the way to the right up until where the right end of the old "On this page" box would be (can I achieve that with just replacing the `padding-right` in *page* and *archive*?)

Many thanks for your help, I'm at my wit's end.

**Comment by mmistakes** [comment]
Moving the "On this page" table of contents is really tricky. What makes it complicated is it has to reside inside the content container because it's created by Kramdown when it parses the content.

I'm using some CSS trickery (eg. negative margins) to pull it outside of that container and into the space on the right (padding). This works because there is no other content there. I can't think of any way to move it to the left and not interfere with the author sidebar.

Ideally you'd just place that content inside of the sidebar container, but that's not possible if you're using Kramdown's automatic TOC feature. Your options are to use the [custom sidebar nav](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#custom-sidebar-content) and manually specify the links, or use some sort of Javascript based solution to create a table of contents similar to how Kramdown does it.

And yes, if you remove the right padding on `.page` and strip out make the width `100%` (remove the `calc` stuff), it'll fill the remaining space instead of centering.

Search through the closed issues as I've covered a lot of this numerous times before and you'll likely find a more detailed explanation.

**Comment by sdruskat** [comment]
Thanks for your very swift reply (and the great theme of course). I can see what you mean.

What about simply "disappearing" the left column altogether, letting the content start where it would have started, keep "On this page" where it is, and let the content fill the remainder of the space? I imagine this would be simpler as you'd only have to adjust the susy magic? I had looked for that already as well, but am sorry to report I couldn't find the breakpoint/susy/??? element in question.

Thanks so much!

**Comment by mmistakes** [comment]
It's currently been designed to have the main content centered on the page regardless if there are sidebars on the left or right. Changing that would alter the overall design of the theme so it's not something I'm going to do, but there's nothing stopping you from turning the theme into something custom to meet your needs.

I ripped out much of the Susy SCSS from the layout so that could be why you're not seeing it. For the most part I'm simply floating containers and using `calc` to pad out space for the sidebar instead of Susy mixins.

If you want to push the Kramdown TOC to the left instead just make sure you don't have an author sidebar on the page. Then reverse much of the logic that pads the right to pad the left, then float the `.toc` to the left instead.

**Comment by sdruskat** [comment]
Thanks. Reversing the padding is clear, but how do I float the `.toc` to the left? Sorry for being a nuisance.

**Comment by mmistakes** [comment]
My bad. Meant you'll have to `float: left` `.page__content`. There's probably a bunch more tweaks, you essentially reverse paddings, positioning, margins etc.

`sidebar__right` for instance will need the negative margin on the left instead of the right, and will need to be absolutely positioned to `left: 0` instead of `right: 0`.

**Comment by sdruskat** [comment]
Yes, thanks, just found `.page__content` to work. Excellent, thanks!

**Comment by chrisdaaz** [comment]
@sdruskat i am trying to accomplish the same thing. can you share what you did to make it work? was it simply altering `.page__content` and reversing the padding, or was there a lot more involved?

**Comment by chrisdaaz** [comment]
OMG I MADE IT WORK. nvm @sdruskat ! 

Here's how:

**sidebar.scss**

`.sidebar_right`
- change `float: right;` to `float: left;`

`@include breakpoint($large)`
- change `right: 0;` to `left: 0;`
- change `margin-right` to `margin-left`
- change `padding-left` to `padding-right`

`@include breakpoint($x-large)`
- change `margin-right` to `margin-left`

**page.scss**

- add `float: left;` to `.page__content`
