### ISSUE TITLE
main.scss error

### ISSUE THREAD

**Issue by gt987** [mmistakes/minimal-mistakes#1312]
I have recently merged the latest branch to my repo and received an error from GitHub which I'm not sure about (line 19?). The page build failed for the `master` branch with the following error:

Your SCSS file `assets/css/main.scss` has an error on line 19: Invalid CSS after "...: $lighter-gray": expected "{", was ";".

- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes/no
- **Operating system:** 

---

**Comment by mmistakes** [comment]
That error is because you have some bad CSS in the various `.scss` files found in your `_sass` folder.

When you merged in the master branch you likely didn't deal with merge conflicts properly and it's leaving in things like `<<<<<<< HEAD` and `========` throughout your CSS, which isn't valid.

If you're not customizing any of the files in `_sass` I would suggest you just delete the entire folder and copy them fresh from the [MM repo](https://github.com/mmistakes/minimal-mistakes/tree/master/_sass). Or go line by line and remove Git merge comments in them.

**Comment by gt987** [comment]
Thanks a lot for the quick reply. I just fixed it by hand as you were suggesting…
I've just started using GitHub, so I’m often not sure on how things will work out. 

Anyway, thanks! You have done a great work!


GT
