### ISSUE TITLE
Mixed Content for HTTPS

### ISSUE THREAD

**Issue by tenapril** [mmistakes/minimal-mistakes#1318]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---
## Environment informations

- **Minimal Mistakes version: latest
- **Jekyll version: latest
- **GitHub Pages hosted:** yes
- **Operating system: win7 64bit

## Expected behavior

All my posts on jekyll are HTTPS secured, but only my home and other pages are mixed content,
idk how to solve this as i am new to this.

here are the examples:
https://andrewkusumo.science/
![image](https://user-images.githubusercontent.com/25809352/32046747-1ac3a3da-ba6e-11e7-93e5-facb5894e53d.png)
https://andrewkusumo.science/first-post/
![image](https://user-images.githubusercontent.com/25809352/32046771-25a12fa2-ba6e-11e7-901c-50f71f722799.png)

Thanks for the help :)

**Comment by mmistakes** [comment]
The mixed content warning is due to you loading assets over `http` instead of `https`. If you open your browser's web development tools and look at the console it'll tell you exactly what the issue is.

![image](https://user-images.githubusercontent.com/1376749/32051522-f1d13d34-ba22-11e7-9abe-1aec4fce58bf.png)

Looks to me that the header/overlay image on your homepage has the following path `http://andrewkusumo.science/assets/images/header.jpg` when it should be `https://andrewkusumo.science/assets/images/header.jpg`.

Since you didn't provide a repo to look at I have no idea what your YAML Front Matter is for that page. Verify it is a relative path and not starting with `http://`. Also make sure you've set your site `url` in **_config.yml** to `https://andrewkusumo.science` and not left it blank or using `http://`.

**Comment by tenapril** [comment]
@mmistakes thanks a lot man! the problem is solved by filling the url in the _config.yml
![image](https://user-images.githubusercontent.com/25809352/32053866-b43bee9c-ba86-11e7-965a-a60bc453d15c.png)

Really appreciate your help :)
