### ISSUE TITLE
compress_html not working

### ISSUE THREAD

**Issue by spiraltaiji** [mmistakes/minimal-mistakes#1324]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.6.0
- **Jekyll version:** 3.5.2
- **GitHub Pages hosted:** no
- **Operating system:** local: linux mint; production: netlify

---

## Expected behavior

compress_html should work with a suitable default.html in _includes 

## Steps to reproduce the behavior

compress_html, using the following options in _config

```
compress_html:
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [] # development
```
With an edited default.html file in _includes that has this front matter:

```
---
layout: compress
---
```
should strip html comments. It does not. Consequently, netlify's own build does not run compress_html.

however, editing default.html directly in my local gem file directory does produce the desired behavior.

**Comment by mmistakes** [comment]
What's not clear to me is are you using the gem version of the theme or a forked version? If the gem version you have to override `_layouts/default.html` with a local version to set `layout: compress`.

Do you have a public repo? I stopped supporting the compress layout as it can cause issues and has a few caveats that can break builds if you don't conform to its limitations.

Curious, have you tried using some of the Jekyll plugins that minify HTML or something like Gulp/Grunt to do it for you? Since you're not hosting with GitHub Pages you're not limited to the inferior `layout: compress` Liquid method of minifying.

**Comment by spiraltaiji** [comment]
Yikes, my bad. I copied default.html into _includes, not _layouts. It works as intended, including on deployment to netlify.

I thought I'd use html_compress as it is sufficient to pass google's pagespeed insights tests for html compression. That's sufficient for my needs but I'd like to retain github compatibility for the future.

Thanks for a wonderful theme!
