### ISSUE TITLE
Linking Author avatar and name to site root

### ISSUE THREAD

**Issue by shredtechular** [mmistakes/minimal-mistakes#1331]
- [X] This is a question about using the theme.
- [X] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

## Feature Request Question

In your docs, you mentioned when in doubt on contributing to ask first, so this is just a question if you would want to consider a feature pull request for making the author avatar and name in the sidebar nav linkable -- for example, I have a customer interested in making those link back to the site root for users.

This might fall into the customization bucket that we should do this in our child of your theme, but wasn't sure if maybe you thought this might be desired by a number of your other users to consider a pull request for it?

Thanks!

**Comment by mmistakes** [comment]
I think this might fall in the customization bucket. I'm not sure if this could be done "clean" so that it is easy to turn off/on for those who don't want it.

What makes it complicated as not everyone who'd want the author avatar and name to link back somewhere, will want it to go to the site's root. In the cases where blogs support [multiple authors](https://mmistakes.github.io/minimal-mistakes/layout-author-override/) this would be problematic.

This is why I've included the [website `uri` key](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/author-profile.html#L37-L43) for the author sidebar, to provide a way to link back to the author's site.
