### ISSUE TITLE
Support mutliple authors in one post

### ISSUE THREAD

**Issue by ldt116** [mmistakes/minimal-mistakes#1341]
Add ability to support multiple authors for one post. I think we can create a YAML Front Matter like in this [post](https://stackoverflow.com/questions/15189008/how-can-i-have-multiple-authors-for-one-post-in-jekyll)

```yml
authors:
- author1
- author2
```
And the list authors should be displayed on left column.

- [x] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

**Comment by ldt116** [comment]
Currently, I archive this by below work around code. I am new to Jekyll so that this snippet contains  duplicated code. Hope you can make update.

https://raw.githubusercontent.com/ldt116/bkolp/master/docs/_includes/author-profile.html

**Comment by ldt116** [comment]
I made a little improve the code for supporting multiple authors in single post by adding the following code in `author-profile.html`

```
{% assign authorCount = page.authors | size %}
{% if authorCount == 0 %}
  {% if page.author and site.data.authors[page.author] %}
    {% assign author = site.data.authors[page.author] %}
  {% else %}
    {% assign author = site.author %}
  {% endif %}
  
  {% assign authors = {{author.authorid | split: "," }} %}
{% else %}
  {% assign authors = page.authors %}
{% endif %}

<div itemscope itemtype="http://schema.org/Person">
  {% for authorid in authors %}
  <p>
...
  </p>
  {% endfor %}
</div>
```

But there is a little change that we need to add field `authorid` in `_config.ymml` to make the no author post automatically add the default site author.

**Comment by mmistakes** [comment]
I don't know that this is something 80% of the theme's users would need. In fact I can't recall ever seeing a blog post that listed multiple authors, which tells me it's a fairly niche request.

The best route is for you to customize the author profile as you've done above. But I don't think this is something I'd be interested in incorporating into the theme's core, especially due to the Liquid `for` loop and possible performance implications that would have.

**Comment by infominer33** [comment]
> I don't know that this is something 80% of the theme's users would need. In fact I can't recall ever seeing a blog post that listed multiple authors, which tells me it's a fairly niche request.
> 
> The best route is for you to customize the author profile as you've done above. But I don't think this is something I'd be interested in incorporating into the theme's core, especially due to the Liquid `for` loop and possible performance implications that would have.

Would you have any suggestions on how to improve that script? I'm using MM for a few github organizations, and it would be nice to show who has contributed to a particular page... 

I'd probably be better off using github metadata, but I'm no coder... 

If you have any thoughts on the matter, I'd really appreciate your opinion.

---
note: I really love your work, and have been using your themes since a few months now... no other theme I've touched compares to minimal mistakes.. and it's incredible how you build hugo versions at the same time.. or idk how you do that really I guess you build both as a team together

**Comment by mmistakes** [comment]
@infominer33 You can assign a different author for a post and they will show up in sidebar instead of the site default. What the theme doesn’t support is assigning more than one author for a post, which is what this issue was requested.

Check the sample posts and theme documentation for more info.

https://mmistakes.github.io/minimal-mistakes/layout-author-override/
https://mmistakes.github.io/minimal-mistakes/docs/authors/

**Comment by infominer33** [comment]
yes, that's what I meant. 

Example: 

![](https://imgur.com/W2oZ5Zs.png)

Just hoping for your suggestion, I might use his script as is... but maybe you have a better idea I should explore

**Comment by mmistakes** [comment]
No really suggestions from me. The theme was designed to have a single author in the sidebar. Your best bet is ignoring the sidebar and just group the authors in the body in some sort of grid treatment. There’s no way they will all fit comfortable in a sidebar.

**Comment by infominer33** [comment]
oh yeah, I wasn't really thinking about the sidebar. Thanks for all your hard work and dedication! I'll figure out what I need from here.

**Comment by infominer33** [comment]
https://github.com/infominer33/infominer33.github.io/commit/d80cae2f1138b901f6ca205abd0e1e27541780d9

here is my solution for including authors at the bottom of each post just like tags and categories

which I pieced together by examining your code and this answer on stack overvlow

https://stackoverflow.com/questions/15189008/how-can-i-have-multiple-authors-for-one-post-in-jekyll

**Comment by jphconstantin** [comment]
@mmistakes: I understand your position but your documentation mentions the possibility to indicate multiple authors !
yes its a niche: a post or a page can be modify by a team !
