### ISSUE TITLE
Posts don't look like how they're supposed to

### ISSUE THREAD

**Issue by brandonskerritt** [mmistakes/minimal-mistakes#1371]
Posts look 'ugly' and do not appear how they are supposed to appear. Might be an issue with the front matter but I've attempted to follow the online guide.

- [ x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes
- **Operating system:** Windows 10

---

## Expected behavior

For posts to look like [this](https://mmistakes.github.io/minimal-mistakes/post/post-future-date/)

Link to my repo
https://github.com/brandonskerritt/brandonskerritt.github.io

Link to a post on my website:
https://brandonskerritt.github.io/Hello-World/

I  cloned the  theme, customized _config.yml, added my own posts and the posts don't look nice, or how they're supposed to.

**Comment by mmistakes** [comment]
Yup, your front matter is wrong. You need to set the [correct layout](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#single-layout).

Instead of `layout: post` change them to `layout: single`.

If you don't want to add `layout: single` to every post you can also use Jekyll's [front matter default feature](https://jekyllrb.com/docs/configuration/#front-matter-defaults) and set it in your `_config.yml` to apply to all posts.
