### ISSUE TITLE
email is always required however i configure

### ISSUE THREAD

**Issue by abekthink** [mmistakes/minimal-mistakes#1412]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I believe this to be a bug with the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Information
When I configure `staticman_v2` comments in staticman.xml, email is optional, but it doesn't work when i use `requiredFields: ["name", "message"]`.
However i configure whatever, the website always show that email is required(*).
So i continue to see the code `_includes/comments.html`, there is the hard code that email must be required.

**Comment by mmistakes** [comment]
That's correct, email is currently hardcoded as required. I went with that as a sensible default. Since `_includes/comments.html` has no clue what you set as required in the Staticman config file there's no way to make it toggleable.

If you don't want the required text to appear you'll need to override that include by removing `<small class="required">*</small>`.

**Comment by abekthink** [comment]
Thanks, i had overrided `_includes/comments.html`, and changed the label `comment_form_email_label` in `_data/ui-text.yml` to show the correct text, then it worked well.
Thanks again.
