### ISSUE TITLE
Question: How to force all items in menu to go to drop down menu, instead of letting them vary by screen width?

### ISSUE THREAD

**Issue by hbahamonde** [mmistakes/minimal-mistakes#1418]
- [X] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes
- **Operating system:** OSX

---

## Expected behavior

  Regardless of the width of the mobile device, I'd like to send all my menu items to the drop down menu. 

I find it odd that, say, in vertical (in mobile) there is just one item (and all the rest in the drop down menu), while in landscape (in mobile) there are three elements, for instance. 

Desktop stays the same. 

## Steps to reproduce the behavior

If you go to www.hectorbahamonde.com **using your mobile device**, you will see that there is only the "research" item. The rest of the items are in the drop down menu. I'd like to force all items to go into the drop down menu. 

Thanks so much!

**Comment by mmistakes** [comment]
See issue https://github.com/mmistakes/minimal-mistakes/issues/1301

There isn’t an easy way of doing this without heavily customizing the theme and its CSS.

**Comment by bkmgit** [comment]
@hbahamonde  The logic for this is in https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/plugins/jquery.greedy-navigation.js which is pre-built into https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/main.min.js as described at https://mmistakes.github.io/minimal-mistakes/docs/javascript/
To get the effect you want, rather than removing one link at a time, once the window size drops below a certain width, change the javascript file to put all links in the hamburger menu.  The original code is available at https://github.com/lukejacksonn/GreedyNav with a preview you can experiment with available at https://codepen.io/lukejacksonn/pen/BowbWE
