### ISSUE TITLE
author not show when article save to pocket

### ISSUE THREAD

**Issue by mastito03** [mmistakes/minimal-mistakes#142]
when I tried to save articles to http://getpocket.com. the author's name does not appear. even in another article I am trying to save, name of the author comes up with the wrong name.

in the theme-setup article, author name that appears is not my name but 'author override'

**Comment by mmistakes** [comment]
If you can dig up how Pocket interrupts content I can investigate what's going on. As far as I've tested the theme uses rich snippets to properly markup publisher/author data, published date, title, etc etc. At least as far as [Google's Rich Snippets](https://developers.google.com/structured-data/testing-tool/) testing tool is concerned.

**Comment by jtobiasl** [comment]
hello mr. ary,
hey, i'm just a noob to github but i'm trying to install your theme to give it a test run & i'm finding it to be high rocketscience.

it's the first theme i've not been able to successfully install.

why is this such a pain in the ass?

please help, 
j

**Comment by mastito03** [comment]
I do not know how pocket work. when I tried to look at the data structure another website, I can not find special features that indicate the author.
things that look the same, author part all located within the section. but when I tried to move into the section, still no luck.

I also tried adding id, ref, class to the author. still no luck. I refer to the theme-setup page that author is wrong, 'author override' has an element of 'author' in its ref.

I also try to keep in https://www.readability.com/, author also do not appear.

**Comment by mmistakes** [comment]
@jtobiasl Nature of the beast. Jekyll isn't really the most user friendly piece of software for non-devs yet. It doesn't have an official way of installing themes which is why all of this is such a pain right now. Getting Jekyll installed and running properly can be a challenge in itself, let alone copying over someone's repo to apply as a "theme."

Not much else I can do about that right now.

**Comment by mmistakes** [comment]
@mastito03 I tried both Pocket and Readability. I'm not seeing anything weird with the author names being wrong on posts or other pages. Theme Setup is the only strange one, and I believe it's because it has the author override code on the page. Pocket and Readability are getting confused by it, which there's nothing I can do about that.

Closing because this seems to be an edge case for a page that is specific to the theme. I'm not concerned that it says "Author Override" there since you shouldn't be including that page with your site anyways...

![screen shot 2015-05-01 at 7 44 55 am](https://cloud.githubusercontent.com/assets/1376749/7429786/087771bc-efd6-11e4-9432-fbc60ceb7d1d.png)


![screen shot 2015-05-01 at 7 41 03 am](https://cloud.githubusercontent.com/assets/1376749/7429770/c8a3e926-efd5-11e4-9bf0-f29207f239d1.png)

![screen shot 2015-05-01 at 7 41 48 am](https://cloud.githubusercontent.com/assets/1376749/7429771/cbcf6c4c-efd5-11e4-8f51-aa332e802cf1.png)
