### ISSUE TITLE
Footer covers text at bottom of page

### ISSUE THREAD

**Issue by peterewills** [mmistakes/minimal-mistakes#1427]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: 4.8.1** 
- **Jekyll version: 3.6.2**
- **GitHub Pages hosted: yes** yes/no
- **Operating system: macOS** 

---

## Description of issue

I am surprised to see that the footer covers the text at the bottom of the page. Occurs on Firefox, Safari, and Chrome. Perhaps related is the fact that when I load the page, the footer does not appear until I scroll down (i.e. top of footer begins exactly at the bottom of the window as the page loads).

I doubt this is an issue with the theme itself, since it does not happen on `mmistakes.github.io`. However, I'm unsure how to proceed in addressing it; any help is appreciated.

## Steps to reproduce the behavior

Clone github.com/peterewills/peterewills.github.io, and do `bundle exec jekyll serve`. Page **may** also be available at pwills.com, but the cleanest bet is to clone and serve the site locally. Then, look at the bottom of (for example) `/about/`, or `/professional/`. 

Here's a screenshot of what I see at the bottom of `/professional/`:

![screen shot 2017-12-28 at 7 05 43 pm](https://user-images.githubusercontent.com/12958484/34427684-25c3b714-ec02-11e7-8198-128191cce42f.png)

**Comment by mmistakes** [comment]
The problem is you are overriding `_includes/scripts.html`. Your version of [`scripts.html`](https://github.com/peterewills/peterewills.github.io/blob/master/_includes/scripts.html) is missing the main JavaScript file needed for most of the theme (sticky footer, collapsible menu, etc.).

What you'll want to do is duplicate [`scripts.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/scripts.html) bundled in the theme and then add your MathJax script.

Another option is to use the [custom footer include](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/footer/custom.html) to drop in your MathJax code. This appears before `scripts.html` so there's a possibility of a script conflict if you're trying to do some jQuery. But if you're just adding a conditional to load a CDN'd version of MathJax you should be fine.

**Comment by peterewills** [comment]
Brilliant! Thank you.
