### ISSUE TITLE
Archive authors using {% arhive-single type="grid" %} with author_profile CSS

### ISSUE THREAD

**Issue by nickgarlis** [mmistakes/minimal-mistakes#1448]
- [ ] This is a question about using the theme.
- [x ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---
 Are you interested in archiving authors like that ?
![screenshot from 2018-01-03 21-30-08](https://user-images.githubusercontent.com/25513006/34536339-75c85fce-f0cd-11e7-8258-43f3812b3686.png)

I understand that something like that might not be in high demand since not many people use multiple authors but then again it would easy to merge since it's based on CSS that's already in the theme.

**Comment by mmistakes** [comment]
Yeah as you stated probably not in high demand since I don't see many multi-author MM sites.

It may also set implications that the theme supports "author archives", meaning you can easily pull up a page with all of the author's posts on the site. Something Wordpress and friends do by default.

In our case you'd just have a grid of pictures that link to whatever is set as their "home" URL. Which doesn't seem as useful to me.

**Comment by nickgarlis** [comment]
Sounds reasonable although it looks like I have implemented "author archives" too.

**Comment by mmistakes** [comment]
Archives in general are a pain point. You either use a plugin that auto-generates them or suffer through manually creating each since GitHub Pages doesn't support those plugins.

You wouldn't believe how many vanilla MM sites I see where the user hasn't notice that category/tag links at the bottom of every post go to broken links. All because they have to manually create those archive pages since the theme can't do it for you. Same thing for breadcrumbs.

Throwing author archives into that mix will make things even more messy I think. I hope that someday one of the two popular archive generating plugins are whitelisted ([jekyll-archives](https://github.com/jekyll/jekyll-archives) and [jekyll-pagination-v2](https://github.com/sverrirs/jekyll-paginate-v2))for use on GitHub Pages.
