### ISSUE TITLE
Custom CSS 

### ISSUE THREAD

**Issue by nickgarlis** [mmistakes/minimal-mistakes#1453]
- [ ] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

It would be useful to have a custom.scss file where the user could add their own CSS or maybe override existing CSS. I am aware of the skins folder but I personally like to keep my files as close as possible to the original files for easier updates. I also really don't like messing with minimal-mistakes.scss or main.scss. I believe there was a recent update on minimal-mistakes.scss which broke my theme after `bundle update`. I had imported another file inside of minimal-mistakes.scss and that prevented it from getting updated so I had to do it manually which was no biggy but kind of inconvenient.

**Comment by mmistakes** [comment]
`assets/css/main.scss` was built for exactly this purpose. It's intentionally minimal as it never changes, making it safe for you to at your own custom declarations of `@import`s after it loads in the main Sass file and any theme overrides.

It is only two lines and extremely safe for updating, as long as you make sure to not blow away your adds.

```scss
@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
@import "minimal-mistakes"; // main partials
```

Also this file hasn't been modified at all since it's introduction. The only change was when I added skins, which wouldn't have broken anything if you didn't catch the update.

**Comment by nickgarlis** [comment]
My apologies, I didn't know that was the purpose of this file.

**Comment by mmistakes** [comment]
No worries.

I've thought about adding another import after these that pointed to a blank `_custom.scss`. But that wouldn't really solve much as you'd still have to make sure any changes you made there were applied.

Since this file is so small already I didn't see much gain breaking it off into its own partial.

**Comment by idev** [comment]
Hello, sorry to caputre this one, but I don't really understand how to add custom css.

I have a custom css called "item.css" which is placed in the /css folder, also I copied the main.scss as described. If I now try to @import "item.css"; inside the main.scss, it is not working. What am I missing?

Thank you!

**Comment by mmistakes** [comment]
`item.css` needs to be a Sass partial to be imported. Rename to `_item.scss` and place in your `_sass` folder. Then it can be imported with `@import item` inside of `assets/main.scss`.

**Comment by idev** [comment]
Sorry but it is not working.
What I did is following the documentation regarding "Custom CSS":
-> add a css Folder, create a file main.scss, paste content from main.scss github.
-> add a Folder _scss, create a file _custom.scss, paste my css code
-> edit main.scss (in my css folder) and add @import _custom (with varations)

You also mentioned the asset folder, this is new to me, because the documentation is only talking about css folder.

Thank you!

**Comment by iBug** [comment]
@idev Read mmistakes's response carefully:

> **and place in your `_sass` folder**.

**Comment by idev** [comment]
Sorry Typo, is _sass Folder not _scss

**Comment by idev** [comment]
So what worked for me:
- Create a folder assets/css/
- Create a file main.scss and add github content (described in documentation)
- Create a custom.css (in assets/css)
- Import custom.css at main.scss (@import custom.css)

Sorry for the confusion, but I was not able to get it running with a Sass partial.
