### ISSUE TITLE
Unable to figure out how to display a main index page

### ISSUE THREAD

**Issue by havesomeleeway** [mmistakes/minimal-mistakes#1468]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes
- **Operating system:** 

---

## Expected behavior

I am trying to have a separate `page__title` on my side so that it does not display my `site-title`. 
![screenshot-2018-1-13 havesomeleeway github io](https://user-images.githubusercontent.com/25948209/34900630-9d08d4bc-f83c-11e7-8aaa-d4cefc172437.png)

This is what is inside my `index.html`:

```
---
layout: single
author_profile: true
title: false
header:
  overlay_color: "#5d1a38"
---
```

I was hoping that by setting `title` to `false` would change it but i was wrong, obviously.

## Steps to reproduce the behavior

I have cloned `single.html` into `_layouts` as I am trying to adjust `layout: single`.

**Comment by mmistakes** [comment]
Site title is controlled by `title` in your _config.yml and is part of the masthead include

https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/masthead.html#L5

`title` in a posts YAML is for `page.title`, which is very different from what outputs in the masthead heater.

**Comment by havesomeleeway** [comment]
Thanks for the swift ⚡️ response! Ill go and figure this out further. Will close this issue until I see the need to re-open it for more help. Cheers!

**Comment by havesomeleeway** [comment]
Reopening this issue to avoid creating another one. 

I'm struggling to find out how to add content to my `/` page. I have a `home.md` with the following YAML.

```
---
permalink: /
layout: single
---
Testing
```

However, at my main page, https://www.havesomeleeway.com, i don't seem to be able to see the word `Testing`. 

Under my `_config.yml`, i have set the url to my site and ignored baseurl as suggested. 

```
url                      : https://www.havesomeleeway.com
baseurl                  : # the subpath of your site, e.g. "/blog"
```

I can't seem to figure out what i'm missing here. Should i add an `index.md` inside `_pages`?

**Comment by mmistakes** [comment]
Issue isn't the theme, its standard Jekyll stuff. For a refresher give [their docs](https://jekyllrb.com) a good look over.

But the short of it is, Jekyll will use the path/filename of your source Markdown file along with your `permalink` structure set in _config.yml to determine where the `.html` is built and named.

In your case you have `/_pages/home.md` with a permalink of `/` which should work. But the problem is you also have `index.html` in the root of your project. That's likely overwriting `home.md` which is why you aren't seeing the changes.

Delete `index.html` and it should work. Or delete `home.md` and make your changes in `index.html`. Doesn't matter which option you take, you just can't do both.
