### ISSUE TITLE
Navigation conundrum..

### ISSUE THREAD

**Issue by Andy-ABTec** [mmistakes/minimal-mistakes#1510]
Hi, I think I'm starting to get my head round how the template works now... see http://test.ab-tec.co.uk, GitHub templated site from https://github.com/Andy-ABTec/minimal-mistakes

The "The Manual" link in the masthead pulls in a page that is the first of 5 "chapters" that go together to form the manual. I'm using a single sidebar navigation menu across all of these pages. 

This works but I've noticed that if I scroll down towards the bottom of the sidebar and click a link the relevant page/id loads as expected but I think that the sidebar is reloading as well because it is returning to displaying the top few items of its content. 

Is there a way of loading the main page content but keeping the position of the sidebar static?

Hope this make sense and as ever TIA for any help/advice!

**Comment by mmistakes** [comment]
What's going on is your links in the sidebar go to different pages. That's why you're seeing a reload.

If the links are anchors to content on the existing page it will scroll down the page and not reload. But looks like all of those sidebar links go to other pages. Nothing the theme can do about that.

**Comment by Andy-ABTec** [comment]
OK, thanks for your time and the explanation...
