### ISSUE TITLE
this thing work with jekyll 3 beta?

### ISSUE THREAD

**Issue by xicubed** [mmistakes/minimal-mistakes#160]

**Comment by mmistakes** [comment]
It should. I haven't tested yet though.

**Comment by mmistakes** [comment]
Just did a test and was able to get it to work with the latest Jekyll 3 beta. Just have to do some minor changes:

1. [Update Gemfile](https://github.com/mmistakes/minimal-mistakes/commit/4e27b27cfe5c649480da58413b879dd3e72bdb7a)
2. Run `bundle jekyll update`
3. Run Jekyll as you normally would. `bundle exec jekyll build` or `bundle exec jekyll s`

If you use the Jekyll Gist tag you might run into problems. I had to [remove that](https://github.com/mmistakes/minimal-mistakes/commit/9343657ba7b1651d480c4f491a5c34f57ec6a427) since it didn't seem like it's been updated for Jekyll 3 yet.

**Comment by xicubed** [comment]
Thanks!
