### ISSUE TITLE
White space at the end of a post

### ISSUE THREAD

**Issue by seyoum** [mmistakes/minimal-mistakes#1602]
- [ ] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [X] I believe this to be a bug with the theme.
- [X] I am using the latest version of the theme.
- [X] I have updated all gems with `bundle update`.
- [X] I have tested locally with `bundle exec jekyll build`.
    - Minimal Mistakes version: 4.11.1
    - Jekyll version: 3.7.3
    - GitHub Pages hosted: no
    - Operating system: Windows 10 - 1709

___ 

The theme adds a lot of vertical space after a short article. This triggers the vertical scroll bars and makes it look like there should be more content than it really is.

I believe this is a CSS problem somewhere but since this theme relies a lot on CSS framework I am not sure if I can find the source of the problem. Would be really nice to have it fixed if possible. Perhaps some skilled CSS pros here can contribute?

[Example image](https://i.imgur.com/SO6SIzk.png)

**Comment by mmistakes** [comment]
This is related to #1578, #1494, #1504, #1427

What is going on is JavaScript is determining the height of the page so it can push the footer to the absolute bottom.

Otherwise on pages with very little content the gray footer bar floats in the middle of the page.

If it bothers you, you can simple [rip out the JavaScript](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/_main.js#L5-22) that does this.
