### ISSUE TITLE
staticsman error

### ISSUE THREAD

**Issue by fedebarabas** [mmistakes/minimal-mistakes#1607]
- [x ] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.9.0
- **Jekyll version:** 
- **GitHub Pages hosted:** yes
- **Operating system:**  ubuntu 16.04

---

## Expected behavior

Posting a staticman v2 comment successfully

## Steps to reproduce the behavior

Trying to post a comment in https://fedebarabas.github.io/projects/name_similarity/ gets this error:

Cannot GET /v2/entry/fedebarabas/fedebarabas.github.io/master/comments

I've read similar issues here and as far as I can tell, my config files are ok

**Comment by mmistakes** [comment]
If you open your browser's console you'll see more info on the error.

![screen shot 2018-03-30 at 12 28 28 pm](https://user-images.githubusercontent.com/1376749/38145151-e9265346-3415-11e8-88af-527fc95f0727.png)

Usually when Staticman reports a 500 error it's because you're sending over data it doesn't like or isn't valid. I'd double check your settings are correct. If there are fields in the form that are marked required and you aren't sending data Staticman will error.

At quick glance you have recaptcha configured in `staticman.yml` but not in `_config.yml` which is probably the issue. Staticman is expecting it but you don't have it active in `_config.yml` so the fields that send over keys back to Staticman aren't present.

Also you aren't on the current version of the theme. So I'd upgrade as well.

**Comment by fedebarabas** [comment]
I added the recaptcha info in _config.yml (I thought all comment
configuration was done in staticman.yml) but the issue is still there.

This is the developer report


I would try to avoid upgrading because I have several conflicts with
upstream. But if that is the only way, I will do it

**Comment by mmistakes** [comment]
It's definitely your config settings and or not using the latest version of theme. 

Your site still doesn't allow the recaptcha box which tells me you might be using an older version of the theme.

Since you have it enabled Staticman expects it and that is failing.

Not sure what else to suggest. Update the theme and compare config settings against the demo site as Staticman works there.

If you aren't customizing the theme you should install it as a `remote_theme` as it is much easier to upgrade. You won't have to deal with merge conflicts or pulling from upstream.

https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

**Comment by mmistakes** [comment]
The YAML in your _config.yml is bad, it is very particular about spaces. You need to add a single space after the colons. That would explain why the reCaptcha widget isn't appearing in the comment box.

```yaml
reCaptcha:
  siteKey                : "6Ler208UAAAAAO-pE8g5IDEGD-i0eF6iReihVB1z"
  secret                 : "6Ler208UAAAAAFkPcx43nx-qtHgo6HXo7ozSff92"
```

Can you confirm that you've done the required steps in the docs? If you don't setup Staticman correctly with GitHub it's not going to work.

1. Allow Staticman push access to your GitHub repository by clicking on **Settings**, then the **Collaborators** tab and adding `staticmanapp` as a collaborator.

2. To accept the pending invitation visit: [`https://api.staticman.net/v2/connect/fedebarabas/fedebarabas.github.io`](https://api.staticman.net/v2/connect/fedebarabas/fedebarabas.github.io). Consult the Staticman “**[Get Started](https://staticman.net/docs/index.html)**” guide for more info.

**Comment by fedebarabas** [comment]
I fixed the space after the colons and this gave me the recaptcha dialog.

Then I upgraded to 4.11.1 version but I still get error 500

I definitely followed the config steps in the docs, including adding
staticman as collaborator

**Comment by fedebarabas** [comment]
I think I am not getting the secret correctly
If my secret is SECRET, I went to 

https://api.staticman.net/v2/encrypt/SECRET

and I pasted the result to the staticman.xml config file. Is this the way to go? 
It is weird because trying the example in https://staticman.net/docs/encryption I don't get the same result written in that page

**Comment by fedebarabas** [comment]
Ok, I fixed it. I realized the sample _config.yml in your repo has this line:

`
path: "_data/comments/{options.slug}"
`

instead of 

`
path: "/_data/comments/{options.slug}"
`

taking out the extra `/` did the trick
