### ISSUE TITLE
Locale ignored for UI generation

### ISSUE THREAD

**Issue by carbeck** [mmistakes/minimal-mistakes#1627]
## Description

The `locale` setting in my `_config.yml` seems to be ignored for generating the UI texts. They remain in English.

## Environment

- Minimal Mistakes version: 4.11.1
- Ruby gem or remote theme version: remote
- Jekyll version: 3.7.3
- Git repository URL: https://www.github.com/carbeck/carbeck.github.io
- Operating system: Ubuntu 16.04.4 LTS
- GitHub Pages hosted (if yes provide URL to site): https://carbeck.github.io

---

## Expected behavior

UI texts in German language as per setting in `_config.yml`.

## Steps to reproduce the behavior

- specify `locale: "de-DE"` in `_config.yml`
- compile with `bundle exec jekyll build` (just `jekyll build` fails: 
> /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:313:in `check_for_activated_spec!': You have already activated public_suffix 3.0.2, but your Gemfile requires public_suffix 2.0.5. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)

)

**Comment by mmistakes** [comment]
You don't have the UI text data file in your repo, that's why it's all defaulting to English.

Copy [`_data/ui-text.yml`](https://github.com/mmistakes/minimal-mistakes/blob/master/_data/ui-text.yml) to your repo and it'll work. Since you're hosting with GH and using as a remote theme you need to do this as it can't pull it from the bundled gem.

The ruby gem version doesn't have that limitation...

The Jekyll build failure has nothing to do with the theme. You'll want to poke around jekyll/jekyll or ask for help through their approved channels.
