### ISSUE TITLE
Blanking out label based keys in ui-text.yml did not remove them from UI

### ISSUE THREAD

**Issue by pateskinasy** [mmistakes/minimal-mistakes#1629]
## Description
Blanking out label based keys in ui-text.yml did not remove them from UI.

## Environment
Windows 10
https://github.com/pateskinasy/pateskinasy.github.io
Hosted on Github Pages

- Minimal Mistakes version: 4.11.1
- Ruby gem or remote theme version: 2.7.6
- Jekyll version: 3.7.3
- Git repository URL: https://github.com/pateskinasy/pateskinasy.github.io
- Operating system: Windows 10
- GitHub Pages hosted (if yes provide URL to site): www.pateskinasy.github.io

---

## Expected behavior
"Tags" and "Categories" to be removed from the UI

## Steps to reproduce the behavior
Specifically:
Tried tags_label and categories_label. I've deleted "Tags" and "Categories" from them but they didn't disappear from the UI.

**Comment by mmistakes** [comment]
Leaving `categories_label` and `tags_label` blank won't work because the theme is setting the default value to "Categories: " and "Tags: " inside of [`_includes/category-list.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/category-list.html#L17) and [`_includes/tag-list.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/tag-list.html#L17).

You can remedy this by:

1. Feed both a string with a space
    ```yaml
    tags_label: " "
    categories_label: " "
    ```
2. Remove the `default` values from category-list.html and tag-list.html... ` | default: "Tags:"` and ` | default: "Categories:"`

**Comment by pateskinasy** [comment]
Thanks Michael once again for the support. It worked.
