### ISSUE TITLE
Feed doesn't get generated

### ISSUE THREAD

**Issue by mplacona** [mmistakes/minimal-mistakes#1640]
## Environment

- Minimal Mistakes version: latest
- Ruby gem or remote theme version: gem
- Jekyll version: 3.7.3
- Git repository URL: https://github.com/mplacona/realkotlin.com
- Operating system: Ubuntu
- GitHub Pages hosted (if yes provide URL to site):

---

## Expected behavior

Seems like no matter what I do, the contents of my feed never get generated. I read #417 but the steps indicated there were not useful to me. I also saw a suggestiong to change back from `plugins` to `gems` (#1144) but that shouldn't apply to me as I am not using GH-Pages

## Steps to reproduce the behavior

Starting with `bundle exec jekyll serve`

Contents generated on feed:

```
<feed xmlns="http://www.w3.org/2005/Atom">
<generator uri="https://jekyllrb.com/" version="3.7.3">Jekyll</generator>
<link href="https://realkotlin.com/feed.xml" rel="self" type="application/atom+xml"/>
<link href="https://realkotlin.com/" rel="alternate" type="text/html"/>
<updated>2018-04-29T01:00:07+00:00</updated>
<id>https://realkotlin.com/</id>
<title type="html">Real Kotlin</title>
<subtitle>Learn the Real Kotlin online</subtitle>
<author>
<name>Marcos Placona</name>
<uri>https://www.placona.co.uk</uri>
</author>
</feed>
```

None of the posts, which live under `_tutorial` are included

Any help here super appreciated.

**Comment by mmistakes** [comment]
[Jekyll Feed](https://github.com/jekyll/jekyll-feed/blob/master/lib/jekyll-feed/feed.xml) only generates a feed for "posts". The Markdown files in your `_tutorial` folder are collection documents. That's why you're not seeing them.

You'll need to request that feature from Jekyll Feed if you want them to support collections. Or you can build your own feed for the tutorial documents, by forking their [`feed.xml`](https://github.com/jekyll/jekyll-feed/blob/master/lib/jekyll-feed/feed.xml#L34) file and changing the `site.posts` loop to be `site.tutorial` instead.

```liquid
{% assign posts = site.tutorial | where_exp: "post", "post.draft != true" %}
```

**Comment by mplacona** [comment]
Totally makes sense. I went ahead and rolled my own version [here](https://github.com/mplacona/realkotlin.com/blob/master/feed.xml) in case anyone ever finds this thread and wants to do the same.

Thank you!
