### ISSUE TITLE
Include FontAwesome for local install on server / GDPR EU issues

### ISSUE THREAD

**Issue by BenjaminJurke** [mmistakes/minimal-mistakes#1662]
## Description
As some of you probably know, on May 25th, 2018 the EU will issue a new privacy law, which severely limits the hassle-free kind of online communications. For example, embedded advertising that communicates with an external server becomes an issue (as the IP address is considered 'private information' and thus would require an explicit acknowledgment of the page visitor to share), and likewise the usage of Google Fonts and similar "common" web development elements is at least under scrutiny. This will be a major pain in the a$$ for a lot of blogs. 

Long story short: Jekyll and the Minimal Mistakes theme is extremely benevolent is this aspect. So far, the only external dependency I found is the FontAwesome package. When I look at my website at the moment, the `https://use.fontawesome.com/releases/v5.0.12/js/all.js` file is the only one that could potentially cause an issue.

Therefore, I wanted to ask (or suggest), to add an option to the `_config.yml` file like `localfonts: true`, which would then add the required css/js/ttf/woff/... files from FontAwesome to the `assets` subfolder in the compiled websites `_site` subdirectory, i.e. more or less the situation we already had before, when using FontAwesome 4.

I guess I am not the only one having to deal with this rediculous nonsense... but ultimately, this would probably be a good reason to make this 'local server fonts' feature a part of the MinimalMistakes theme.

**Comment by mmistakes** [comment]
@BenjaminJurke Have you dug up and info that specifically calls out using FontAwesome or Google Fonts from external servers you don't control i.e. CDNs?

Under scrutiny and not compliant are two different things. Not sure how compelled I am to add the extra complexity to load FA locally or via a 3rd party server. A time ago I included all of the FA files with the theme, but they were always out of sync and it became much easier to use the `.js` version.

It also gives users the flexibility to override the `_include` the theme loads that file to bump to a newer version if I haven't gotten to it. Much easier for them to change a single line than override a boatload of SCSS files and fonts if they want the latest icons.

**Comment by BenjaminJurke** [comment]
Indeed. There are now actual service providers that simply block EU countries from accessing website due to the GDPR. Just google GDPR shield, e.g. [https://www.techrepublic.com/article/to-save-thousands-on-gdpr-compliance-some-companies-are-blocking-all-eu-users/](https://www.techrepublic.com/article/to-save-thousands-on-gdpr-compliance-some-companies-are-blocking-all-eu-users/)

**Comment by BenjaminJurke** [comment]
Today I actually looked at the MM theme code basis. It is actually super-simple to embed the FontAwesome locally to the server, just as Mike Rose suggested.

1.  Download the FontAwesome package from the [FontAwesome Website](https://fontawesome.com/get-started)
2. The relevant file is `fontawesome-all.min.js` inside the `svg-with-js/js` folder of the downloaded ZIP package.
3. Move this file to a folder of your Jekyll base, e.g. I placed it into the `assets/js/fa-v5.0.12` directory, such that in the compiled version of the site the relative file URL is `assets/js/fa-v5.0.12/fontawesome-all.min.js`
4. Create a local copy of the [`_includes/scripts.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/scripts.html) file in your Jekyll base directory.
5. Inside this file (currently in line 12) you find the line   
`<script src="https://use.fontawesome.com/releases/v5.0.12/js/all.js"></script>`  
which loads the FontAwesome SVG/JS script from the default FontAwesome CDN server. Replace this line by  
`<script src="{{ '/assets/js/fa-v5.0.12/fontawesome-all.min.js' | relative_url }}"></script>`  
or some other path that you used for the local script file.
6. Recompile / build your Jekyll website. All done.

Still, it would be (Font)Awesome 😉 if this process would be automated by default in the theme, but it is not much trouble to follow up on manually.

**Comment by mmistakes** [comment]
I'll look into ways of possibly easing the pain for locally hosting FontAwesome in the theme.

In the past I manually included all the FontAwesome CSS and fonts with the theme so they could be bundled in. It just got unwieldy having to commit all those assets every time they added a new icon and I used the bump to version 5 as an excuse to offload it to CDN version.

There's probably some build step I could employ to do it or drop it in as a Git submodule to handle updates without having to actually commit the files to this repo. But not sure if that's worth the trouble.

Curious to see how other theme developers handle this. I know this theme isn't alone, pretty much every theme out there that uses externally hosted copies of jQuery, Google Fonts, FA, and many other scripts will get bit.

Perhaps they just punt on the issue as they're user base is smaller and can get away with it...

**Comment by mmistakes** [comment]
I didn't even consider WordPress and its ecosystem. So many plugins and themes offload to CDNs to load 3rd party scripts and styles, they're in for a fun time...

I'm with you, seriously doubt its going to be enforced. But does sort of stink for those who want to do the right thing.

**Comment by Sciss** [comment]
There is a lot of FUD and misinformation traveling through the net right now. GDPR is protecting citizens by a few basic mechanism, such as "opt-in-by-default" (instead of opt-out) and minimising unnecessary data production. The truth is, many plugins and libraries do unnecessarily process data. For example, many website do not effectively function if you disable js or cookies, even if they should based on their contents. There is a lot of good reasoning behind GDPR.

It is simply not true that WordPress becomes "illegal". You can audit the plugins your site is using, e.g. the cookies produced, and for the data produced, whether it allows an instance (third party or not) to create a personal data trail. In those cases, you would need to install a plugin that obtains consent of website visitors first, i.e. before creating those particular cookies. I have gone through the WP site of my partner a few days ago, and the major problem where the "social media sharing" buttons. They are _known_ to be very problematic in terms of privacy. There are other ways to provide the same functionality without proactively creating data trails that allow Google, Facebook, and Twitter to track you across different sites. After removing the particular plugin, the only remaining issue was Google Fonts. It is also not true that Google Fonts are "illegal" as such, because there are no court cases yet that would determine that, so if people caution against Google Fonts, it is because they could be interpreted within the GDPR as producing personal data trails. I would take this as an opportunity to review how much unnecessary data is actually gathered by fairly simple websites.
