### ISSUE TITLE
disqus comment problem.

### ISSUE THREAD

**Issue by cortix** [mmistakes/minimal-mistakes#1698]
## Environment

- Minimal Mistakes version: 4.11.12
- Ruby gem or remote theme version: ruby 2.4.4p296 (2018-03-28 revision 63013)
- Jekyll version: 3.8.2
- Git repository URL: https://github.com/cortix/hsnclkk
- Operating system: windows 7 home basic
- GitHub Pages hosted (if yes provide URL to site): yes but forward it a domain.

---

## Steps to reproduce the behavior

Hi, I read many issues about this comment problem. I can not run the disqus on both my github-pages server and my local server. Can you help me to figure the problem out. 

Best regards.

**Comment by mmistakes** [comment]
Doesn't look like there's anything wrong with the theme as Disqus is loading.

![screen shot 2018-06-03 at 9 38 13 am](https://user-images.githubusercontent.com/1376749/40887140-ec21e068-6711-11e8-8e0b-5d025e70b62e.png)

Your issue is likely something with a configuration on the Disqus site, or the shortname is incorrect. Or maybe something is up with their service currently as I'm seeing these sorts of errors in the browser's console tab... which are related to their Disqus JavaScript file.

![screen shot 2018-06-03 at 9 40 59 am](https://user-images.githubusercontent.com/1376749/40887174-6105a23e-6712-11e8-8cf7-ccd97f7cef2d.png)

I'd widen your search to Stackoverflow and look for Disqus errors. This isn't a Jekyll or theme issue.

**Comment by cortix** [comment]
Thank you so much @mmistakes I understand my problem now. I have confused the username of my disqus with the shortname of the site.
