### ISSUE TITLE
Add Slideshare link

### ISSUE THREAD

**Issue by sobkowiak** [mmistakes/minimal-mistakes#173]
It would be nice if we could configure the Slideshare id in `_config` and it would generate a link to Slideshare like Github,  Twitter, e.t.c.

**Comment by YNedderhoff** [comment]
I tried to do that by adding

```html
{% if author.slideshare %}<a href="http://de.slideshare.net/{{ author.slideshare }}" class="author-social" target="_blank"><i class="fa fa-fw fa-slideshare"></i> Slideshare</a>{% endif %}
```

to _ _includes/_author-bio.html_. Basically, this works with every icon available with FontAwesome. But in the slideshare case, the icon unfortunately didn't appear. Ideas why?

**Comment by mmistakes** [comment]
@YNedderhoff Theme is probably using an older version Font Awesome without the Slideshare glyph. You'll need to update to get it to show up.

**Comment by YNedderhoff** [comment]
I did, doesn't change anything. Just found out it's the same for the last.fm glyph ...

**Comment by Amorymeltzer** [comment]
@YNedderhoff You sure?  Both [slideshare](https://github.com/FortAwesome/Font-Awesome/issues/1176#issuecomment-53092778) and [last.fm](https://github.com/FortAwesome/Font-Awesome/issues/719#issuecomment-53365208) appear to have been added to font-awesome in v4.2.

I raised #178 on this issue.

**Comment by mmistakes** [comment]
I just pushed an update that includes Font Awesome 4.4
Like @Amorymeltzer said pretty sure Last.fm has been in Font Awesome for a few versions now. No idea if Slideshare was a 4.4 addition or not.

But either way both icons work just fine for me. If you're having problems getting them to show then check your markup and compare against Font Awesome's documentation because there's clearly something wrong with your setup.

![screen shot 2015-09-06 at 9 01 57 pm](https://cloud.githubusercontent.com/assets/1376749/9707590/ef8f291e-54da-11e5-8f83-2b931db72cd9.png)

**Comment by mmistakes** [comment]
Closed because I don't feel it's necessary for me to add every social network and site under the sun into the sidebar. It's easy enough to customize the theme for your own needs using the common ones I've added as an equal.
