### ISSUE TITLE
Comments with staticman and minimal-mistakes theme not working.

### ISSUE THREAD

**Issue by gitorko** [mmistakes/minimal-mistakes#1750]
https://github.com/gitorko/gitorko.github.io

Hi Michael,

I have configured github pages with remote_theme, but cant get staticman comments section to show up. 

The api seems to be working when i invoke it directly as i can see entries in '_data/comments/', not sure what i am missing.

https://api.staticman.net/v2/entry/GITUSER/GIT_REPO/master/comments?fields[name]='test1'&fields[email]='a@a.com'&fields[message]='test'&options[slug]='slug'

**Comment by mmistakes** [comment]
You're missing configs. In addition to staticman.yml there are several variables that need to be set in `_config.yml` as well.

You're missing `comments.provider` and some other Staticman fields. Have a look the demo site's config to compare again and figure out what you're missing. A lot these under `staticman` are for v1 and if you're using `staticman.yml` they're configured there instead. But `branch` and any reCaptcha stuff needs to be in `_config.yml`.

But you're not even seeing the form, which is due to not setting a `provider`.

https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_config.yml

```
comments:
  provider               : "staticman_v2"
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : # "New comment"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "_data/comments/{options.slug}"
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:
  siteKey                : 
secret                   : 
```

**Comment by gitorko** [comment]
I finally have it working. It took some time for the form to show up, its not immediate so might lead someone to think that it didnt work.
layout: splash also seems to cause the comments form to not show up. layout: single works.
Which layout should i be using for wide screen layout with comments working?

**Comment by mmistakes** [comment]
Comments were designed to only work with `layout: single`. If you want a wide variant of that add `classes: wide` to the front matter as well.

See this [demo post](https://mmistakes.github.io/minimal-mistakes/markup-text-readability-wide-page/) for an example.
