### ISSUE TITLE
blog comments not working

### ISSUE THREAD

**Issue by nadaa** [mmistakes/minimal-mistakes#1763]
I am trying to add comments to my blog here: nadaa.github.io
I added the required configuration to config.yml & staticman.yml

The first error was about reCaptcha though I generated ReCaptcha and added the keys to both config and statisman.
After disabling the captcha in staticman.yml file, still the message can't be sent, and the console shows this error 

> 
> {success: false, rawError: {…}, errorCode: "GITHUB_WRITING_FILE"}
> responseText
> :
> "{"success":false,"rawError":{"code":404,"status":"Not Found","message":"{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/repos/contents/#update-a-file\"}"},"errorCode":"GITHUB_WRITING_FILE"}"
> 

Can you please help to resolve this?

Thanks

**Comment by mmistakes** [comment]
Don't think your issue is related to the theme or configuring Staticman.

You sure you properly autheticated Staticman with GitHub? From that error it looks like it's having issues writing the data file to your repo.

See Step 1 on the [Staticman docs](https://staticman.net/docs/).

Other than this I don't really have any other advice. Maybe file an issue on Staticman's repo. They might be able to clarify that error since it appears to be originating from Staticman.

**Comment by mmistakes** [comment]
Possibly related https://github.com/eduardoboucas/staticman/issues/202

**Comment by nadaa** [comment]
Thanks @mmistakes , your suggestions really helped. I didn't have any error now, however, the comments doesn't appear, it says wait for approval, and I don't know how to approve the comments!?

**Comment by mmistakes** [comment]
Your repo on GitHub. Check the pull requests. You need to merge them in to approve comments.

**Comment by nadaa** [comment]
Nothing to merge, I set the moderation to false in the staticman.yml!.
