### ISSUE TITLE
inlineDisqussions

### ISSUE THREAD

**Issue by damageboy** [mmistakes/minimal-mistakes#1776]
## Description

This is partly a question / suggestion:
I really like the commenting experience provided by [inlineDisqussions](https://tsi.github.io/inlineDisqussions/) and I was wondering if there is a way to integrate that with minimal mistakes?

Is this something I'm supposed to do on my own? Or is this the sort of thing that a project like minimal-mistakes normally take upon themselves?

Sorry if I sound lost, it's only because I really am... :)

**Comment by mmistakes** [comment]
Depends. If it's something I think adds value and doesn't complicate or clutter the theme I'd consider it.

At first blush I'm thinking it's something best left as a customization you do. But feel free to change my mind ;-)

Since it's a jQuery plugin you should be able to [modify the theme's JavaScript](https://mmistakes.github.io/minimal-mistakes/docs/javascript/) to bundle it in.

**Comment by damageboy** [comment]
Thanks for answering so quickly.
I'll close for now and try to give it a go :)
