### ISSUE TITLE
latest 3 post instead features

### ISSUE THREAD

**Issue by ghiboz** [mmistakes/minimal-mistakes#1804]
## Description

Hello again!

I have another question:
should be possible add the latest 3 post excerpt in the `feature_row` instead the 'static' 3 features?

thanks 😄

**Comment by mmistakes** [comment]
You'll need to hack the theme to do that. Have a look at these pages to see how it's currently built.

- https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/home.html#L9-L11
- https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/archive-single.html

If you use [feature_row](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/feature_row#L1-L5) instead of archive-single.html inside of the `for` loop, with some clever uses of [include parameters](https://jekyllrb.com/docs/includes/#passing-parameters-to-includes) and `assign`, you can probably getting it working.

**Comment by ghiboz** [comment]
thanks @mmistakes !!
some things begins to work!! thanks
