### ISSUE TITLE
scrollable sticky toc (enhancement request )

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [mmistakes/minimal-mistakes#1851]
In reference to **closed issue** on this repo - [Link](https://github.com/mmistakes/minimal-mistakes/issues/1840)

The asked person had made a custom fix.

However If I may request for this feature in the theme,  because having lengthy table of contents overflowed from the page and are not reachable.

@mmistakes  - _**Would you like to introduce it?**_

**Comment by mmistakes** [comment]
Don't know if this could be done gracefully. The right sidebar is a huge hack right now because it supports Markdown auto TOCs and a Liquid helper that creates the TOC.

The placement of the HTML is more flexible with the Liquid helper method, but styling it in a way to not break Kramdown TOCs is challenging.

I prefer the pattern of not sticking the TOC and having it scroll with the content. For documentation heavy sites the left nav sidebar is a better place for adding waypoints.

I'm willing to bet most people ignore the sidebar anyways. There's likely few people who are going to be bouncing around multiple headings on a single page.

**Comment by Kulbhushan-Chand** [comment]
You had me convinced about the added visual clutter because of table of contents. Personally I too give less attention to them. However this may be a dormant feature in the theme. Also the bug in the current `toc `implementation (see the last paragraph of this comment).

My main motive was to get your attention to this closed issue - [**link1**](https://github.com/mmistakes/minimal-mistakes/issues/1840)
where the person had implimented the same on this page - [**link2**](https://wei2624.github.io/MachineLearning/sv_discriminative_model/)

You can see in link 2, he have implemented the scrollable toc. Check this [commit ](https://github.com/Wei2624/Wei2624.github.io/commit/8c8ee0c118c7984f42759b7605da344d859ffbfe)
and the following consecutive commits you can decipher the css changes made by him.

Again I would say that the present system of `toc `in the theme have **problem**  displaying large number of headings in the post. 
**### To see the problem** - You can try to add a lot of headings in the post and in yaml add `toc_sticky: true`. _In this case the table of content will overflow from the page and the last enteries on the list of toc will not be accessible._

**Comment by mmistakes** [comment]
Link2 is super buggy for me. There's all sorts of screen flashes and inconsistencies with how the page scrolls, don't think that's a particularly good solution.

As far as right sidebars that get cutoff. This is one of the reasons I was hesitant to add a sticky behavior. If your body content is shorter than the height of the table of contents, it's going to extend beyond the viewport.

Either turn off the stickiness or [limit what headlines](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/toc.html#L18-L19) are used to make it shorter.

**Comment by Kulbhushan-Chand** [comment]
Thanks for the pointer to limit headlines.
