### ISSUE TITLE
Yet another grid layout question 

### ISSUE THREAD

**Issue by ansiblejunky** [mmistakes/minimal-mistakes#1877]
I went through various existing issues regarding the grid layout on the homepage. After this and doing some research on my own, I honestly am not able to get it working. Yes, I can create a grid layout and define the various variables in the front matter that hold information like `image_path` and stuff, but this is hardcoded information on the homepage. I don't want that. I want dynamic information. I want to list the most recent articles in a grid layout format instead of the list format.  The problem I find is that your grid layout and `feature_row` and stuff all require `image_path` and stuff.  However, the `site.posts` returns a list of posts and each has `post.header.feature` as the `image_path`, so I was trying to assign that or pass that value as the `image_path` but nothing is working. 

Here is what I have in the `index.html`.
```
---
title: "Ansible Junky"
layout: splash
header:
  overlay_color: "#000"
  overlay_filter: "0.5"
  overlay_image: /assets/images/20080219-Strasbourg-France-7264.jpg
excerpt: "Website devoted to my opinions on photography and technology."
---
{% for post in site.posts limit: 5 %}
  {% include feature_row image_path=post.header.teaser type="left" %}
{% endfor %}
```

This doesn't work at all and I have not found a solution. Your help would be much appreciated. 

Also, how is the `splash` layout different from the `collections` layout and using `entries_layout: grid`? I saw that also in your messages. Not sure how it differs.

Of course I still want the website to have the bit at the bottom for pagination.

**Comment by ansiblejunky** [comment]
Ok, I found some helpful information from [this issue](https://github.com/mmistakes/minimal-mistakes/issues/1251). However, the pagination is gone now from the home page.

**Comment by mmistakes** [comment]
I don't have much to add that I haven't already said numerous times before.
To start, stay away from the feature row include. That's used for purely static content that you don't mean to loop through (unless you want to hack it up to support that).

Instead use [`/_includes/archive-single.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/archive-single.html)

It has a `type` parameter that you can pass to output either a `list` view or `grid` view (the default is `list`). If you start digging into the various archive layouts I provide you'll see I start a `for` loop and then include `archive-single.html`... which is similar to the HTML you pasted above.

Not sure what your issue is with pagination, but if I had to guess it's related to the `for` loop you're using. Jekyll has `site.posts` which holds all the post data. Then there is `site.paginator` which is used by jekyll-paginate.

You probably changed `{% for post in site.paginator %}` to `{% for post in site.posts %}` and that killed your pagination.

**Comment by ansiblejunky** [comment]
Ok, so now I tried the code you suggested:
```
<div class="grid__wrapper">
  {% for post in site.paginator %}
    {% include archive-single.html type="grid" %}
  {% endfor %}
</div>
```
And with the `site.paginator` my home page is totally empty. Doesn't seem to work at all.

**Comment by mmistakes** [comment]
:man_shrugging: 

Have a search through the closed issues. Pagination issues come up often enough there should be some gold in there. It's almost a configuration problem or misunderstanding on how [Jekyll's pagination](https://jekyllrb.com/docs/pagination/) needs to be setup. Hint... it's extremely picky.

**Comment by mmistakes** [comment]
Try `paginator.posts` instead of `site.paginator`. Autocorrect spat out the wrong thing in my previous comment.
