### ISSUE TITLE
Right sidebar overlaps main text in Chrome 70 and Safari but works fine in Firefox

### ISSUE THREAD

**Issue by Wei2624** [mmistakes/minimal-mistakes#1941]
Hi @mmistakes 

Thanks for the great theme. 

I have removed padding-right in archive.css. It now looks like:

```
.archive {
  margin-top: 1em;
  margin-bottom: 2em;

  @include breakpoint($large) {
    float: right;
    width: calc(100% - #{$right-sidebar-width-narrow});
/*    padding-right: $right-sidebar-width-narrow;*/
  }

  @include breakpoint($x-large) {
    width: calc(100% - #{$right-sidebar-width});
/*    padding-right: $right-sidebar-width;*/
  }
} 
```

What I want is that I plan to remove the padding area between the right sidebar and the border so that the main text can have more space. It works well in Firefox but does not work in Chrome 70 and Safari. It will overlap the main text. 

![image](https://user-images.githubusercontent.com/6278809/48380466-d7d73e00-e6a5-11e8-81e5-bec88f276aba.png)

You can also check if that is the case on your side by the [link](https://wei2624.github.io/MachineLearning/sv_discriminative_model/). 

Have you ever got this issue? And any idea to fix it?

Thanks for your time.

**Comment by Wei2624** [comment]
@mmistakes I think my question is that given that I set `width: calc(100% - #{$right-sidebar-width-narrow})`, why does it still overlap?

**Comment by mmistakes** [comment]
It overlaps because `.page__content` is too wide. You need padding on the right of that to leave room for the right sidebar.

![image](https://user-images.githubusercontent.com/1376749/48417646-40afcc00-e721-11e8-82cd-c1be59b2473d.png)

![image](https://user-images.githubusercontent.com/1376749/48417659-486f7080-e721-11e8-9993-9b551d3e3504.png)

**Comment by Wei2624** [comment]
@mmistakes Thanks for the reply. I see your point. 

However, the thing that confuses me is that it works well on my computer where I use `63.0 (64-bit)` firefox on Ubuntu. The screen resolution is 1920x1080. The performance is like

![mm](https://user-images.githubusercontent.com/6278809/48424306-61335280-e730-11e8-969b-428b764cf87d.png)

Is that possibly because of the screen resolution or the browser?

Thanks

**Comment by mmistakes** [comment]
Has nothing to do with the browser. I'm on Firefox too. It's 100% the width of the viewport.
You likely have the styles in media queries. You need to approach this from a mobile first mentality.

Shrink the width screen to phone size, and as you widen it check to see when things overlap. At that breakpoint you need to set the padding.

If you look at the code I already have you'll see I'm changing things as the width increases using breakpoint mixins like `@include breakpoint($medium) { }`, `@include breakpoint($large) { }`, `@include breakpoint($x-large) { }`, etc.

I think you were just lucky with a wide browser window, because when I increase it things don't overlay. You just get a huge amount of space to the left.

![image](https://user-images.githubusercontent.com/1376749/48424666-1108c000-e731-11e8-829f-acaeee29bb3d.png)

I'd suggest reading up on responsive web design or taking some online courses. I don't have the bandwidth to spend time debugging every layout issue you have. All of this is standard HTML/CSS development get help with over on forums like Stackoverflow or pay someone to fix.

**Comment by Wei2624** [comment]
@mmistakes Thanks for your points and patience.
