### ISSUE TITLE
Cannot get the posts by tag section with tags and their counts to show?

### ISSUE THREAD

**Issue by cwerner** [mmistakes/minimal-mistakes#1951]
Hi and thanks for your great theme.

I'm struggling to get the section of your example to display:
https://mmistakes.github.io/minimal-mistakes/tags/

I do get my sections of posts by tag as a link list, but I cannot see the top section of your example with the tags listed plus their counts.

Do I need to have a Jekyll plugin installed for this to work? I host on gh-pages...

What I want:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/13906519/48671239-6e33b580-eb25-11e8-9be1-6df001214d9c.png">

What I have:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/13906519/48671250-84417600-eb25-11e8-88a9-ba3f32b66d38.png">

My site is here: 
https://github.com/cwerner/chrwerner.github.io

I'm not quite sure if I messed up your theme on the way as I must admit that I don't really know what I'm doing here...

Thanks!

**Comment by mmistakes** [comment]
You're not using the correct layout. Instead of `layout: archive` your want [`layout: tags`](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#layout-tags)

If you're still in doubt, check the [source for the demo site's tag page](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_pages/tag-archive.md).

**Comment by cwerner** [comment]
Dough!

Sorry for the rookie (m)mistake and thanks for the quick help.
