### ISSUE TITLE
GitHub Pages: Valid remote theme not recognized: Minimal Mistakes

### ISSUE THREAD

**Issue by edgriebel** [mmistakes/minimal-mistakes#1992]
# Description
I'm having a problem using minimal mistakes as a remote theme. When deploying to GitHub pages, the error email says "The minimal-mistakes theme is not currently supported." but the theme is #1 on the list of remote themes [1] so I don't understand why I'm getting this error message.

# Environment
* Minimal Mistakes version: master and 4.14.1
* Ruby gem or remote theme version: 2.7.6
* Jekyll version: 3.7.4
* Git repository URL: https://github.com/edgriebel/edgriebel.github.io
* Operating system: Linux/GitHub
* GitHub Pages hosted (if yes provide URL to site): http://edgriebel.com

# Expected behavior
Push to GitHub repo should rebuild and deploy jekyll site with new mmistakes theme

# Steps to reproduce the behavior
Instead, when I push to GitHub I get an error email 
>The page build failed for the `master` branch with the following error:
>
> The minimal-mistakes theme is not currently supported on GitHub Pages. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.

I believe I have tried "everything" to get this working but it still doesn't work. Note that this runs fine locally for me on Linux (e.g. "bundle install; bundle exec jekyll serve"). I'm moving this from an existing GitHub theme if that makes a difference too.

# What I've tried
I've followed the recommendations in the theme's quickstart [2], and also in GitHub's page to use a remote theme [3]. I've tried a number of things to fix this problem including stripping out all but essential gems from Gemfile and ensuring the url: matches my url, and trying the remote_theme: with and without fixing the version listed in the theme's quickstart. My Gemfile is here[4] and _config.yml is here[5].

I've looked at #1685 and #1339 and I don't think they apply.

I'm not asking to debug my _config.yml file (like, "Why does my text have a brown background?"), if it does look like that's the problem then I apologize in advance.

[1] https://github.com/topics/jekyll-theme
[2] https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/
[3] https://blog.github.com/2017-11-29-use-any-theme-with-github-pages/
[4] https://github.com/edgriebel/edgriebel.github.io/blob/master/Gemfile
[5] https://github.com/edgriebel/edgriebel.github.io/blob/master/_config.yml

**Comment by mmistakes** [comment]
Everything looks correct to me. The only reason GitHub Pages would give you that error about MM not being supported is if you had it declared under `theme:` in your _config.yml (which you do not), or if you included the MM theme gem in `Gemfile` (which you also are not doing).

I do see you've commented those lines out though. Is it possible you received that error before and since correcting it things are fine? Nothing else is jumping out to me as being incorrect in your setup.

**Comment by mmistakes** [comment]
For comparison this is the [`_config.yml`](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_config.yml) and [`Gemfile`](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/Gemfile) I'm using for the demo site that is hosted on GitHub Pages using MM as a `remote_theme`.

**Comment by edgriebel** [comment]
I've taken a look at these, they were very helpful when I was porting to
the new theme.

I've had the `theme:` and Gem commented out a while ago, I'll do a push
again to force a redeploy just to make sure.

Thanks,
-ed

**Comment by edgriebel** [comment]
Pushed it and got the same error, is the next step GitHub support or is there something else you can think of?

**Comment by True-Demon** [comment]
Just dropping this in here to mention that I am also now experiencing this issue. My theme is currently falling back to my previous theme after upgrading to minimal mistakes. Github-Pages shows that it no longer supports "mmistakes/minimal-mistakes" in the commit history, which does not make sense because I can build it locally just fine. I can also see several example sites which import minimal mistakes with a near-identical _config.yml file as myself that are having no trouble using the remote theme. I suspect this is a github pages issue, but it's uncertain at this point. My site is at https://github.com/true-demon/truedemon.github.io for reference

**Comment by edgriebel** [comment]
FYI my issue is still outstanding. Haven't received many suggestions from GH support. I think I may have to just copy (_config.yml)[https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_config.yml] and then make customize it, testing each customization in case something breaks it.

**Comment by mmistakes** [comment]
@edgriebel I’d take a close look at your _config.yml file. You might have some bad YAML that is tripping up GH pages during the build. For example you have [`repository` listed twice](
https://github.com/edgriebel/edgriebel.github.io/blob/master/_config.yml#L84). That shouldn’t matter but who knows.

That and all the `theme` configs you have commented out might be confusing something.

**Comment by ashmaroli** [comment]
@edgriebel Have you tried pulling in the theme's `master` branch instead?
```yaml
remote_theme: mmistakes/minimal-mistakes
```

**Comment by samba** [comment]
I seem to have run into this too. A few related discoveries, but referring to other themes:

1. [Someone tried to reproduce the problem with a minimal site.](https://github.com/iBug/gh-pages-test)
2. [Possibly it's related to the `github` entry in `_config.yml`](https://github.com/benbalter/jekyll-remote-theme/issues/32)

**Comment by mmistakes** [comment]
Looks like the presence of a `github` key in _config.yml is the culprit. Explains why the MM docs site and some of my [remote theme test](
https://github.com/mmistakes/mm-remote-theme-test) repos work fine... neither have `github:` entries.

As a test @edgriebel, I’d try removing [these lines](
https://github.com/edgriebel/edgriebel.github.io/blob/master/_config.yml#L76-L77). If it builds on GH-Pages then the bug seems legit and upstream related to either the github-pages gem or jekyll-remote-theme.

**Comment by edgriebel** [comment]
That was it! Thanks so much for the help, it works now!
