### ISSUE TITLE
Creating a Gallery returns a Liquid Syntax error

### ISSUE THREAD

**Issue by NahuatlC137** [mmistakes/minimal-mistakes#2011]
I've placed the gallery front matter per [minimal mistakes documentation](https://mmistakes.github.io/minimal-mistakes/docs/helpers/). I then drop into the body of the post using `{% include gallery %}`.

When I `bundle exec jekyll serve`, I get the following error:

Liquid Exception: Liquid syntax error (C:/**dir**/_includes/gallery line 2): Syntax Error in 'assign' - Valid syntax: assign [var] = [source] included in C:/**dir**/_real_estate/2018-12-30-V2-lessons-learned.md

jekyll 3.7.4 \| Error:  Liquid syntax error (C:/**dir**/_includes/gallery line 2): Syntax Error in ' assign' - Valid syntax: assign [var] = [source] included

**front matter**
![image](https://user-images.githubusercontent.com/29752787/50553595-b0e5c300-0c77-11e9-8de5-0473967baa37.png)

**inserting to body of post**
![image](https://user-images.githubusercontent.com/29752787/50553601-ec808d00-0c77-11e9-8ca5-c20de00f762c.png)

I have a feeling that I'm supposed to include `{% include gallery %}` elsewhere, but I'm not sure where.

**Comment by mmistakes** [comment]
You have a public GitHub repo demonstrating this? From the YAML above everything looks correct. Something else is likely the culprit but I'd need your source code to try and reproduce it.

**Comment by NahuatlC137** [comment]
Hi,
I've pushed the changes from my local repo to master.

https://github.com/NahuatlC137/PracticalTechStudios/blob/master/_real_estate/2018-12-30-V2-lessons-learned.md

**Comment by mmistakes** [comment]
I see your problem. For some reason when you forked the theme you also changed the `gallery` include code, which broke it.

Remove your `_includes/gallery` and replace with the [latest theme's](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/gallery). Then it will work.

Also I'd suggest not forking the theme, and instead use it as a [`remote_theme`](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#remote-theme-method). You can then remove all the theme files (`_layouts`, `_includes`, `_sass`, `assets/css`, `assets/js`, etc.) since it doesn't look like you're customizing anything. This will make sure you always have the latest version without having to manually pull over files and potentially break something.
