### ISSUE TITLE
Allow user to toggle between themes [light/dark]

### ISSUE THREAD

**Issue by rajesh-s** [mmistakes/minimal-mistakes#2033]
## Summary
I'm new to Front-end development. I was wondering if it would be possible to allow the user to toggle between themes/css properties using the same color configurations specified using minimal_mistakes_skin: "default"

## Motivation

* In the recent times a lot of people prefer a darker background at night that's easier on the eyes
* At the same time, it's a know fact that using light font on a dark background ALWAYS reduces readability of the site. 
* I came across site like https://fdp.io/# that allow switching between themes using css properties
* I was wondering if there is a way to allow the user to switch between the colour themes

**Comment by jhabdas** [comment]
Like this? https://codepen.io/sashatran/pen/rPaLgG

**Comment by hello-w0r1d** [comment]
Yes that's right. Another example of it is the following Hugo theme https://academic-demo.netlify.com

**Comment by astrob0t** [comment]
This is how i _(a noob)_ achieved/reverse-engineered it in Minimal-Mistakes
* the Sass mixins were a tad bit confusing to me. So I extracted the css files by running the theme locally in default and dark mode. i saved them as `main.css` and `dark.css`
* pulled up kdiff3 and compared the key differences
* set up [CSS variables](https://www.w3schools.com/css/css3_variables.asp) for the differences
* started substituting the CSS colors in the `main.css` with the variables.
* added a `light` class to the `<body>` tag
* toggled that class on click of a button using javascript.

you can see it in action here _(shameless plug)_ - [my dev site](https://astrob0t.com)
There are a few other decorations on the site which are not directly from the dark theme but the above is the gist.

I am sure Michael will come up with a better solution than that of the above monstrosity. Eagerly waiting as this issue has been marked with the `Enhancement` label.

**Comment by mmistakes** [comment]
Not exactly sure how I'd handle this without bloating the theme with a bunch of extra CSS.
The way the stylesheet sheet works now is at build it injects "skin" dependent Sass variables to give everything the correct colors.

Which means the dark skin's styling isn't available to the "light" or vice/versa. Does bundling in all the skins in a stylesheet really the best thing for those who don't care about a light/dark toggle? I dunno...

There's also the issue of the theme not having a canonical "light" skin anymore. There are essentially 9 different color palettes someone can choose... and they don't all compliment each other. Which means probably designing 8 or so more color schemes to invert them.

Personally I've never much cared for sites that add this sort of thing. I'd rather see it happen at the system or browser level. There are browser extensions that do just this which might have better results vs. me trying to maintain consistency across 10 color palettes x modes (20 palettes if you're counting at home).

**Comment by jhabdas** [comment]
@mmistakes see https://inclusive-components.design/a-theme-switcher/

**Comment by jhabdas** [comment]
That said I see this as a passing fad. Everyone scrambling to add a light/dark mode to their themes when the OS + browser should be responsible for this behavior.

**Comment by astrob0t** [comment]
OS + browser can go all dark mode on their browser menu but they can only go as far as just applying a dark contrast mode on the website content, which may lead to the website visuals getting all messed up. So it is actually upto the website developer to manage/feature their own dark mode.

**Comment by jhabdas** [comment]
I agree it's up to the site to control how it looks, but feel the toggle needs to be elsewhere which it seems like macOS is moving wards with Mojave as illustrated by @paulmillr here: https://paulmillr.com/posts/using-dark-mode-in-css/

**Comment by jaketae** [comment]
I know this issue has been marked as closed, but I was wondering if we could continue this discussion as per @rcarmo's suggestion. I'm aware that there is no canonical light or dark theme, but it would be great if some form of customization functionality could be added with a toggling option, e.g. allow users to enable a toggle with two themes specified in `_config.yml`?

**Comment by Gioele-Bencivenga** [comment]
I'd also very much like to be able to achieve this.
Since my website is supposed to have both showcase pages and posts I'd like for users to be able to switch to the light theme when reading.

**Comment by hardianlawi** [comment]
@astrob0t Hi, I'm a noobie in web dev here. Do you mind sharing your solution in more details?

**Comment by khanfarhan10** [comment]
Sorry for not viewing this thread earlier,
@mmistakes my approach was a bit different : since you already have 10 different themes, would it be too difficult to add the toggle switch that switches between any 2 (or all :)) of them? A simple change in the css files would maybe do the trick as separately generated with the two different themes as suggested by @astrob0t ? Like if theme is dark use a dark.css and if theme is light use a light.css?

I'm a noob to jekyll and web dev so apologies if this is not easy at all. Great theme Michael. Will love it always!

Here is my original **ISSUE** :



### Summary
Wouldn't it be great to add a two theme switching button feature to the website:   
A button that would change the theme right away and would be available on all pages on the top navigation menu, possibly close to the search button on top?

Maybe include something in the theme configuration file as :
- Light_Dark_Button : true/ false
- Light_Theme : aqua
- Dark_Theme : neon



### Motivation
I thought of looking at some articles and found these : 
- https://medium.com/@derekkedziora/how-to-add-a-dark-mode-toggle-to-a-jekyll-site-a76dac00128d
- https://laptrinhx.com/how-to-add-a-dark-mode-toggle-to-a-jekyll-site-2605890340/

However, these documents don't cover the themes that minimal mistakes uses, aka : 

| aqua | neon | plum | dirt | mint | sunrise | air | contrast | dark |



### Drawbacks
None that I know of , except that it may cause the one navigation menu item to maybe go to the sidebar with three horizontal bars?
