### ISSUE TITLE
Make staticman_v3 default Staticman comment provider

### ISSUE THREAD

**Issue by cloudwheels** [mmistakes/minimal-mistakes#2036]
## Summary

This is a skeleton issue based on #2034

The backend service for staticman v2 has become overwhelmed. Users are able to set up their own backend, but the developers have created a github application which resolves the issue and avoids the need to create this custom backend.

In effect, whilst the v2 api will continue to run, v3 offers a much smoother and more stable implementation and should be the default going forward.

This should involve small changes to _config.yml, the  bundled staticman.yml, _includes/comments.html and related documentation + testing.

My current use case for minimal-mistakes is helping me to pass my exams in horticulture: they're a few weeks time. eek. It's a nice little PR I'd be happy to take on, but I'm very good at letting coding be a distraction to learning the actual plant stuff, so if this is accepted and anyone else is keen before mid-February, please do carry on 👍

**Comment by cloudwheels** [comment]
https://github.com/mmistakes/minimal-mistakes/issues/2034#issuecomment-455852851

**Comment by mmistakes** [comment]
Nested comments are not supported in any of my themes.
Have a look on my personal site and repo to see how I’ve done it.

If you’re starting fresh it’s much easier since you can use an internal Staticman field to assign a unique identifier for each comment as a way of referencing their parent. When I implemented it on my personal site I imported hundreds from Disqus which didn’t left me with comments without UIDs.

If you search around there are others who have improved on my implementation. I don’t have the links handy but they exist.

**Comment by cloudwheels** [comment]
Thanks again for the quick response!

**Comment by deadlydog** [comment]
I think this issue was closed without addressing the original ask, which was to introduce a `staticman_v3` config option and make it the default. I get that you don't offer nested comments in this theme (which would be awesome and amazing if you did), but that's a separate issue than simply introducing staticman v3 support. Could we maybe get this issue reopened to introduce staticman v3 support?

**Comment by mmistakes** [comment]
@deadlydog Staticman 3 is supported. See the docs on how to configure it.

https://mmistakes.github.io/minimal-mistakes/docs/configuration/#staticman-v3

**Comment by deadlydog** [comment]
Ahhh perfect. I hadn't found that link; that looks like exactly what I need. Thanks for the super fast responses @mmistakes . You can really tell you are passionate about your projects, and I appreciate it :)
