### ISSUE TITLE
Replace featured image with leaflet map

### ISSUE THREAD

**Issue by dylanjlennon** [mmistakes/minimal-mistakes#204]
Hi,
Thank you very much for providing the template for this theme. I am just getting my feet wet right now. I am wondering: is it possible to use leaflet maps in place of the featured image? For example, by passing an .html file to the image: option?
Thank you for your time,
Dylan

**Comment by mmistakes** [comment]
That's possible but you will have to customize the theme to do it. There's a ton of ways to do it but if you like the convention I used for the feature images you could do something similar. I'm not familiar with leaflet maps so not sure what the html looks like, but here's something to get you started...

In the YAML Front Matter of your post/page add `map: foo.html` (replace foo.html with whatever the filename is) and place `foo.html` in your `_includes` folder.

Then add something like the following to the `post.html` and `page.html` `_layouts` where you want the maps to appear... perhaps above/below the feature image?

``` html
{% if page.map %}  
    {% include {{page.map}} %}
{% endif %}
```

That will inject whatever html files you placed in `_includes` and reference referenced with `map: `. If you need further help I'd suggest asking on the [Jekyll Talk forums](https://talk.jekyllrb.com/) since this is more of a Jekyll question than anything related to the theme.

**Comment by dylanjlennon** [comment]
I only suggested html because I am using a leaflet package in R (via
Rstudio) and using R markdown to write some pages. RStudio can also write
html so I was thinking of rendering the leaflet into an html page using
Rstudio, and then using your convention. Probably a very roundabout way of
doing things, but I have only just begun my foray into coding, js, and
Jekyll.  Lots to learn.

Anyways, I will definitely think about things more and seek help at the
Jekyll forumn when appropriate. Thank you for your help and suggestions.

**Comment by mmistakes** [comment]
This method is probably the easiest unless you want to write a Jekyll plugin or come up with a sleeker solution. Nothing wrong with generating a bunch of includes that you call in as you need them. Worth asking on Jekyll Talk though, there's people way smarter than me that might have a better solution.

**Comment by dylanjlennon** [comment]
Just following up even though this is closed:

http://dylanjlennon.github.io/dylans-first-post/

I got it working. Any ideas as to what attributes contribute to the white
space at both ends of the header?

**Comment by mmistakes** [comment]
There's some CSS applied to it that as far as I can tell is inlined as part of the HTML bit you included. You can use the browsers web developer tools to inspect elements on the page and it will tell you exactly what styles are being applied and where.

I'm seeing this on the wrapper

``` css
.container-fluid {
    padding-right: 15px; /* remove or set this to 0 */
    padding-left: 15px; /* remove or set this to 0 */
    margin-right: auto;
    margin-left: auto;
}
```
