### ISSUE TITLE
switching to remote theme kills navigation and search

### ISSUE THREAD

**Issue by Ryukhin** [mmistakes/minimal-mistakes#2046]
I am battling several issues that seem to be around publishing the site on GitHub Enterprise that their support team seems to think is an issue with using the remote theme. When I switch to the remote theme in the config my navigation and search stop working. I have fallen down the Ruby dependency hole of nightmares, I have run out of ideas and am now only making things worse. 

I have made a copy to my private account - https://github.com/Ryukhin/docs.test to see if you can see where I went south. Any ideas or help would more than I can say.

This repo contains the same files but the TOC and Nav work here https://github.com/Ryukhin/docs.accounts 

TIA
/heather

**Comment by mmistakes** [comment]
Couple of things.

**1.** I wasn't able to build your docs.test repo locally until I modified your `Gemfile`. It was looking for the jekyll-include-cache gem which you were missing. Try this:

```ruby
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem "jemoji"
  gem "jekyll-include-cache"
end
```

Then run `bundle install`. After doing this your site built for me and the navs appear.

**2.** Search doesn't give any results, though this is likely due to you not having any posts. The way you've setup `_docs` should be as a [collection](https://jekyllrb.com/docs/collections/), but that doesn't seem to be the case so that could account for them being excluded from the search index as well. The search index file loops over all collection documents only. So if they are pages their content won't be included.

**3.** You have some theme specific files left in the repo that could be confusing GitHub Pages. Remove `minimal-mistakes-jekyll.gemspec` as you don't need that.

**4.** You should gitignore `_site` as pushing that may also be confusing GitHub Pages. It generates this folder for you and you shouldn't include it as what you are currently pushing has `localhost` paths. You can gitignore `.sass-cache` as well.

**5.** Your docs.accounts repo is using the MM theme as a gem, which isn't supported by GitHub Pages. It'll build locally but if you're trying to have GH build your page it's not going to work. 

I'd start with all of these suggestions. I've never used GitHub Enterprise but there is this issue currently that may or may not be related.

https://github.com/benbalter/jekyll-remote-theme/issues/43

**Comment by mmistakes** [comment]
Your docs.accounts repo has the `_docs` collection [correctly setup](https://github.com/Ryukhin/docs.accounts/blob/master/_config.yml#L206-L209). This is why search works there and not in the other repo.

**Comment by Ryukhin** [comment]
THANK YOU! You are a genius. I am going to fork this over to my Enterprise repo and see what happens. According to GH support, it should work using the remote theme and now it totally works! I am a lone writer out here and getting the second set of eyes is so helpful, cannot thank you enough. Well, aside from supporting you - which I will do on next payday - again, thank you.

**Comment by mrmanc** [comment]
> I'd start with all of these suggestions. I've never used GitHub Enterprise but there is this issue currently that may or may not be related.
> 
> [benbalter/jekyll-remote-theme#43](https://github.com/benbalter/jekyll-remote-theme/issues/43)

That issue isn’t related—it’s about hosting the theme on Enterprise rather than hosting the site using the theme on Enterprise (which works great). Just commenting as I spotted the reference from that issue.

**Comment by chtitoon** [comment]
@mrmanc Should I reopen my issue then?

**Comment by mrmanc** [comment]
> @mrmanc Should I reopen my issue then?

Not sure to be honest—depends on what the etiquette is when an issue is closed for being stale. Probably worth discussing over [there](benbalter/jekyll-remote-theme#43) though. :)
