### ISSUE TITLE
Make the theme more suitable for Netlify CMS

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#2047]
## Summary

I have started implementing Netflify CMS on some of my sites. Would you be interested in a pull request that implies minor changes to the theme (like moving some of the settings to data files) to make it more suitable for implementing the Netlify CMS and making it possible to have a smooth CMS backend to the theme?

## Drawbacks

People needs to make minor adjustments when updating.

**Comment by lsolesen** [comment]
@mmistakes Netlify CMS is pretty configurable, but as I understand it, it needs the settings that you want to edit together in the same file. You can see an example here, where I moved a couple of the settings from _config.yml to _data-files, and then it is possible to be able to edit those settings by enabling Netlify CMS fairly easy.

I totally understand if you are reluctant to make breaking changes, and maybe you do not even think it is clever :) Netlify CMS still works even if the site is hosted at Github.

**Comment by mmistakes** [comment]
Do you really need to remove the _config.yml settings you're moving to `_data/settings.yml`? Couldn't you just copy them to `settings.yml`? That means duplication, but I don't see any harm with that. The same thing happens if you use `staticman.yml` for comments...

There's a lot of theme logic that looks for these variables under `site.` namespace too. Changing all of these out would be a lot of work since it would be changing `site.variableName` to `site.data.settings.variableName`.

And that opens up similar issues the theme has with `ui-text.yml` data file, that isn't copied with the theme gem and can have missing text strings because of that. Unless you specifically add `default` filter values to every variable (which I've done for the UI text, but is kind of unwieldly).

**Comment by lsolesen** [comment]
@mmistakes They can be left in _config.yml and then the values from _config.yml can be used as default values in the theme. Off course it will be a lot of work to switch from site.variableName to site.data.settings.variableName and that is the reason I am asking whether you would even be interested in a pull request to support this :)

**Comment by mmistakes** [comment]
For the reasons cited above I think this would cause me way too many headaches.

There have been issues raised over on jekyll/jekyll related to data files and themes that would help clean some of this up. If and when those land would be a good time to reevaluate. Right now this would add extra complexity to the theme I'm not comfortable with.
