### ISSUE TITLE
how to change tab size in code tag ( ``` tag at .md)

### ISSUE THREAD

**Issue by joyoon729** [mmistakes/minimal-mistakes#2065]
hi.
when I use ``` tag in markdown to syntax highlighting,
the tab size is always 4.
I want to change tab size to any other size.

ex)
<_posts/2019-2-21-post1.md>

-------------------------------------------------------

example code ...
```md
```js
function foo(){
(*tab*)return 0;
}
```
-------------------------------------------------------

and it represents my page with tab size 4...

how to modify tab size?

**Comment by mmistakes** [comment]
The example code above doesn't have any indents at all and shows like this. Not exactly sure I follow what your issue is, but it sounds more like a Markdown thing than anything related to the theme.

![image](https://user-images.githubusercontent.com/1376749/53171781-aed21d80-35b1-11e9-9d51-8064b12fd839.png)

Whatever indents (e.g. how many spaces you have) is respected by Kramdown/Rouge when it applies the syntax highlighting. It doesn't rewrite tabs to be 2 or 4 spaces to my knowledge. Which is what I think you're asking.

**Comment by joyoon729** [comment]
thanks!
