### ISSUE TITLE
Staticman comments are added, but don't appear

### ISSUE THREAD

**Issue by imnotender** [mmistakes/minimal-mistakes#2074]
Hi,
After a little while messing around, I managed to make, for the most part, staticman's v3 comment system work. I can submit a comment at any post I make where it's enabled, and staticman adds the PR to the repo, and after I merge it, it appears in _data/comments/postslug.
The problem is, after it's done building, it doesn't appear on that post. It only gets through <div class="js-comments"> and everything that's supposed to be inside it isn't showing up, so I know from that that it doesn't go through the {% if site.data.comments[page.slug] %} condition. I think I've tried everything I can think of by now. I'm using forestry.io so it's automatically set to production,no errors building, and my repo is at https://github.com/imnotender/blog.ender.pt .

**Comment by mmistakes** [comment]
I think your issue is how you're naming your `_posts`. You are using spaces instead of hyphens e.g. `2019-03-03-first blog post.md`

This is creating comments in a folder `_data/first blog post`. The problem with that is the comment logic is looking to match comments with the `page.url` which is `first-blog-post` (with hypens). This is why none of your posts are showing the comments you have `_data` files for.

Rename your post filenames to follow Jekyll's convention of `YYYY-MM-DD-your-filename.md`, submit a new comment, and verify it's going in a folder like `_data/your-filename`.

I renamed your posts, renamed the `_data` folders, removed the `slug` front matter, and comments showed up locally for me.

**Comment by imnotender** [comment]
Damn, made a new post following the convention and comments are working there, can't believe it was something that simple. Thank you so much!
