### ISSUE TITLE
Twitter cards not working 

### ISSUE THREAD

**Issue by quintus-sertorius-blue** [mmistakes/minimal-mistakes#2084]
## Environment
I am using the latest version of Minimal Mistakes and Jekyll

My repository is here https://github.com/quintus-sertorius-blue/BlueSertorius 

## Expected behavior

Twitter cards seem not to work properly. When I copypaste this link http://quintusertorius.com/mentalpollution/# into the twitter card validator https://cards-dev.twitter.com/validator it shows me a gray image, even though I have an overlay image.

I tried to change image and also to put an og_image under the header section but it didn't work.

Thank you for your  help

**Comment by mmistakes** [comment]
I think you have the wrong path to your `og_image`. If you look at the source of that page it has this path:

```
https://quintus-sertorius-blue.github.io/_images/biblio.jpg
```

Which isn't valid. That's why Twitter is showing a gray image. Closing as this isn't a theme issue but a content issue on your end.

FYI - Jekyll ignores `_underscore` folders by default. Looks like you have two lines of `includes` in your [_config.yml](https://github.com/quintus-sertorius-blue/BlueSertorius/blob/gh-pages/_config.yml#L41-L42) Which could part of your problem too. It should be an array instead:

```
include: [ "_pages", "_images" ]
```

**Comment by quintus-sertorius-blue** [comment]
thank you for your help
the path for the `og_image` is this one `og_image: /images/biblio.jpg` as I wrote in the source of that page
also in the config.yml the path for the the `og_image` is the same  `og_image: /images/biblio.jpg`

Am I doing something wrong? I renamed the folder `_images` in `images` and the `include`
 is now `include: [ "_pages", "images" ]`
