### ISSUE TITLE
Can't get the OpenGraph/FB feature image to change

### ISSUE THREAD

**Issue by pricelessbrewing** [mmistakes/minimal-mistakes#213]
It just keeps wanting to use the author image file as the preview image instead of the feature: image tag. I'm probably using the wrong header tag or something stupid, but let me know if you figure it out please.

Post in question, https://github.com/pricelessbrewing/pricelessbrewing.github.io/blob/master/_posts/Calc/2016-1-05-Mash-Calculator-Update.md

**Comment by mmistakes** [comment]
Looks like the feature image isn't loading on the page which is why FB isn't picking it up. Likely cause is leaving `url: ` in your `_config.yml` blank. Set it to `url: http://pricelessbrewing.github.io` and the image should show up when you push to GitHub. This will give you an absolute path vs. the relative one you're using now.

![screen shot 2016-01-05 at 11 03 46 pm](https://cloud.githubusercontent.com/assets/1376749/12134801/07265c48-b401-11e5-8e88-1437238eaa5e.png)

Once the image shows up on the post you may need to force Facebook to rescrape the page to pull in the right image. You can do that using the [Open Graph debugger](https://developers.facebook.com/tools/debug/og/object/) tool.

**Comment by pricelessbrewing** [comment]
Awesome thanks. I imagine the url: was also why the link in the top right referred back to the current page instead of the homepage?

As an aside about how github works, I usually edit the files directly so when I have to push an update to an existing page. Is there a way to manually push an update, or does it do so automatically?

**Comment by mmistakes** [comment]
Yes that's exactly why that link didn't work. With `url: ` that anchor ends up being empty as well and obviously points nowhere then.

Not exactly sure on the GH side of things. As far as I know editing the files commits them to the repo which should update the site. I've only ever done updates through local commits that I push up to GH.

**Comment by pricelessbrewing** [comment]
Gotcha. Thanks again, any ideas on the open graph error?

Inferred Property The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.

Looks like it might need a new meta tag for the og:image? Also the Twitter card is 

<meta name="twitter:image" content="http://pricelessbrewing.github.io/images/https://pricelessbrewing.github.io/images/logo.png">

 <meta property="og:image"              content="image url" /> is missing all together which is probably the problem.

**Comment by mmistakes** [comment]
Your YAML Front Matter for that post needs to be changed. Go back to how you had it originally

```
image:
  feature: logo.png
```

Having the full path in there how you have it now is screwing up the OG tag. Take a look at the meta tag in the source and you'll see what I mean.

``` html
<meta name="twitter:image" content="http://pricelessbrewing.github.io/images/https://pricelessbrewing.github.io/images/logo.png">
```

**Comment by pricelessbrewing** [comment]
Thanks again, I swapped that back. Also this is all pointless since I didn't bother to check your _includes/_open-graph.html for an update. You did so a couple months ago, and added support for page/post specific og:image 's. Should be good I hope now.
