### ISSUE TITLE
Theme works. But not in locally. 

### ISSUE THREAD

**Issue by niklasjang** [mmistakes/minimal-mistakes#2136]
#### Work well in general.
I forked your repo and customized somewhat.
I can post on my blog and some features are work very well.
![image](https://user-images.githubusercontent.com/44601388/56824253-e64e9600-6890-11e9-82e1-be54f04b0aee.png)

#### But not in local.
But when I my blog on local, theme is not working.

>bundle exec jekyll serve

this commend is work. But when I open localhost:4000...

![image](https://user-images.githubusercontent.com/44601388/56824197-c0c18c80-6890-11e9-9bbd-46e0fe9553fc.png)

I think it is not duplicated question. Almost everyone is in reverse situation of mine.

_pages:
![image](https://user-images.githubusercontent.com/44601388/56824338-2ca3f500-6891-11e9-9213-fcdb87f52775.png)

my Gemfile:

>source "https://rubygems.org"
>gem "minimal-mistakes-jekyll"
>gem "jekyll", "~> 3.6.2"
>gem "rake", "~> 12.3.0"
>group :jekyll_plugins do
>gem "jekyll-feed"
>gem "jekyll-seo-tag"
>gem "jekyll-sitemap"
>gem "jekyll-paginate"
>gem "jekyll-algolia"
>gem 'jemoji'
>gem "tzinfo"
>gem "tzinfo-data"
>gem "jekyll-include-cache"
>gem "jekyll-archives"
>end

**Comment by mmistakes** [comment]
I would strongly discourage anyone from forking the Minimal Mistakes theme repo. Aside the fact that it's difficult to manage updates, it also requires many config edits.

There are folders, files, configurations, `Gemfile` contents, and more that are setup in a way that are only applicable to the theme gem and developing it. This is why I encourage installing the theme using the `remote_theme` method and [forking this starter](https://github.com/mmistakes/mm-github-pages-starter) instead.

It has the bare minimum of configuration and sample posts to get you started quickly. Give that a try instead.

The reason I think you're having issues is your `Gemfile` isn't correct. Most of it doesn't apply when you're hosting with GitHub Pages because they don't allow a lot of the 3rd party gems you're trying to install. The biggest difference is `gem "jekyll"` is replaced with `gem "github-pages"` which loads a specific version of Jekyll (and approved plugins).

One of it's dependencies loads a bunch of metadata directly from your repo and uses that to populate `url` and `baseurl` configs in your _config.yml automatically. This is likely why your site works on GitHub Pages, but is broken locally... the path to your CSS file is wrong so you get a site without a stylesheet.

Using the `github-pages` gem will mimic the environment of your hosted site which should either work or point out any issues.

This is a long way of me saying, don't fork the theme repo, but instead use the starter instead since that has a GitHub Pages `Gemfile` ready to go.
