### ISSUE TITLE
How to append an off-canvas sidebar elegantly?

### ISSUE THREAD

**Issue by Harrypotterrrr** [mmistakes/minimal-mistakes#2155]
## Summary

Thanks for providing such a beautiful theme!
I wonder how to make an off-canvas sidebar elegantly, e.g. append a button to control the visibility of sidebar like [Pisces  of hexo-next theme](https://github.com/theme-next/hexo-theme-next)

## Motivation

In some cases, such as for browsers to read technical posts more conveniently, I think it is a good idea to have a choice to close the sidebar which contains the avatar, related information and links.

## Drawbacks

It is possible to make the website redundant.

**Comment by Harrypotterrrr** [comment]
I am not familiar with the font-end knowledge, so if my proposal is denied, could you give me some advice on how to solve it in `Jekyll way`, such as offering me relative blogs or website for self-learning? 
I have checked this [site](https://www.w3schools.com/howto/howto_js_off-canvas.asp). It works with `JS` but it may not be useful in `{{% include sidebar.html %}}` this way..
Thanks for your help!😊

**Comment by mmistakes** [comment]
I'm afraid there really isn't an elegant way to do this easily. Unless you're comfortable writing HTML/CSS/JavaScript, you're going to have a hard time replacing the current priority+ dropdown navigation with an off canvas one.

If that's you're intention I'd suggest using a theme that is designed that way instead of trying to hack it onto my theme.

**Comment by Harrypotterrrr** [comment]
Thanks for you reply! If I have enough time, I will check other jekyll-theme and try to learn how to append this feature on your theme.
