### ISSUE TITLE
Staticman no longer allows comments

### ISSUE THREAD

**Issue by justinrummel** [mmistakes/minimal-mistakes#2170]
## Environment

- Minimal Mistakes version: 4.16.3
- Ruby gem or remote theme version: n/a
- Jekyll version: n/a
- Git repository URL: [justinrummel/jr.com-mm](https://github.com/justinrummel/jr.com-mm)
- GitHub Pages hosted (if yes provide URL to site): No
- Operating system: n/a

## Expected behavior

Currently not able to post comments.

## Steps to reproduce the behavior

It appears that Staticman is enforcing CORS, and current MM sites that use Staticman can no longer post comments.  Confirmed this is also impacting your own site. 

![](https://d2rsw2kbemic8w.cloudfront.net/items/0W3n2H0V2w0R1d2Y061Z/Image%202019-05-26%20at%207.16.44%20PM.png?X-CloudApp-Visitor-Id=205743)

**Comment by mmistakes** [comment]
Have you filed an issue on Staticman's repo to track?

**Comment by justinrummel** [comment]
Working on the research now, posting mostly for awareness....

**Comment by mmistakes** [comment]
Curious to see what changed on Staticman's end of anything. Looking at the repo `dev` branch was last updated 4 months ago and `master` 2 months.

Wonder if where they host changed something? Guess this is another reason to host your own instance vs. using the public Staticman endpoint.

**Comment by justinrummel** [comment]
Confirmed solution at [github.com/eduardoboucas/staticman/issues/278#issuecomment-475170669](https://github.com/eduardoboucas/staticman/issues/278#issuecomment-475170669).  Need to update from dev.staticman.net to api.staticman.net for v3. 

I've tried to figure out how to host my own instance several times and failed every single time.  If you figure it out and document, I'd be happy to verify the directions.

**Comment by mmistakes** [comment]
Nice. Was wondering when the dev instance would stop working. 

Thanks for digging into it.

**Comment by justinrummel** [comment]
Wonder if this line needs to be updated for v3

https://github.com/mmistakes/minimal-mistakes/blob/102924ff940d5b7f03493bb70aedcbad2d99286f/_includes/comments.html#L38

**Comment by mmistakes** [comment]
Shouldn't need to change. The endpoint for v3 is set in the config. Just need to switch from `dev` to `api` there.

**Comment by mmistakes** [comment]
@justinrummel Not sure if you experienced this one yet, but the dreaded "Too many requests" error is happening again once switching to `api.staticman.net` v3 instead of using `dev.staticman.net`.

Looks like even with using a GitHub application there's still some sort of API limit Staticman is hitting and comments don't go through.

There's this issue if you want to track any developments https://github.com/eduardoboucas/staticman/issues/279

**Comment by deadlydog** [comment]
Curious if you're going to make staticman v3 a first-class citizen or not? Right now in the `_config.yml` it only calls out staticman and staticman_v2:
```
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
```

**Comment by deadlydog** [comment]
I just found issue #2036 and left a comment on it to see if we could get it reopened regarding adding staticman v3 support.

**Comment by mmistakes** [comment]
@deadlydog I don't have any plans to change how Staticman is enabled in the theme. With all it's issues the last year I'm not really motivated to until it stabilizes.

Even the new v3 GitHub application endpoint is having it's issues. Calling it out as an official comment solution for the theme has only brought more attention to it and put me in a support role for when it goes bad.

**Comment by deadlydog** [comment]
Having [the link](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#staticman-v3) you provided in #2036 does effectively show how to use staticman v3 with minimal configuration changes, and is just what I was looking for 👍

**Comment by VincentTam** [comment]
> @deadlydog I don't have any plans to change how Staticman is enabled in the theme. With all it's issues the last year I'm not really motivated to until it stabilizes.
> 
> Even the new v3 GitHub application endpoint is having it's issues. Calling it out as an official comment solution for the theme has only brought more attention to it and put me in a support role for when it goes bad.

Under Staticman v3, no matter how the Node.JS code inside the app changes, I don't think the URL scheme (i.e. input) and the rendered output YML file structure would change.  Provided that this theme's integration works well with a self-hosted Staticman v3 instance, nothing much can be done by a static blog theme, apart from offering advices in documentations/README.

Btw, I suggest using an alternative/self-hosted Staticman API instance to avoid unexpected interruption of static comments service due to unnotified update on the main public production/testing Staticman API instance, say in https://github.com/eduardoboucas/staticman/issues/283.  You might refer to [my post for self-hosting Staticman](https://vincenttam.gitlab.io/post/2018-09-16-staticman-powered-gitlab-pages/2/) if interested.

P.S. I wrote the linked docs for Staticman v3, and I built @staticmanlab.

**Comment by andreigi** [comment]
> @deadlydog I don't have any plans to change how Staticman is enabled in the theme. With all it's issues the last year I'm not really motivated to until it stabilizes.
> 
> Even the new v3 GitHub application endpoint is having it's issues. Calling it out as an official comment solution for the theme has only brought more attention to it and put me in a support role for when it goes bad.

Glad to know I read this before using Staticman on my own site.

**Comment by justinrummel** [comment]
Thanks @VincentTam 

I'll take a look at your blog post again and try to follow the directions.  If there are spots that I feel are unclear I'll reach out to you.

**Comment by mmistakes** [comment]
Seems like the best approach these days is to fork  the Staticman repo and spin up your own instance on a free Heroku plan.

Closing as there’s nothing the theme can do about improving the reliability of the public endpoint.

**Comment by VincentTam** [comment]
> Seems like the best approach these days is to fork the Staticman repo and spin up your own instance on a free Heroku plan.

Staticman's maintainer has recommended users to set up their own API instance: https://github.com/eduardoboucas/staticman/issues/317#issuecomment-565250060
