### ISSUE TITLE
Display site.description in masthead

### ISSUE THREAD

**Issue by jdeluyck** [mmistakes/minimal-mistakes#2173]
## Summary

Allow printing of the subtitle / description of the site below the site title

## Motivation

It's just a nice featue that I believe more sites can use. It's like a subnote under your main title, giving you the ability to add an 'afterthought'.

## Drawbacks

Can't really think of one.

## Code:

I added to main.css:
````
$type-size-9: 0.350em !default; // ~4px

/* Site Subtitle */
.site-subtitle {
  font-size: $type-size-9;
}
````

to masthead
````
        <a class="site-title" href="{{ '/' | relative_url }}">{{ site.masthead_title | default: site.title }}
        <div class="site-subtitle">{{ site.description }}</div></a>
````

and I guess this could be made optional - for my own use I've just included it as is.

**Comment by iBug** [comment]
Good idea. But what about submitting a PR for this?

**Comment by jdeluyck** [comment]
Sure :) I wasn't sure if you'd be interested.

**Comment by mmistakes** [comment]
@jdeluyck If it's quick to do a PR I'll take a look, but no promises I'll merge it in. I'm trying to reduce the amount optional stuff since the theme is getting really bloated with these sorts of things.

They're easy enough to do custom `_includes` that override the bundled theme's if you wish to customize.
