### ISSUE TITLE
Displaying sidebar on category pages

### ISSUE THREAD

**Issue by jdeluyck** [mmistakes/minimal-mistakes#2174]
I've been trying to add a sidebar to all my pages on my (to be published) blog, but I'm having a hard time doing this to the individual category pages.

The category list page (/categories) works, just not the individual /categories/<category> ones.

Could you point me in the right direction?

Source is at https://github.com/jdeluyck/kcoreorg-website

**Comment by mmistakes** [comment]
The [Jekyll Archives plugin](https://github.com/jekyll/jekyll-archives) is generating the individual category and tag pages. You'll need to define front matter defaults for those since there are no "pages" per say for you to add them to like you have for the [`/categories/` index](https://github.com/jdeluyck/kcoreorg-website/blob/master/_pages/category-archive.md).

I'd weigh in on the jekyll-archives issue tracker. Seems like there is already [an issue related to this](https://github.com/jekyll/jekyll-archives/issues/107) not working.
