### ISSUE TITLE
my disqus shows same comments to all pages

### ISSUE THREAD

**Issue by DevKiHyun** [mmistakes/minimal-mistakes#2218]
Hi.

My disqus shows same comments to all posts.
I couldn't find solution how to solve this bug.

For example, I show 2 link of posts. All of them show same comments.... I want to show a unique comment window for a single post.

https://devkihyun.github.io/study/Paper-Review-7-Invert-CNN-Invert-Representation/
https://devkihyun.github.io/study/Paper-Review-6-RDN-Super-Resolution/

Thank you.

**Comment by mmistakes** [comment]
Don't think this is a theme issue, rather it has to do with your post names and how Jekyll creates permalinks.

The correct format for post filenames is `YYYY-MM-DD-your-post-title.md`
If you look at your posts you're using spaces which I believe is confusing some things. The theme uses `page.url` to populate the Disqus comment box, which is how comments are associated with a given page.

![image](https://user-images.githubusercontent.com/1376749/61725474-d7676a80-ad3d-11e9-88cb-8328f7b88547.png)

In your case the [`page.url`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/comments-providers/disqus.html#L4) (which should be unique for every page) is the same for both posts, which is why the same comments appear on all. 

```html
<script>
    var disqus_config = function () {
      this.page.url = "https://devkihyun.github.io/study/Machine-learining-and-Probability/";  // Replace PAGE_URL with your page's canonical URL variable
      this.page.identifier = "/study/Machine learining and Probability"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');
      s.src = 'https://devkihyun.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
    })();
  </script>
```

I would suggest you rename your `_posts` to match Jekyll's conventions, which should fix your issue.

For example change:
`_posts/2019-07-22-Paper Review 6 - RDN [Super Resolution].md`
to `_posts/2019-07-22-Paper-Review-6-RDN-Super Resolution.md`

**Comment by DevKiHyun** [comment]
Thank you!!! I changed all names, but problem is not solve.... 
I also found  'page.url' of all post show specific post's url. I don't know why...

**Comment by mmistakes** [comment]
I think your issue is you aren't using the latest version of the theme. Since you have it configured as a `remote_theme` you also need to remove the following folders (and files within):

- `/_includes`
- `/_layouts`
- `/_sass`
- `/docs`

I did this with a cloned version of your site and it built and Disqus comments had the correct `page.url`s. As far as I can tell at some point you might have modified one of the theme's files and broke something.
