### ISSUE TITLE
Code highlighting with ruge used in mardkown idiomatic way does not work

### ISSUE THREAD

**Issue by ddd-workshop** [mmistakes/minimal-mistakes#222]
Code highlighting using rouge in an [markdown idiomatic way](https://help.github.com/articles/creating-and-highlighting-code-blocks/) does not work

**Comment by mmistakes** [comment]
I think this is an upstream issue with either Kramdown, Jekyll, or both? Check [this thread](https://talk.jekyllrb.com/t/syntax-highlighting-on-github-pages/1898/6) for more info and solutions. Seems like if uninstall the `jekyll gem` and install `github-pages` that may fix things. I haven't had any luck getting backticks to work with syntax highlighting on any of my sites.

Personally I use the `{% highlight %}` tags since they always work.

**Comment by mmistakes** [comment]
As of version 3.0.0 1cce75a35e339e5b2d305ea521ae22202e7ebc08 GFM code highlighting is [supported by the theme](https://mmistakes.github.io/minimal-mistakes/markup-syntax-highlighting/).
