### ISSUE TITLE
Permalink works locally but not when hosted with Github Pages

### ISSUE THREAD

**Issue by vikramriyer** [mmistakes/minimal-mistakes#2249]
In the main _config.yml, I have set

```yml
permalink: /:categories/:title
```

On a particular post, I have set 
```yml
title: My Post
categories: desired_value
```

When I serve locally using *Jekyll serve*, I can see the post at
> http://localhost/desired_value/my-post

however, not able to view it when I check

> https://vikramriyer.github.io/desired_value/my-post

If I remove permalink from _config.yml, I am able to view the post at
> https://vikramriyer.github.io/my-post

Any help is highly appreciated. :)

PS: Cheers to Minimal Mistakes.

**Comment by mmistakes** [comment]
Doesn't sound like a theme issue, but rather something with your Jekyll setup or possibly GitHub Pages.

Have you [setup your locally development environment to mimic GitHub Pages](https://help.github.com/en/articles/setting-up-your-github-pages-site-locally-with-jekyll)? You should get the same results if you have. The fact that it works locally tells me it's probably a Jekyll version thing since you might be running a newer version of Jekyll than GH Pages supports.

The theme has no control over permalinks, that's purely Jekyll's domain.

**Comment by vikramriyer** [comment]
Hmm, seems sensible to me. I will check if there is anything that I might have screwed up. Thanks for pointing out.
