### ISSUE TITLE
Can't get sidebar working

### ISSUE THREAD

**Issue by yyarmoshyk** [mmistakes/minimal-mistakes#2254]
Hello,

I'm having trouble with getting sidebar to work correctly. I'm trying to replicate the posts/docs categories I have at http://tech-notes.net and followed the instructions [here](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#custom-sidebar-navigation-menu)
1. Added the test sidebar block to `_data/navigation.yml`
2. Added the following into the `_config.yml`
```
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
```

*Result:*
Nothing happens. Am I missing something?

*Expected result:*
See Test category with multiple test docs on the site homepage.

My stuff is available [here](https://github.com/yyarmoshyk/tech-notes.net)

It can be ran in docker:
```
docker run --name jekyll-run --rm -v "${PWD}/public:/myblog/public" -v "${PWD}/minimal-mistakes/docs:/myblog" -p 4000:4000 -it ruby:2.5 /bin/bash -c "cd /myblog; bundle install; bundle exec jekyll serve"
```

**Comment by mmistakes** [comment]
I don't use Docker, but looking at the files in your [`/minimal-mistakes`](https://github.com/yyarmoshyk/tech-notes.net/tree/master/minimal-mistakes) folder I believe you've edited the wrong _config.yml

The one in the root is for the files there. I'm guessing you're trying to build the content in `/minimal-mistakes/docs`, which has it's own _config.yml. This one looks untouched by you, so you'll want to migrate any changes you made [here](https://github.com/yyarmoshyk/tech-notes.net/blob/master/minimal-mistakes/_config.yml) to `minimal-mistakes/docs/_config.yml` and build your Jekyll site from that folder instead.

In fact I would trash everything in `/minimal-mistakes` and move all the files in `/docs` up a level.

**Comment by mmistakes** [comment]
You'd also be better off using [this repo as a starter](https://github.com/mmistakes/mm-github-pages-starter). I think you may be getting confused as to what folders you should be placing your content and config in because you forked the theme repo (which has a lot of extra stuff you don't need... `/docs` site, `/test` site, etc.)

**Comment by yyarmoshyk** [comment]
@mmistakes Thank you for the update. I'm pretty sure that docs folder has nothing to do with it. I've just removed it and nothing changed :) 

I think docs is this one https://github.com/mmistakes/minimal-mistakes/tree/master/docs

As for docker I'm trying to run it locally with `jekyll serve` instead of building and pushing into pages. This trick works great with my other jekyll sites.

Let me check the [mm-github-pages-starter](https://github.com/mmistakes/mm-github-pages-starter).

**Comment by mmistakes** [comment]
It does matter because of how you have your content setup along with the _config.yml file. The config file you're making edits in is in a folder that has no content... while the /docs folder has the content.

Unless you haven't pushed up everything to that repo. I can only comment on what I saw there and the structure was off which is why the settings you're trying to apply aren't taking.

**Comment by yyarmoshyk** [comment]
@mmistakes 

Thank you for the advise. I could get it working at mm-github-pages-starter.
