### ISSUE TITLE
Footer is blocking the contents of website. 

### ISSUE THREAD

**Issue by Anamika255** [mmistakes/minimal-mistakes#2301]
Hello, on my website, the footer is appearing a couple of inches higher, overlapping with the contents. Screenshot attached. These things were working fine before but now it is malfunctioning when I didn't even change anything. Is it because of the new releases? How can I unsync my website?
<img width="1280" alt="Screen Shot 2019-10-29 at 7 59 37 PM" src="https://user-images.githubusercontent.com/15238698/67825623-27fe0a80-fa87-11e9-8bd0-668675ae6962.png">

**Comment by mmistakes** [comment]
https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#remote-theme-method

> You may also optionally specify a branch, tag, or commit to use by appending an `@` and the Git ref (e.g., `mmistakes/minimal-mistakes@4.9.0` or `mmistakes/minimal-mistakes@bbf3cbc5fd64a3e1885f3f99eb90ba92af84063d`). This is useful when rolling back to older versions of the theme. If you don’t specify a Git ref, the latest on `master` will be used.

**Comment by mmistakes** [comment]
The footer is overlapping because CSS changed in the theme in the latest version and you are overriding all of the `_sass` files.

You’ll need to merge in those updates.

**Comment by Anamika255** [comment]
How can I unsync my website repo such that the new versions don't affect my page?

**Comment by Anamika255** [comment]
@mmistakes Also, how can I remove this blue permalink icon in front of all my headers? I used two hashtags to create a header.

**Comment by mmistakes** [comment]
Not sure. When you customized things you must have changed something to make the permalink icons always visible.

In the default version of the theme they're only visible when you hover headers.

**Comment by Anamika255** [comment]
I have copied the _sass folder and edited some things within. Should I delete that and download from yours again?

**Comment by mmistakes** [comment]
Yeah probably. Since you forked the theme you're going to run into this issue any time it updates, since you'll manually need to figure out what changed and pull those commits into your fork and/or apply any customizations you made.

The way you have it now, every file in `_includes` overrides the theme's version. Same goes for `_sass`. Ideally you'd only have `_includes` in your repo that actually override (change) something from the bundled theme.

Sass is a little trickery, because of how those assets are handled with Jekyll it's an all or nothing. I would suggest you remove `_sass`, copy `/assets/css/main.scss` and then add any CSS alterations after the `@import` lines. This is the most future proof method as you'll have less files you'll need to manage going forward.
