### ISSUE TITLE
Pages not linked properly

### ISSUE THREAD

**Issue by guillaumelobet** [mmistakes/minimal-mistakes#2315]
**When the site is generated, it does not seem to link the pages properly.** 

I followed the procedure described here https://mmistakes.github.io/minimal-mistakes/docs/pages/  to add pages. I particular:

- creating the `_pages` folder
- creating the `about.md` page ([link](https://github.com/BioGOGame/BioGOGame.github.io/blob/master/_pages/about.md))
- updating the `_config.yml` ([link](https://github.com/BioGOGame/BioGOGame.github.io/blob/master/_config.yml))
- updating the `navigation.yml` ([link](https://github.com/BioGOGame/BioGOGame.github.io/blob/master/_data/navigation.yml))

However, when I go to, for instance, to `mysite.github.io/about`, it does not find the page (error 404). I got the same error when building the site locally. 

The source code of the site is here: https://github.com/BioGOGame/BioGOGame.github.io

I have the feeling this is a dumb question, and I am missing something obvious, so any help will be appreciated...

**Comment by mmistakes** [comment]
Your `_pages` aren't being created, which is why they're 404ing.
By default Jekyll ignores folders that begin with an `_` underscore except `_layouts`, `_includes`, `_sass`, and `_posts`.

You did the correct thing by telling Jekyll to include `_pages`, but you got the path wrong... omit the trailing slash and do this instead:

```yaml
include:
  - .htaccess
  - _pages
```

Now Jekyll will see the `.md` files in your `_pages` folder... but you have some bad YAML in them which is causing them not to be converted to `.html`

![image](https://user-images.githubusercontent.com/1376749/68615315-d2672c00-0490-11ea-8c75-092913841ee9.png)

You have an extra space before the `---` in some of the files (`about.md`, `install.md`, and `use.md`)

After removing the extra line before `---` they should build:

![image](https://user-images.githubusercontent.com/1376749/68615449-14906d80-0491-11ea-99dc-4cd52447c911.png)

And finally you'll need to either update the paths in your `navigation.yml` to match these or update the `permalinks` in the .md files. Right now they're building as `filename.html` while what you want is `/filename/index.html`

For example you have this for `about.md`:

```yaml
---
permalink: /about
title: "About"
toc: true
---
```

Change it to this:

```yaml
---
permalink: /about/
title: "About"
toc: true
---
```

And the header navigation links should work correctly now.

**Comment by guillaumelobet** [comment]
Awesome, it works like a charm! Thanks a lot for looking into this and such a detailled answer!
