### ISSUE TITLE
What is the best way of adding content/text to index.html?

### ISSUE THREAD

**Issue by thephet** [mmistakes/minimal-mistakes#2337]
Hi, I am starting to use your theme, it is amazing. But I have a question, how should I add text to index.html?

So far I have added a header image, but I don't know what's the recommended way to add some text. It is a personal website, so I just wanted to write a few paragraphs about me and perhaps add some images. I don't know if I should just type it after the front matter.

**Comment by mmistakes** [comment]
Depends on what layout you’re using. Most support adding body content after the front matter. 

I’d suggest experimenting or looking at the example sites under [/docs](https://github.com/mmistakes/minimal-mistakes/tree/master/docs/_docs) or [/test](https://github.com/mmistakes/minimal-mistakes/tree/master/docs/_docs) to emulate a look you like.

**Comment by thephet** [comment]
Thank you for your answer. I think I am more confused now, /docs doesn't have an index.html file, and /test has one, but then the content under the front matter is plain html, not markdown.

**Comment by mmistakes** [comment]
The docs home page is under [docs/pages/home.md](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_pages/home.md) and is using a custom permalink to set it as the index page. You don't have to do it this way.

If you go the `index.html` route I don't think you can add Markdown to the body since it's a HTML file... you'll need to provide HTML. This is a limitation to having a paginated home page as that's how Jekyll's plugin works.

**index.html**:
```
---
layout: home
---

<p>Your content here to appear above recent post list</p>
```

If you want something more static like what I did with the doc site then there are several layouts at your disposal... like `layout: splash`.

Your best bet is to look through the examples I've provided and then dig into the source files to see how they're done.

**Comment by thephet** [comment]
Thank you very much for your answer. I have a question related (maybe very nooby question because I am new to jekyll), would it be possible in the index.html to include a markdown file with markdown text?

**Comment by mmistakes** [comment]
If you change it to `index.md`, then Jekyll will process it as Markdown.
Problem with that you won't get paginated posts on the homepage because Jekyll's pagination plugin requires it to be a `index.html` file.

https://jekyllrb.com/docs/pagination/

**Comment by thephet** [comment]
Using the html, can I use liquid to include a md file? or would that failt to produce markdown too?

Sorry for all the questions. If the answer is no, I guess I will stick with HTML

**Comment by mmistakes** [comment]
Try it out and see what happens. I'm not sure.

**Comment by mmistakes** [comment]
If Liquid works and you can include a file I don't think it will process the Markdown. It will still treat it as HTML text since that's the file extension of the file with the include.

**Comment by thephet** [comment]
Liquid does work, but using include_relative the markdown does not work :(

I will need to use plain html 

thanks for your help
