### ISSUE TITLE
Disqus comments locate at a wrong position

### ISSUE THREAD

**Issue by zjgcjy** [mmistakes/minimal-mistakes#2343]
First of all, that's a great theme of jekyll. I pretty like to share it with others. With the great help of the docs, I almost fix up all the problems. Nevertheless, when it comes to adding comments like Disqus, the position of comments is at the bottom of the page, which makes me confused.

Here is the image.

![image](https://user-images.githubusercontent.com/27962618/70716371-3ba7bc80-1d27-11ea-9903-c7c3689972c4.png)

Well, as you can see from [this link](https://zjgcjy.github.io) too.

I did not modify any source code of the theme, so when it happened, I just tried to solve the problem by reviewing what's go wrong with the configuration. But it didn't work as I am not familiar with `html` and `scss`. Please help me.

**Comment by iBug** [comment]
Yours is a great website. But I'm afraid I can't be helpful before you provide the source repository of your website so that I could have a look at what might be wrong. If you're concerned about content that you don't want to publish, you can also try creating a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to aid the issue.

**Comment by zjgcjy** [comment]
> Yours is a great website. But I'm afraid I can't be helpful before you provide the source repository of your website so that I could have a look at what might be wrong. If you're concerned about content that you don't want to publish, you can also try creating a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to aid the issue.

Of course, here are two links, [my site](https://github.com/zjgcjy/zjgcjy.github.io) and [blog source](https://github.com/zjgcjy/Blog-Asset). However, all the posts here are private and I think it has nothing with the problem except all declared with `permalink: /posts/:year-:month/:title.html` and `layout: single`. I really appreciate your help.

**Comment by iBug** [comment]
The problem looks like it's caused by you didn't set the environment variable `JEKYLL_ENV=production` as required [here](https://github.com/zjgcjy/Blog-Asset/blob/5e1025d/_layouts/single.html#L66), which led to the omission of the designated Disqus location. When Disqus didn't find the block element for it, it inserts itself at the end of the page, which finally created the strange look as you've reported.

It seems like you're building your website in your own environment instead of relying on GitHub Pages, so I would suggest that you set the desired environment variable when running Jekyll:

```shell
JEKYLL_ENV=production bundle exec jekyll build
```

**Comment by zjgcjy** [comment]
> The problem looks like it's caused by that you didn't set the environment variable `JEKYLL_ENV=production` as required [here](https://github.com/zjgcjy/Blog-Asset/blob/5e1025d/_layouts/single.html#L66), which led to the omission of the designated Disqus location. When Disqus didn't find the block element for it, it inserts itself at the end of the page, which finally created the strange look as you've reported.
> 
> It seems like you're building your website in your own environment instead of relying on GitHub Pages, so I would suggest that you set the desired environment variable when running Jekyll:
> 
> ```shell
> JEKYLL_ENV=production bundle exec jekyll build
> ```

Nice! It works, thanks a lot.

Well, I run the Jekyll before like `jekyll build JEKYLL_ENV=production` maybe it didn't work. As I am not  familiar with jekyll, i didn't know what's going wrong.

**Comment by iBug** [comment]
> Well, I run the Jekyll before like `jekyll build JEKYLL_ENV=production` maybe it didn't work. As I am not familiar with jekyll, i didn't know what's going wrong.

Not really specific to Jekyll, but shell syntax regulates that environment variables specific to a single command should be specified at the beginning of a line, not in the middle or at the end.
