### ISSUE TITLE
htmlproofer fails on 404 page

### ISSUE THREAD

**Issue by asarkar** [mmistakes/minimal-mistakes#2356]
Using MM gem-based theme hosted on Netlify. Repo: https://github.com/asarkar/non-compos-mentis, site: https://blog.asarkar.org/

Site generation is failing with the following error:

```
11:32:50 PM: Running ["LinkCheck", "ScriptCheck", "ImageCheck"] on ["public"] on *.html...
11:32:54 PM: Ran on 74 files!
11:32:54 PM: - public/404.html
11:32:54 PM:   *  linking to internal hash #main that does not exist (line 126)
11:32:54 PM:      <a href="#main" class="screen-reader-shortcut">Skip to content</a>
11:32:54 PM: htmlproofer 3.15.0 | Error:  HTML-Proofer found 1 failure!
```

Full build log: https://app.netlify.com/sites/non-compos-mentis/deploys/5e0704c1986ef10007d063e7

The 404 page in question is [here](https://github.com/asarkar/non-compos-mentis/blob/master/site/404.html). The content hasn't been changed, I just mucked with the permalink in an attempt to fix the build after seeing https://github.com/mmistakes/minimal-mistakes/issues/1263.

**Comment by mmistakes** [comment]
Looks to me HTMLproofer is failing your build, not Jekyll.

**Comment by mmistakes** [comment]
HTMLproofer is looking for an element with an id of `main`.
Just add that to your container div in your custom 404 page HTML.

```html
<div id=“main” class=“container”>
  ...
</div>
```

**Comment by mmistakes** [comment]
Also if you use `layout: single` it has the [`#main` div already](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html#L17).

**Comment by asarkar** [comment]
Thank you, using `layout: single` fixed the issue. It seems there's been a change in HTMLproofer that caused this, although I don't understand why every page must have an internal hash main.

**Comment by mmistakes** [comment]
Short answer, they don't.
It's just HTMLproofer warning you that there is a link that goes nowhere.

The theme follows the best practice of skip links that allow screen reader users to skip directly to the main content of the page. They are linking to `#main` which is baked into all of the theme's layouts.

You used `default` which isn't a fully formed layout and is meant to be chained with the other layouts. `default` doesn't have a `#main` element, which is why when you used it HTMLproofer did the correct thing and alerted you to this.

I haven't used HTMLproofer in some time, but there's probably a way to configure it to not break the build for these sorts of alerts. I seem to remember you could configure quite a number of things.
