### ISSUE TITLE
Change `Update Gemfile` in Quick-Start Guide to a bigger heading size.

### ISSUE THREAD

**Issue by leochoo** [mmistakes/minimal-mistakes#2423]
## Summary

Hi, I'm new to Jekyll. I found this fantastic Jekyll theme and I love the simplicity of it!
But I would like to make one suggestion for the documentation.

- Change `Update Gemfile` to a bigger heading size.
On `Quick-Start Guide` page, `Update Gemfile` is in a smaller size heading, which makes it look like it is a sub-step of `Migrating to Gem Version`. However, changing `_config.yml` and `Gemfile` must be done when switching to a new theme. So I would suggest to change the heading to a bigger size so that people don't miss it.

**Comment by iBug** [comment]
Looks like a strange setting with H4 of `font-size: 0.75em`. Might be better to cancel this altogether.

**Comment by mmistakes** [comment]
This is the hierarchy for headings... example below.

![Screen Shot 2020-03-05 at 6 55 41 AM](https://user-images.githubusercontent.com/1376749/75979410-7183b980-5eae-11ea-82de-39f7f2c045fb.png)

https://mmistakes.github.io/minimal-mistakes/markup/markup-html-tags-and-formatting/

`h4` could potentially be changed to `0.9em`, `h5` to `0.8em`, and `h6` to `0.75em` for a smoother transition of sizes. But there's nothing wrong with the documentation file. "Update Gemfile" is a subheading under "MIgrating to a Gem Version" which is why it was given a `h4` designation.

**Comment by iBug** [comment]
@mmistakes May I ask to change the default size so *at least* H4 is no smaller than P? This is really an issue as discussed here: <https://ux.stackexchange.com/q/126039/116810>

**Comment by mmistakes** [comment]
Headline sizes have been changed so type hierarchy is clear. `h1` > `h2` > `h3` > `h4` > `h5` > `h6` > `p`

```scss
/* headline scale */
$h-size-1: 1.563em !default; // ~25.008px
$h-size-2: 1.25em !default; // ~20px
$h-size-3: 1.125em !default; // ~18px
$h-size-4: 1.0625em !default; // ~17px
$h-size-5: 1.03125em !default; // ~16.5px
$h-size-6: 1em !default; // ~16px
```

![headlines-fixed](https://user-images.githubusercontent.com/1376749/76008983-81b38d00-5ede-11ea-9580-fe12c0e8783d.png)
