### ISSUE TITLE
Upgrade to Jekyll 3 breaking serve

### ISSUE THREAD

**Issue by wilsonmar** [mmistakes/minimal-mistakes#245]
I upgraded to the latest of everything today and got this message when I was not able to get a site by running jekyll serve:
```
Configuration file: /Users/mac/gits/jekyll/minimal-mistakes/_config.yml

  Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
jekyll 3.1.2 | Error:  jekyll-paginate
```
A solution is offered by Jonas Kersulis at http://kersulis.github.io/2015/10/31/jekyll-3/
for jekyll-paginate being deprecated:
1) In _config.yml, remove  relative_permalinks: true and   - jekyll-paginate under gems:
2) Specify alternative paginate-gist to it has been offered.
This also requires a change to the Gemfile.
3) Use of Kramdown instead of Redcarpet
4) For syntax highlighting, Pygments to Rouge

**Comment by mmistakes** [comment]
`jekyll-paginate` has been deprecated but still works fine with Jekyll 3+, it's just not getting any new features.

A good chunk of errors can be solved by just using a `Gemfile` and [Bundler](http://bundler.io/), When in doubt run `bundle exec jekyll serve` instead of the vanilla `jekyll serve`.

Bundler will force the load versions specified in `Gemfile.lock` instead of possibly running conflicting versions installed on your system. You may have to run `bundle update` first to make sure you have the correct gems installed.

**Comment by wilsonmar** [comment]
I apologize for not reading the install instructions. Almost everyone else tell people to do `jekyll serve`. And some on StackOverflow have crazy solutions. Using `bundle exec jekyll serve` works great on not only yours but other sites as well. Bravo. Closing issue.

**Comment by mmistakes** [comment]
No worries. I've had enough issues running Jekyll over the years and when I finally learned to use `bundle exec` almost all of them went away.
