### ISSUE TITLE
Is gemfile lock necessary?

### ISSUE THREAD

**Issue by eric3zhao** [mmistakes/minimal-mistakes#246]
I find "jekyll (3.1.1)" is writtern in the file Gemfile.lock.Is that means the jekyll version must be 3.1.1?I get the newest version(jekyll 3.1.2).so when I run your project,there are many errors.

```
# azi @ zhaowanzideMacBook-Pro in ~/minimal-theme on git:master x [16:49:24] 
$ jekyll serve
Could not find proper version of jekyll (3.1.1) in any of the sources
Run `bundle install` to install missing gems.

# azi @ zhaowanzideMacBook-Pro in ~/minimal-theme on git:master x [16:49:34] 
$ bundler install
Could not find rb-inotify-0.9.5 in any of the sources
```

**Comment by mmistakes** [comment]
Feel free to remove `Gemfile` and `Gemfile.lock`. Personally I would keep them and use Bundler. Running vanilla `jekyll serve` isn't necessarily the best way. 

And yes. The versions in the `.lock` file are the ones that will be used. You have to run `bundle update` to bump them to newer versions. After they install you should run Jekyll with `bundle exec jekyll serve` instead. The gem versions in the Gemfile will be loaded instead of what random ones might be installed on your system which helps to mitigate conflicts.

**Comment by eric3zhao** [comment]
I see,THX for your answer
