### ISSUE TITLE
masthead logo alt attribute

### ISSUE THREAD

**Issue by marcbompart** [mmistakes/minimal-mistakes#2529]
Can we have the masthead logo alt attribute populated with the "site.title" ?

**Comment by iBug** [comment]
Good idea. I'll take a look.

**Comment by iBug** [comment]
On line 8 of `_includes/masthead.html`, this should work:

```diff
-<a class="site-logo" href="{{ '/' | relative_url }}"><img src="{{ logo_path | relative_url }}" alt=""></a>
+<a class="site-logo" href="{{ '/' | relative_url }}"><img src="{{ logo_path | relative_url }}" alt="{{ site.masthead_title | default: site.title }}"></a>
```

**Comment by marcbompart** [comment]
commit and push! ;-)

**Comment by mmistakes** [comment]
Adding the site title as alternate text for the logo is overkill and unnecessary. Right after the logo the site title appears, so for screen readers they're going to see it twice.

Alternate text should be used to describe the image. In this case it's not adding any additional context and is simply "decoration", which is why it's omitted.

**Comment by ChristopherBull** [comment]
This remains an issue with automated accessibility tests, i.e., Lighthouse: https://web.dev/link-name/?utm_source=lighthouse&utm_medium=cli
I could add an exception to my assertions config that skip that failing test, but I can't as I need to ensure I catch other instances of this accessibility issue throughout my site.

I agree with you point about duplicate text for screen readers. Would it therefore be possible to allow us to define our own `alt` text for the Masthead logo in `_config.yml`, thus avoiding duplication of site title name? Something like "Company logo" or "Photo of xxx".
