### ISSUE TITLE
Collapsing the left sidebar, as a proper feature and not a hack

### ISSUE THREAD

**Issue by Thf772** [mmistakes/minimal-mistakes#2532]
## Summary

The left sidebar takes a lot of screen space, and application of the `.wide` CSS class does not remove it when `author_profile: false` is specified in the frontmatter, resulting in an awkward asymmetric layout.

Multiple issues have been opened regarding this problem, resulting in an endless maze of "Go see this other issue" or partial answers burried in comments and questions.

Hence, I would like to suggest the following:

- Add the official, canonical way to remove the left sidebar in the **documentation**, at least to avoid more people opening issues like this one
- Add a way to remove this sidebar with a configuration parameter, such as `sidebar: false` in order to avoid copying theme files

## Motivation

This subject is requested in multiple issues, yet no canonical solution has been offered by the dev team, or added to the documentation. At least one issue has users requesting this feature to be available as part of the theme, but this request has never been addressed by the devs. Documenting the solution would avoid more issues being opened.

The current mostly working solution is a hack that involves copying and modifying one of the theme's core files. This solution is not maintainable in the long term, especially in case this file is updated in the theme.

Finally, since there is a feature to extend the page content to the right, it is only logical that there should be a similar feature to extend the page content to the left.

**Comment by iBug** [comment]
Looks like a combination of #2453 and #2397

**Comment by mmistakes** [comment]
A lot of the difficulty with this revolves around the CSS used for layout. It's all `float` and width based, which is why things don't magically fill the empty space when a left or right sidebar is omitted.

Instead of more hacks and configs the proper solution would be to migrate the entire layout/grid to something modern like flexbox or ideally CSS grid. Flexbox probably would be the more straight forward path as the layout isn't that complicated.
