### ISSUE TITLE
Strange behaviour of header after scrolling down and up

### ISSUE THREAD

**Issue by Hax4us** [mmistakes/minimal-mistakes#2551]
## Environment

- Minimal Mistakes version: latest forked
- Ruby gem or remote theme version: 3.1.3
- Jekyll version: 3.8.7
- Git repository URL: https://GitHub.com/Hax4Us/demo
- GitHub Pages hosted (if yes provide URL to site): https://hax4us.github.io/demo/
- Operating system: Android

## Expected behavior

Categories section in header must not be hidden after scrolling 

## Steps to reproduce the behavior

I installed the theme, then just change the title __MM__ to __Hax4Us__

Here is first load of website 
![Screenshot_2020-06-04-11-16-57-683_com android chrome](https://user-images.githubusercontent.com/30441647/83720125-1355a680-a656-11ea-8660-a1b865fc3980.jpg)

Then after scrolling up & down 3-4 times 

![Screenshot_2020-06-04-11-16-52-423_com android chrome](https://user-images.githubusercontent.com/30441647/83720154-2799a380-a656-11ea-95c1-49a25c84d612.jpg)

**Comment by mmistakes** [comment]
I think this is due to the JavaScript that determines if the nav links in the header “will fit” or not and then hides the ones it “thinks” won’t.

You’ll see this on the demo site. On load a few links overflow/bump it the site title and the properly disappear once the script executes.

In your case the text is short enough it doesn’t appear to overflow, but it is a few pixels over where it hits your site title. By the time you scroll down it’s hidden the overflowing link and put it behind the hamburger menu toggle.

**Comment by mmistakes** [comment]
Related: https://github.com/lukejacksonn/GreedyNav/issues/18

Seems to only happen in mobile.

**Comment by mmistakes** [comment]
I updated to the latest version of GreedyNav.js, doesn't seem as pronounced on the demo site.
As you are using `remote_theme` you can just rebuild your site and it'll pull the latest version. Other than that don't think there is much more I can do.

There will be a few seconds where the nav elements will appear/disappear due to how JavaScript loads.
