### ISSUE TITLE
`entries_layout: grid` broken in various layouts

### ISSUE THREAD

**Issue by mmistakes** [mmistakes/minimal-mistakes#2639]
https://github.com/TarodBOFH/tarodbofh.github.io/tree/mm-bug-with-grid-layout

no `entries_layout: grid` defined on frontmatter == posts and categories broken and home list as expected
`entries_layout: grid` on frontmatter == posts and categories broken bug home is working

_Originally posted by @TarodBOFH in https://github.com/mmistakes/minimal-mistakes/pull/2616#issuecomment-668704931_

**Comment by TarodBOFH** [comment]
The problem comes with `{% assign page = post | default: page %}` on the `post__meta.html` file. That overrides current page variables with those in the post, and effectively removes any variable set at page lvl. I don't know if there is a way to combine objects on liquid.

I'm no liquid expert with that override can be dangerous. Is there a way to make it behave differently? I.e.

```
{% assign frontmatter = post | default: page %}
```

And use that local variable instead of the global one. I'd think to offer something that combines post and page in a local variable instead and make that avaliable to the includes, to avoid problems like this in the future.
