### ISSUE TITLE
Wired code snippet added to /tags view

### ISSUE THREAD

**Issue by ddd-workshop** [mmistakes/minimal-mistakes#279]
On `/tags/` view wired `<!-- Push to group_names -->` code snipped is added:
![tags](https://cloud.githubusercontent.com/assets/16007327/14677426/04443086-0712-11e6-87f8-610c00322333.png)

It's added by 26 line of `_includes/group-by-array` - I found out that reducing this comment indentation from 4 to 2 spaces removes this unwanted behavior.

**Comment by mmistakes** [comment]
Pretty sure this is a Kramdown (Markdown) issue. It's taking the indents and parsing them into code blocks. Another way to get around it is to change the page to `.html` instead of `.md`. Then Kramdown won't get confused by the indents. That's exactly what I do with the demo [tag-archive](https://github.com/mmistakes/minimal-mistakes/blob/gh-pages/_pages/tag-archive.html) page.

This obviously won't work if you have Markdown on the page that you want converted.

I'll probably just strip out the indents from the include to avoid any issues. Makes it slightly harder to read but I highly doubt anyone is going to tinker with it.
