### ISSUE TITLE
It would be nice if it works after download

### ISSUE THREAD

**Issue by wilsonmar** [mmistakes/minimal-mistakes#280]
In the previous version, it was comforting to see a nice sample site after download and running

`bundle exec jekyll serve`

I stayed with mm largely because of this because it was like being blindfolded and dropped off in a foreign country. I don't know how much time it would take me to get it working.

Now, mm joins amplify, jekyll-bootstrap, and others with this frustrating screen:

<img width="1124" alt="screen shot 2016-04-23 at 3 55 55 pm" src="https://cloud.githubusercontent.com/assets/300046/14764191/697e99a8-096c-11e6-8419-defa2a46d1be.png">

It makes me want to run away screaming.
Even though people will be changing files after cloning etc.
can you at least get us to first base here?

**Comment by mmistakes** [comment]
This was by design. I purposely removed all of the demo posts, pages, and collections because that is **content** and not part of the *theme*. You'd be surprised how many people had no clue they could (or should) remove them. For example you know how many forks kept the "Theme Setup" page? Answer. A TON!

And as you even said:

> Even though people will be changing files after cloning etc.

All the more reason to remove the demo content. Why give people an extra step if they're going to remove it anyways?

Regardless I did leave the index.html page in tact and it does get you to a base site.

It looks to me as if you're using my `gh-pages` branch which you really shouldn't be doing.

If you use `master` you'll get the normal "Recent Posts" homepage albeit with no posts. My `gh-pages` branch has `baseurl: minimal-mistakes/` set which means you have to access it at `http://localhost:4000/minimal-mistakes/` because of said `baseurl`.

**Comment by wilsonmar** [comment]
Here is my approach 

1. git clone https://github.com/mmistakes/minimal-mistakes  mymm
2. bundle the folder
3. git clone https://github.com/mmistakes/minimal-mistakes-demo
4. Copy demo files over the template:
cp -r ./minimal-mistakes-demo ./mymm
(in the future, I'll move from folder containing my files)
5. bundle exec jekyll serve

This results in this error message:

```
  Liquid Exception: The included file '/Users/mac/gits/jekyll/minimal-mistakes/_includes/feature-row' should exist and should not be a symlink in minimal-mistakes-demo/_pages/splash-page.md
jekyll 3.0.3 | Error:  The included file '/Users/mac/gits/jekyll/minimal-mistakes/_includes/feature-row' should exist and should not be a symlink

```

**Comment by johnlane** [comment]
I found the Gem-based "quick start" instructions did not result in a fully working install.  I found this issue logged when searching for information. I am just posting this as feedback and in case it helps others who may end up here with the same problems. Here are the steps which worked for me for a complete working install, albeit containing only one post:

```sh
$ gem install jekyll bundler
$ jekyll new jekyll-mm
$ cd jekyll-mm
$ sed -i -e 's/"minima".*/"minimal-mistakes-jekyll"/' Gemfile
$ bundle install
$ rm _config.yml index.md about.md
$ wget https://raw.githubusercontent.com/mmistakes/minimal-mistakes/master/_config.yml
$ echo 'theme: minimal-mistakes-jekyll' >> _config.yml
$ wget https://raw.githubusercontent.com/mmistakes/minimal-mistakes/master/index.html
$ sed -i -e 's/^layout: post/layout: single/' _posts/*welcome-to-jekyll.markdown
$ jekyll serve
```

* note espacially the neeed to add `theme: minimal-mistakes-jekyll` to the supplied `_config.yml`. Without this it does not work.
