### ISSUE TITLE
Gallery incorrect indentation under list

### ISSUE THREAD

**Issue by AkashCherukuri** [mmistakes/minimal-mistakes#3011]
## Environment

- Minimal Mistakes version: Latest
- Git repository URL: https://github.com/AkashCherukuri/AkashCherukuri.github.io
- GitHub Pages hosted (if yes provide URL to site): https://akashcherukuri.github.io/notes/soc2021/#famous-cnns
- Operating system: Windows10

## Expected behavior

The gallery should be aligned with the list, so that it looks better.

## Steps to reproduce the behavior

Below are two screenshots of the page. The first one shows the gallery not being indented properly, and the second one shows an image which is indented properly.

![image](https://user-images.githubusercontent.com/62202731/122760919-47c7ef00-d2b9-11eb-86a8-9dfaa2fcdc8a.png)
![image](https://user-images.githubusercontent.com/62202731/122760969-544c4780-d2b9-11eb-96e1-7f8f80d31fd4.png)

A minimum reproducible example:
```
---
title: "Test"
permalink: /test/
gallery:
  - image_path: /images/img1.png
  - image_path: /images/img2.png
---
Lorem Ipsum

- List heading

  {% include gallery caption="indentation" %}
```

**Comment by mmistakes** [comment]
The gallery isn't indented because it's not part of the list element... if you look at the source HTML the `figure` element is outside of it.

![Screen Shot 2021-06-21 at 8 49 20 AM](https://user-images.githubusercontent.com/1376749/122764653-b2533d80-d26d-11eb-85c0-4a998ffe11b1.png)

You might have to experiment with the Markdown you're writing. It might not respect the indent for the the `gallery` include.

Closing as this isn't a theme as it doesn't control Markdown processing... that's a Kramdown and Jekyll thing.
