### ISSUE TITLE
is there an easy way to put the Table of Contents on the left hand side?

### ISSUE THREAD

**Issue by rwillett** [mmistakes/minimal-mistakes#311]
We're trying to work out how to put the auto generated table of contents on the left hand side of the screen, where the navigation bar would go (if there was one). 

Whilst it looks OK on the right hand side of the screen it forces a re-flow of text which our designers don't like. 
![screen shot 2016-05-08 at 09 16 56](https://cloud.githubusercontent.com/assets/668923/15096721/be60542e-14fd-11e6-8fdc-7724561ec15e.png)

What they are looking for is this:

![possible_design1](https://cloud.githubusercontent.com/assets/668923/15096745/60aaf298-14fe-11e6-9c02-73e7e71e20bf.png)

This is hacked together in Affinity Photo for UX testing.

Is there a flag to move the TOC over or is this not an easy option?

Thanks

Rob

**Comment by mmistakes** [comment]
Unfortunately no if you want to continue to use [Kramdown's automatic table of contents](http://kramdown.gettalong.org/converter/html.html#toc) feature. You can only place it in the same location as the content. If you want a toc outside of that container you have to use another solution, like one of the [many Javascripts](https://www.google.com/search?q=jquery+table+of+contents&ie=UTF-8&oe=UTF-8&hl=en-us&client=safari) that can do something similar, or a Jekyll plugin.

On my personal site [Made Mistskes](https://mademistakes.com) I use jQuery to [move the toc](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/_assets/javascripts/main.js#L49) to another `<div>` so that's an option too. Or you can build the toc manually which might be harder to maintain. That's exactly what I do with the theme's demo site in the [documentation section](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/).

**Comment by rwillett** [comment]
Michael, 

Thanks. We were expecting the answer "no" :)

Your other suggestions are very useful, we'll look at them and see if we can use them. We might use Javascript to simply move the TOC over.  We weren't aware of the other plugins but we'll only look at those if we can't get the JS to work.

Thanks again for your help.

Rob
