### ISSUE TITLE
pdf-rendering?

### ISSUE THREAD

**Issue by adeldaoud** [mmistakes/minimal-mistakes#323]
I am trying to get pdf-rendering to work with your with the minimal-mistakes repository, but with no luck. After googling around it should be similar to rendering images, that is:

![caterpillar](http:/adeldaoud.github.io/SUPPLEMENTARY_DATA/my-file.pdf)

PDF-rendering is built in to Github, see here, https://help.github.com/articles/rendering-pdf-documents/

Am I missing anything which is Jekyll specific?

**Comment by mmistakes** [comment]
You probably have the path to the PDF asset wrong. The example above goes to a 404 page which tells me the PDF isn't where it should be.

```markdown
![caterpillar](http:/adeldaoud.github.io/SUPPLEMENTARY_DATA/my-file.pdf)
```

Looks like you're missing a `/` in the URL as well. Should be `http://`. Took a look in your repo and something like this should work since this file exists.

```markdown
![caterpillar](/SUPPLEMENTARY_DATA/Daoud_Kohl_2016_MPI_Topic_modeling/economic-intercept-catterpillar.pdf)
```

Also not entirely sure what you mean by pdf-rendering. If you're hoping to have the PDF embedded on the page this isn't a solution for that. With the above Markdown you're essentially linking to a file that depending on your browser will either display it or download the asset. You'll need another solution to go the embedded route.

**Comment by adeldaoud** [comment]
Thanks for the quick reply! You are certainly right about the missing “/” – a typo when I wrote the issue. Sorry about that. 

a) regarding pdf-rendering. Yes, I am trying to embed the pdf-file as is implied by this Github page: https://help.github.com/articles/rendering-pdf-documents/

Do you have a suggestion about how this can be done most easily?

b)

I tried your solution but that did not work either, strangely. I converted the pdf into a png and then it worked (as embedded image); or I had to remove the exclamation mark (but not as an embedded file, merely a link):

```
# image version (works)
![mpi caterpillar image](http://adeldaoud.github.io/images/mpi.png)

# pdf verion (does not work)
![mpi caterpillar](http://adeldaoud.github.io/images/mpi.pdf)

# pdf verion without exclamation mark (works)
[mpi caterpillar](http://adeldaoud.github.io/images/mpi.pdf)

# suggested path to the pdf (does not work)
![caterpillar](/SUPPLEMENTARY_DATA/Daoud_Kohl_2016_MPI_Topic_modeling/economic-intercept-catterpillar.pdf)

```
This is the md file where I am trying to get this working: https://github.com/adeldaoud/adeldaoud.github.io/blob/master/SUPPLEMENTARY_DATA/index.md

Many thanks for your further guidance

**Comment by mmistakes** [comment]
I think you're confusing what GitHub means by rendering PDFs. That's for the GitHub.com site as part of showing PDF's inline in your source code, issues, commits, etc. It's not part of GitHub Pages where your Jekyll hosted site lives.

To do PDF's like GitHub does you'll need to use a similar web library that displays embedded PDFs. Off the top of my head I don't know of one. But try the Jekyll Talk forums or Google. You'll get more help there.
