### ISSUE TITLE
Ruby 2.3 and nokogiri 1.6.7.2

### ISSUE THREAD

**Issue by iulitaro** [mmistakes/minimal-mistakes#328]
Hi,

I am a fresh user of the Jekyll Minimal Mistakes (and Ruby user for 2 days) and so far loving it. I want to raise a problem that I have encountered while deploying locally.

OS: Windows 8.1 x64
Ruby version 2.3
nokogiri 1.6.7.2

The problem is that nokogiri does not support the newest Ruby 2.3 and the error as seen in the screenshot appears. 

I fixed it in the following way:

- Open Gemfile.lock and change nokogiri version from 1.6.7.2 to 1.6.8.rc2 
( http://stackoverflow.com/questions/36868318/nokogiri-requires-ruby-version-2-3 )

- Deleted
      nokogiri (1.6.7.2-x64-mingw32)
      mini_portile2 (~> 2.0.0.rc2)

I am new to Ruby so not sure what would be a reasonable solution for this but maybe this fix is worth mentioning somewhere.

Iulia

![vlcsnap-2016-05-29-15h17m35s90](https://cloud.githubusercontent.com/assets/940531/15633578/b9551af0-25b0-11e6-888a-e11e930bc762.png)

**Comment by mmistakes** [comment]
Looks to me it's a depency issue with the `github-pages` gem or one of the Jekyll plugins bundled with it. I'm no Rubyist either but looks like `html-pipeline` depends on Nokogirl which some of the other gems require. 

Probably worth seeing if this issue has come up over in the [GitHub Pages](https://github.com/github/pages-gem) repo or one of the Jekyll plugins. There could be a reason why they use that specific version of Nokogirl or perhaps have a better fix. Since I'm not a maintainer on any of these projects I really have no control.

**Comment by iulitaro** [comment]
OK, got it. Will leave it as is then.

**Comment by juliohm** [comment]
I am having a somewhat related issue with nokogiri. First I noticed that I had to update the `Gemfile.lock` that comes with minimal mistakes to:

```
BUNDLED WITH
  2.0.1
```

Then I tried to `bundle install --path vendor/bundle` and nokogiri showed this error:

```
An error occurred while installing nokogiri (1.6.8.1), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.8.1' --source 'https://rubygems.org/'` succeeds before bundling.
```

I did what the message suggested and the installation of nokogiri was successful. It only showed a warning that I think is unrelated:

```
WARNING:  You don't have /home/juliohm/.gem/ruby/2.6.0/bin in your PATH,
	  gem executables will not run.
```

Now when I try to execute bundle again, the same error occurs. Could you please advise on how to overcome this issue? Should I change the version of nokogiri in the `Gemfile.lock` file?

**Comment by mmistakes** [comment]
Couple of things. If your couple of bundler is behind a simple `gem install bundler` will update to the latest.

Nokogiri on the other hand has a reputation for being difficult to install. Since you've gotten it to install what I'd suggest is to delete your local copy of `Gemfile.lock`. Then run `bundle update`. This will force bundler to update all of the gems listed in your `Gemfile` and hopefully clear up whatever dependency issue you're having.

Finally, be sure to prepend **all** Jekyll commands with `bundle exec`,

```
bundle exec jekyll serve
bundle exec jekyll build
```

If things still don't work when you run Jekyll, then you'll need widen your search as Nokogiri isn't used by my theme at all. 

It is used by the `github-pages` gem and they likely have [numerous related issues](https://github.com/github/pages-gem/issues?utf8=%E2%9C%93&q=nokogiri) in their repo. And since you only need that to test Jekyll in a way that mimics GH Page's environment, you can go back to using the vanilla Jekyll gem.

Just remove `github-pages` from your `Gemfile`, replace it with `gem jekyll`, and make sure you have all of the jekyll plugins listed as well (`github-pages` gem bundles these so you'll probably need them for things to work properly).

```ruby
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem "jemoji"
  gem "jekyll-include-cache"
end
```

Run `bundle update`, and you should be all set.

**Comment by juliohm** [comment]
Thank you for your attention. I did the first steps as you suggested, deleted the `Gemfile.lock` and tried `bundle update`, now another package is causing the error:

```
An error occurred while installing http_parser.rb (0.6.0), and Bundler
cannot continue.
Make sure that `gem install http_parser.rb -v '0.6.0' --source
'https://rubygems.org/'` succeeds before bundling.
```

Should I proceed and try installing the package manually as suggested?

**Comment by juliohm** [comment]
I did it, and the installation was again successful. The `bundle update` command gave the same error about `http_parser.rb`.

**Comment by mmistakes** [comment]
@juliohm Time to widen your search. Try Stackoverflow you’ll find better help. It’s definitely Nokogiri and it’s dependencies.

**Comment by juliohm** [comment]
Oh my goodness, it seems that paths with spaces in them are problematic somehow: https://github.com/tmm1/http_parser.rb/issues/47

I moved the folder where the project was to another location without spaces, and the error is gone. Unbelievable... 2019 and packages can't handle paths with spaces...

I think we are all set, the site is launching again :) Thank you @mmistakes for your help as usual, and your awesome theme, can't express how much I love it :heart:
