### ISSUE TITLE
Categories & tags show locally but not on github pages

### ISSUE THREAD

**Issue by trevorstephens** [mmistakes/minimal-mistakes#329]
As the title says, when I build locally the category and tags display at the bottom of the post, but when I push to github, they are missing. [Repo here](https://github.com/trevorstephens/trevorstephens.github.io). 

Example outputs:

Locall y @ `http://127.0.0.1:4000/ramblings/a-journey-begins/`:

![untitled](https://cloud.githubusercontent.com/assets/5210848/15634972/87a3fbfe-2586-11e6-8c23-d518694c70ca.png)

[Github](http://trevorstephens.github.io/ramblings/a-journey-begins/):

![untitled2](https://cloud.githubusercontent.com/assets/5210848/15634975/a0f7d652-2586-11e6-8342-bdaea52b3dd7.png)

**Comment by trevorstephens** [comment]
BTW, really love the theme :+1:  thanks for all your hard work!

Also worth mentioning, the tags/categories are being recognized by the archive pages:

- http://trevorstephens.github.io/tags/
- http://trevorstephens.github.io/categories/

**Comment by mmistakes** [comment]
Quick glance at your repo and nothing is standing out to me. Not sure what's going on. The fact that it works locally and not when pushed is strange, I'm stumped.

The only thing I can think of is the [Liquid conditonals](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/page__taxonomy.html) that trigger category and tag lists aren't being met. The GitHub Pages gem was recently updated so maybe something changed or broke. But I doubt it since they're working fine for the MM theme demo that is hosted on GH same as your site.

- [Edge case many categories](https://mmistakes.github.io/minimal-mistakes/aciform/antiquarianism/arrangement/asmodeus/broder/buying/championship/chastening/disinclination/disinfection/dispatch/echappee/enphagy/equipollent/edge-case-many-categories/)
- [Edge case many tags](https://mmistakes.github.io/minimal-mistakes/edge%20case/edge-case-many-tags/)

You don't get any error reports or anything when pushing?

**Comment by trevorstephens** [comment]
Thanks for the quick response Mike!

Nope, all green on the settings page of the repo. Not sure if it is due to not being nested under a `baseurl` like your demo site?

I snooped over the forks of your repo and see this elsewhere as well: https://github.com/ivyleavedtoadflax/ivyleavedtoadflax.github.io/blob/master/_posts/2016-02-22-infographic3.md which is rendered at http://www.machinegurning.com/rstats/infographic3/ for example.

**Comment by trevorstephens** [comment]
Hrmmm. Looks like you are correct on that conditional statement.

https://github.com/trevorstephens/trevorstephens.github.io/commit/eda2cffdb482aa6428b1461f89a7e29a3a8e1d01

http://trevorstephens.github.io/ramblings/a-journey-begins/ gets the 'foo'

**Comment by mmistakes** [comment]
`baseurl` shouldn't matter. The fact that the pages are created is promising. Pretty sure something is up with the Liquid that shows the tag or category lists that linked to above. When I get a chance I'll repush the demo site since it hasn't been rebuilt since `github-pages` updated. 

To rule out the updated GitHub Pages gem try the following:

1. `bundle update`
2. `bundle exec jekyll serve`
3. Verify if categories and tags are there. If they are then I. Really stumped as running Jekyll this way is suppose to mirror the environment on GitHub.

You could also just rip some of the `if` statements in https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/page__taxonomy.html and possibly some in `tag-list.html` or `category-list.html`.

**Comment by mmistakes** [comment]
Sounds like something might have changed then. I'll have to do some testing when I'm in front of a computer. Probably need to modify that conditional if I can reproduce what's going on.

**Comment by trevorstephens** [comment]
Thanks again Mike. Updated the bundle packages and the tags are gone locally now as well.

**Comment by trevorstephens** [comment]
Getting 'foo' on local build as well.

**Comment by trevorstephens** [comment]
The updates were:

    Installing minitest 5.9.0 (was 5.8.4)
    Installing execjs 2.7.0 (was 2.6.0)
    Using jekyll-feed 0.5.1 (was 0.4.0)
    Using ethon 0.9.0 (was 0.8.1)
    Installing html-pipeline 2.4.1 (was 2.4.0)
    Using jekyll-watch 1.4.0 (was 1.3.1)
    Installing jekyll 3.1.6 (was 3.0.3)
    Using jekyll-github-metadata 1.11.1 (was 1.11.0)
    Using jekyll-seo-tag 1.4.0 (was 1.3.3)
    Installing github-pages 80 (was 69)

**Comment by mmistakes** [comment]
I just posted a fix. For whatever reason `site.categories.type`, `site.categories.path`, `site.tags.type`, and `site.tags.path` were all showing values of `null` even though they were populated in `_config.yml`.

This was causing a few things to break. Best I can tell something changed with `site.categories` and `site.tags`. It's possible its a bug in Jekyll but I figured the best solution was just to rename those variables to avoid any clashes.

The fix is to update the following 3 files.

- https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/page__taxonomy.html
- https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/tag-list.html
- https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/category-list.html

**Comment by trevorstephens** [comment]
Thanks Mike! Just posted to the githubs and it's looking great! :+1: :smile:

**Comment by mmistakes** [comment]
Excellent. Thanks for pointing out the bug.

**Comment by trevorstephens** [comment]
My pleasure. Thanks for creating such a great theme and taking care of issues so quickly!

**Comment by jhabdas** [comment]
For those landing here and only want this one fix the [theme upgrade instructions](https://mmistakes.github.io/minimal-mistakes/docs/upgrading/) can be modified as such:

    git remote add upstream
    git fetch upstream
    git cherry-pick 45f3a7a

You'll have some merge conflicts to resolve in `_config.yml`, but that should be it.
