### ISSUE TITLE
Render Error with jekyll-archives?

### ISSUE THREAD

**Issue by authsec** [mmistakes/minimal-mistakes#331]
When I switch from using the liquid type archive to using jekyll-archives the little icons showing tags and categories are no longer shown:

![screen shot 2016-05-31 at 00 22 29](https://cloud.githubusercontent.com/assets/7973409/15659122/d1b2116e-26c5-11e6-8044-464700738777.png)

I'm not sure if it's intended behaviour or a bug, but if it's intended can you make this an option to have it rendered in jekyll-archive mode?

**Comment by mmistakes** [comment]
They should be showing for both as it uses the same HTML for either type. I just tested it yesterday when I pushed a fix and all appeared well. Are you using the latest version of MM 3.2.0?

Do you have a public repo I could see you to try and reproduced your issue?

**Comment by authsec** [comment]
Hi thanks for your response. Unfortunately the repository I worked on is not available online (yet), but I was able to recreate this with a simple post where I set up the repository on github for you to view at https://github.com/authsec/mmistakes-test.

I copied over the files into this repository, upgraded it (hopefully correct) and got the same error when doing `jekyll serve`. It seems it generates the category correctly in the URL pattern, but the icons seem to be missing still. I hope you can reproduce this with the set up.

**Comment by mmistakes** [comment]
Hoping to testing it later tonite, but off the bat I see several things that could be the culprit.

1. You need to uncomment `# gem "jekyll-archives"` from your `Gemfile` then run `bundle install`.
2. If you're not swapping `github-pages` with the `jekyll` gem in your `Gemfile` you'll need to whitelist the plugin in `_config.yml` since all plugins are disabled when running Jekyll thru the GH Pages gem.
3. Make sure you're building/serving with `bundle exec jekyll serve` and `bundle exec jekyll build` as it will eliminate any dependency issues you may have with the various gems and plugins causing Jekyll Archives to behave irregularly.

**Comment by authsec** [comment]
**Thank you!** This works like a charm! And also thank you very much for providing this really awesome theme!

**Comment by mmistakes** [comment]
Excellent. Glad this helped!
