### ISSUE TITLE
Using Jekyll's inbuilt sass/scss compiler

### ISSUE THREAD

**Issue by vg** [mmistakes/minimal-mistakes#333]
Jekyll comes with its own built-in sass/scss compiler. Which also combines multiple @import source files into one css file, and also minifies and compresses the css file. Github Pages has built-in support of this sass-compiler. 

Is there a way to start using the Jekyll's scss compiler it instead recompiling the scss files using node.js and npm every time the stylesheets needs to be changed. 

http://markdotto.com/2014/09/25/sass-and-jekyll/
https://jekyllrb.com/docs/assets/#sassscss

**Comment by mmistakes** [comment]
Yes and no. The theme could absolutely use Jekyll's built-in support for Sass and process `main.scss` that way, but there's a few tradeoffs.

The big one is I've decided to write the CSS without vendor prefixes and let tools like [Autoprefixer](https://github.com/postcss/autoprefixer) handle them. It leaves you with cleaner code and is one less thing to maintain as browsers continue to evolve and update.

The problem is you either need a Jekyll plugin (not supported with GitHub Pages) to run the CSS through Autoprefixer or have an extra build step outside of Jekyll (what I've done) that does it for you.

If your site is targeting modern browsers than piping the CSS through Autoprefixer is probably not something you need to worry about. In that case you could easily reorganize the `.scss` partials into folders Jekyll looks for and [configure Sass](https://jekyllrb.com/docs/assets/#sassscss) there.

I'm hoping that the [Jekyll Assets plugin](https://github.com/jekyll/jekyll-assets) eventually gets whitelisted for GitHub Pages and then I can switch to that since it supports Autoprefixer... among other things.

**Comment by jhabdas** [comment]
Here's an example using Minimal Mistakes with the Jekyll Assets plugin Michael mentioned:

https://github.com/jhabdas/habd.as/

There're a few NPM deps in the manifest still, but none are required for dev. Note this asset pipeline is not as efficient as the Minimal Mistakes built-in default, but it does eliminate the need for multiple registries or even a Node env for that matter. *Not GH Pages friendly.*

**Comment by jhabdas** [comment]
I was off-topic, sorry!
