### ISSUE TITLE
Disqus comments from HTTP side not present on HTTPS site

### ISSUE THREAD

**Issue by ddd-workshop** [mmistakes/minimal-mistakes#350]
If you comment on HTTP site your comments won't be visible on HTTPS site

**Comment by mmistakes** [comment]
That's because Disqus assigns comments based on the page's URL. They're technically two different pages as far as its concerned.

You really should be redirecting your HTTP traffic to HTTPS to avoid the duplicate content. If you're hosting with GitHub [they make this really easy](https://help.github.com/articles/securing-your-github-pages-site-with-https/) now. If you're self hosting you have a few options like editing your `.htaccess` file to do the redirect.
