### ISSUE TITLE
Best practice for inserting search field for site?

### ISSUE THREAD

**Issue by annegentle** [mmistakes/minimal-mistakes#368]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.1.8
- **`github-pages` or `jekyll` gem version:** gem --version 2.5.1
- **Operating system:** Mac OSX

---

## Expected behavior

I'd like to learn how to add a search field -- do you recommend Google Custom Search or a Jekyll plugin such as https://github.com/PascalW/jekyll_indextank? Since I don't see a _plugins folder I wanted to double-check.

## Steps to reproduce the behavior
Intentionally left blank as this is a question.

**Comment by mmistakes** [comment]
Depends on where you plan to host. If on GitHub then a plugin is out of the question (that's why there is no `_plugins` folder in the theme). Google Search is ok but that relies on what Google has indexed of your site which depending on its age might not be much.

I've personally used JavaScript solutions where you build a `json` file of your post content and that is used for searching. One of my older themes, [So Simple](https://github.com/mmistakes/so-simple-theme) has this feature built into it. Most of the Jekyll plugins out there take a similar approach.

**Comment by annegentle** [comment]
Thanks! I'm building the files locally, then pushing flat files (from ``_site``) to a ``gh-pages`` branch, so I think a plugin solution will work as long as it builds something that can be deployed as files.
