### ISSUE TITLE
Pagination is enabled, but I couldn't find an index.html page to use as the pagination template.

### ISSUE THREAD

**Issue by healiseu** [mmistakes/minimal-mistakes#380]
Hi Michael,
first I would like to express my gratitude for the effort you put to make your theme attractive and easy to follow with minimal mistakes ;-)

- [X] This is a question about using the theme.
- [X] I have updated all gems with `bundle update`.
- [X] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.2.10
- **`github-pages` or `jekyll` gem version:** 3.1.6
- **Operating system:** Ubuntu

---

## Expected behavior

I was not expecting to get this message

```
Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination.
```

## Steps to reproduce the behavior

My public repository is
[healiseu](https://github.com/healiseu/healiseu.github.io)

I forked your master repository and changed permalink of 
my home.md to the root folder (/) in order to force generation of index.html inside the _site folder.

I had to erase the index.html from the master branch of your release to make it work.

In my _config.yml file the following lines are without comments

```yml
paginate: 5
paginate_path: /page:num/
```

**Comment by mmistakes** [comment]
Thanks!

The theme defaults to a homepage index with paginated posts. The file that builds that is [`<root>/index.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/index.html). If you're adding `_pages/home.md` with a permalink of `/` then you're essentially telling Jekyll to build two homepage indexes, one overriding the other.

The fact that one of them is a Markdown file is also causing problems with the `jekyll-paginate` plugin.

As per Jekyll's docs in regards to [pagination](https://jekyllrb.com/docs/pagination/).

> Pagination does not work from within Markdown or Textile files from your Jekyll site. Pagination works when called from within the HTML file, named `index.html`, which optionally may reside in and produce pagination from within a subdirectory, via the paginate_path configuration value.

If you want the paginated homepage then remove `_pages/home.md` and move that content into `<root>/index.html`. 

If you don't want a paginated homepage then just remove `<root>/index.html` and the error will go away since you shouldn't be using `paginator.posts` anymore.

**Comment by healiseu** [comment]
Good morning Michael,
thank you for your prompt reply, I don't want a paginated homepage and I have already removed `<roor>/index.html` the error disappears when you comment out these lines at `_config.yml`

```yml
paginate: 5
paginate_path: /page:num/
```
Nevertheless I might need pagination in listing posts, collections, etc. I will have to add more posts and collection files to test that.

**Comment by mmistakes** [comment]
I don't think that's possible. The Jekyll pagination plugin is kind of limited. It only really works with a page at the root of your site. Trying to use it in multiple locations, collections, categories, etc. will likely produce that error. 

- [Octopress Paginate](https://github.com/octopress/paginate)
- [jekyll-paginate-category](https://github.com/midnightSuyama/jekyll-paginate-category)

There are other Jekyll plugins that take a stab at pagination but sadly none of them are supported with GitHub Pages (if you're hosting there).

Closing as this is an issue with the core of Jekyll/plugins and not the theme.
