### ISSUE TITLE
Breadcrumbs is enable, but the link is wrong

### ISSUE THREAD

**Issue by puhemo** [mmistakes/minimal-mistakes#382]
- [x] This is a question about using the theme.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.2.12
- **`github-pages` or `jekyll` gem version:**  jekyll archives
- **Operating system:** windows 10 and mac

---

## Expected behavior

I click jekyll, it should go to http://127.0.0.1:4000/categories/jekyll/, but not.

## Steps to reproduce the behavior

![1](https://cloud.githubusercontent.com/assets/9862655/16405528/ee270cce-3d3a-11e6-978f-fb0980f496d4.png)

![click jekyll](https://cloud.githubusercontent.com/assets/9862655/16405529/f247f390-3d3a-11e6-956f-6e07b5099b10.png)

**Comment by mmistakes** [comment]
Verify you have the [archive settings](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings) properly configured in `_config.yml`. There are settings for the path that may not be filled out. If you're hosting on GitHub then you will have to use the `Liquid` method, so be sure to fill all of that out.

Also the category archive pages may not exist even if you get the path sorted out. If you're using the Liquid method you need to manually create those pages. If you're self hosting then you can use the Jekyll Archives plugin to do that for you automatically.

**Comment by mmistakes** [comment]
I'm going to assume you got this working. If that's not the case feel free to re-open the issue.

**Comment by mmistakes** [comment]
@jleberle - For starters your config is off. Check the paths you're using. I think you flipped the paths for `category_archive` and `tag_archive`. `/categories/` should be with `category_archive` not the other way around.

Also is this your repo that's having the problem? https://github.com/jleberle/jaredeberle.org

If so I just cloned it locally and did a build. I think maybe the confusion is over breadcrumbs and "category" links near the bottom of a post.

For example on this post `/blog/quotes/speaking-at-americans/`

Breadcrumbs all seem to work for me as "Quotes" goes to `/blog/quotes`

![breadcrumbs](https://cloud.githubusercontent.com/assets/1376749/22158827/295b0c82-df0c-11e6-8116-b74f9649af6d.jpg)

The category link does not and is going to `/blog/categories/quotes` which doesn't exist.

![image](https://cloud.githubusercontent.com/assets/1376749/22158861/57a416f6-df0c-11e6-9053-14163f4b2ee3.png)

This is because you're not using `/categories/` in your permalinks as part of Jekyll Archives. You can do it with or without, but they need to match. If you output category pages to `/categories/:name` then the breadcrumb path needs to match that and vice versa.
