### ISSUE TITLE
Tag index archive page

### ISSUE THREAD

**Issue by healiseu** [mmistakes/minimal-mistakes#386]
- [x] This is a feature request.

## [Tag Index](https://mademistakes.com/tag/)

Would it be possible to include a [tag index](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/_layouts/tag_index.html) archive layout in this theme with a similar appearance of what already exists in your made mistakes theme ?

I have tried to make it work by porting bits and pieces but I failed ;-(

**Comment by mmistakes** [comment]
To do what I've done on my personal site it relies on the [Jekyll Archives plugin](https://github.com/jekyll/jekyll-archives). That's partially why I've included a simpler ["list posts by tags" page example](https://github.com/mmistakes/minimal-mistakes/blob/gh-pages/_pages/tag-archive.html) with the theme. 

The presentation of the tag list is nothing special, it's just an `<ul>`. 

![column-1](https://cloud.githubusercontent.com/assets/1376749/16620251/bd977c1c-435f-11e6-8bb5-b0a6ec8869f8.jpg)

The only issue might be browser support. It uses CSS columns which only work with modern browsers.

```css
.tag__list {
  column-count: 3;
}
```

![column-3](https://cloud.githubusercontent.com/assets/1376749/16620261/c721c0f8-435f-11e6-9714-f34dd41bbfb4.jpg)

I'm reluctant to move this into the theme because it's highly stylized and I don't think it visually fits. You are of course more than welcome to do whatever you want with your site.
