### ISSUE TITLE
How to make <html> or <body> fill the screen?

### ISSUE THREAD

**Issue by nickpettican** [mmistakes/minimal-mistakes#395]
Thanks for such a great minimal theme. I'm tailoring it to my needs but I am completely inexperienced with Susy, and I would like my pages to completely fill the screen. How can I do that?

![screenshot from 2016-07-13 10 04 30-02](https://cloud.githubusercontent.com/assets/15140843/16797981/c164f16c-48e1-11e6-8e56-3f9401a0a686.png)

You see, one of my "archive" pages (screenshot above) only has three elements and the footer is smack in the middle of the screen, and I would like to have it at the bottom. 

Thank you! :grin:

**Comment by mmistakes** [comment]
What's going on is the area in blue above is the space occupied by your content, that's why the footer stops at the bottom of that container.

**Short answer:** to push it to the bottom you need to imploy a ["sticky footer" fix](https://css-tricks.com/couple-takes-sticky-footer/). You can give the `.page__footer` a fixed height (eg. `150px`) and add something like `min-height: calc(100vh - 150px);` on `#main` to force it to the bottom. Or if you're only concerned with targeting modern browsers you can use `flexbox`.

Either way you'll need to do some CSS modifications to get it working.

**Comment by nicolaspettican** [comment]
Thanks for your reply!

Yes I initially tried including ```min-height``` and ```height``` in both the base.scss elements ```html``` and ```body``` as well as the ```#main``` to extend the body to fill the screen but oddly nothing worked, so I thought susy might have something to do with it.

I'll try your suggestions out. Thanks again!

**Comment by nickpettican** [comment]
Thanks for your reply!

Yes I initially tried including ```min-height``` and ```height``` in both the base.scss elements ```html``` and ```body``` as well as the ```#main``` to extend the body to fill the screen but oddly nothing worked, so I thought susy might have something to do with it.

I'll try your suggestions out. Thanks again!
