### ISSUE TITLE
Posts are not visible on the index page

### ISSUE THREAD

**Issue by vcidst** [mmistakes/minimal-mistakes#401]
- [x] This is a question about using the theme.

Hi,

I'm setting up my personal website using this excellent theme. However, the posts are not visible. I checked gh-pages branch of your repo to see the tags you've used in posts and added them. My filename was a `md` file and I changed the filetype to `.markup` as you've mentioned on the [guide](https://mmistakes.github.io/minimal-mistakes/docs/posts/)

[Link to website](http://shailendra.me)
[Link to github repo](https://github.com/vcidst/vcidst.github.io)
[Link to the post on github repo](https://github.com/vcidst/vcidst.github.io/blob/master/_posts/2015-08-21-time-capsules-in-space.MARKUP)

I have installed this theme only a couple of hours ago. I forked your repo, added `_posts` folder, `images` folder and editing `_config.yml`

**Comment by mmistakes** [comment]
`.markup` isn't valid. It should be `.md`, `.markdown`, or `.html`. The [Jekyll documentation](https://jekyllrb.com/docs/posts/#creating-post-files) states it that way to imply you can use whatever file format you want.

I probably should include a note about that since you're not the first person to use `.markup` as your file extension. 

Definitely change it back to `.md` for your `_posts`. Something else might be incorrect with your posts for them not to show up on the home page. Verify they are in the correct format and there is no extraneous YAML. Someone else had this exact same issue and it was due to an improper post filename.

**Comment by mmistakes** [comment]
One other thing. You need to enable pagination for posts to show up on the home page. By default it's enabled but I'm not using pagination on the demo site (`gh-pages` branch) so if you copied over the `_config.yml` from there that could explain things.

In your `_config.yml` uncomment lines [229 and 230](https://github.com/vcidst/vcidst.github.io/blob/master/_config.yml#L229):

```yaml
paginate: 5 # amount of posts to show
paginate_path: /page:num/
```

And rename `.MARKUP` extensions to `.md` eg: `_posts/2015-08-21-time-capsule-in-space.md` and everything should work.

I tested locally with your repo and after those 2 changes posts show up on the homepage.

![posts](https://cloud.githubusercontent.com/assets/1376749/16985934/be893014-4e51-11e6-804a-ca82dbf19047.jpg)

**Comment by vcidst** [comment]
Thanks a lot Michael, didn't realize pagination meant that.
