### ISSUE TITLE
Jekyll plugins

### ISSUE THREAD

**Issue by steveschow** [mmistakes/minimal-mistakes#4617]
### Motivation

Please provide some information in the docs about how we can use some common Jekyll plugins with minimal-mistakes, such as Jekyll-mermaid, Jekyll-planuml, Jekyll-spaceship, Jekyll-lilypond.  None of these seem to work properly with minimal-mistakes, so I don't know if there is something In need to tweak to get them to work or if we just have to accept that minimal-mistakes can't work with them.  And why  not?

### Suggestion

Please make minimal-mistakes more compatible with common Jekyll plugins such as these mentioned.

**Comment by yonz2** [comment]
And please add detailed information on creating a multi-lingual sites using minimal-mistakes and e.g. jekyll-polyglot

**Comment by ryan-p-randall** [comment]
Hi @steveschow and @yonz2 : at least according to the [theme's current documentation on plugins](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#plugins), the issues you're experiencing are far more likely to be due to hosting on GitHub Pages than the Minimal Mistakes theme itself.  

If—like me!—you're using the theme with GitHub Pages, you might look into [GitHub Actions](https://github.blog/2022-08-10-github-pages-now-uses-actions-by-default/). Those will let you use a far wider range of plugins than the small set that GitHub Pages allows by default.  

I hope that's helpful!

**Comment by steveschow** [comment]
I'm not using GitHub pages yet

**Comment by iBug** [comment]
Most plugins are out of scope for this project, unless they explicitly require theme support. If you can demonstrate *how* we can add support (or even file a PR for that - you're welcome), we might look into this again.
