### ISSUE TITLE
Background Image between Footer and Masthead

### ISSUE THREAD

**Issue by sashaDoubov** [mmistakes/minimal-mistakes#470]
Been loving the project, thanks!

I'm trying to place a background image between the footer and the masthead, and having it stay as a fixed image (one that doesn't resize) when you resize the window. 
 I'm also trying to make the page a constant page size (no scrolling).

When I place the image into the body of the page, the masthead also gets the background, which isn't something I want. 
![image](https://cloud.githubusercontent.com/assets/4717972/17861539/736d0042-685f-11e6-9fdf-6a8181092fc9.png)

Here's the code snippet of the home page: 
```html
---
layout: home-custom
---
<style>
html { height: 100% }
body
{
    margin: 0;
    padding: 0;
    height: 100%;
    overflow: hidden;
    background-image: url(./images/site_back.jpg);
   background-repeat: no-repeat;
   background-size: cover;
}
</style>`
```
Here's the [site](https://sashadoubov.github.io/) and the [project](https://github.com/sashaDoubov/sashaDoubov.github.io).
Any help would be greatly appreciated (disclaimer: don't have much web experience).
Thanks!

**Comment by mmistakes** [comment]
This is a really easy one to solve. Using the Developer Tools available to you in any modern browser you can inspect various elements on the page.

![dev-tools](https://cloud.githubusercontent.com/assets/1376749/17862106/d28bfb80-6861-11e6-8be5-88f16108220c.jpg)

By inspecting the navigation you'll see all of the CSS assigned to it. On the `.greedy-nav` element there's a `background: #fff` which is giving it the white background. Just remove [that declaration](https://github.com/sashaDoubov/sashaDoubov.github.io/blob/master/_sass/_navigation.scss#L178) from `_sass/_navigation.scss` and that should remove the background color.

![transparent-nav](https://cloud.githubusercontent.com/assets/1376749/17862110/d5922822-6861-11e6-8ca3-eddec28e8231.jpg)

You'll probably have to alter the nav link color since it's unreadable on the image...

**Comment by sashaDoubov** [comment]
Ok thanks! How would I do the opposite of that, make that entire block above the horizontal rule white (including the masthead)?

**Comment by mmistakes** [comment]
Same way. Use the web developer tool inspector in the browser and start inspecting elements. If you inspect masthead `<div>` you'll get what you want.

![masthead](https://cloud.githubusercontent.com/assets/1376749/17863032/f9291d00-6865-11e6-95ec-e25cc7dbea43.jpg)

Then just add `background: #fff;` to `.masthead` found in `_sass/_masthead.scss`.

```diff
.masthead {
  position: relative;
  border-bottom: 1px solid $border-color;
  -webkit-animation: intro 0.3s both;
          animation: intro 0.3s both;
  -webkit-animation-delay: 0.15s;
          animation-delay: 0.15s;
  z-index: 20;
+ background: #fff;
}
```

![masthead-white](https://cloud.githubusercontent.com/assets/1376749/17863064/186faf6c-6866-11e6-813b-0e95c9b1cbf6.jpg)

**Comment by sashaDoubov** [comment]
Thanks so much!
