### ISSUE TITLE
<!DOCTYPE html><html>

### ISSUE THREAD

**Issue by xiongyoudou** [mmistakes/minimal-mistakes#478]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **`github-pages` or `jekyll` gem version:** 
- **Operating system:** 

---

**Comment by mmistakes** [comment]
What's the question/issue you have?

**Comment by mmistakes** [comment]
If you still have a question or issue feel free to reopen with more info.

**Comment by xiongyoudou** [comment]
Sorry,my question is not clearly.but i solved it with another way.
my problem is that:when files in _posts directory is html type,thus will lead to show description on each post like "<!DOCTYPE html><html>" on index page.
i solved it by add "excerpt" on the top of post,so it will be fine!

**Comment by mmistakes** [comment]
You shouldn't be adding `<!DOCTYPE html>` to your posts, that's why it was being injected into the excerpts and probably in other places you didn't notice. 

Posts should just be the body content. The rest of the containing HTML comes from the post/page layouts.

For example the doctype is already in [`_layouts/default.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/default.html#L7)
