### ISSUE TITLE
Chinese duoshuo Comment System bug when use compress layout

### ISSUE THREAD

**Issue by BruceZhaoR** [mmistakes/minimal-mistakes#484]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: 3.7** 
- **`github-pages` or `jekyll` gem version:89/3.1.6** 
- **Operating system:win10** 

---

## Expected behavior

The fixed footer should not cover the comments system.

## Steps to reproduce the behavior

please go to my site to see what's going wrong:  <http://bzrlc.tech/nlp/hxf-text-analysis-1/> 
github repository:  bzrlc/bzrlc.github.io

![1](https://cloud.githubusercontent.com/assets/8092534/18002037/5d3f1696-6bb8-11e6-9807-46c57b22dd1e.png)

**Comment by mmistakes** [comment]
Seems as if you removed `{% include scripts.html %}` from `_layouts/default.html`. None of the theme's scripts are working because of that. For example the nav button doesn't trigger, the author "Follow" button doesn't trigger, and the script that fixes the footer placement by adding padding to its parent so it doesn't cover up content doesn't trigger either.

Without `main.min.js` being included on the page none of those things will work, which is why your site is broken.

Not sure if you did any other customization but it appears that's the cause.

**Comment by BruceZhaoR** [comment]
@mmistakes  Thank you very much! :+1:   I am so careless. :flushed: This theme is so complicated, and  so hard for me to custom my site, as I have poor knowledge of font-end. 

After I add the `main.min.js` , everything looks all right locally, here is the snapshot:

![test](https://cloud.githubusercontent.com/assets/8092534/18012015/294fba16-6bea-11e6-8c6e-160f50066cf5.png)

 **But, the comments module doesn't show in the github-pages**.  :sob:  ..so sad ... I spent a lot time on it ,but still can't find the cause. If you have time, please see the site: http://bzrlc.tech/nlp/hxf-text-analysis-1/ .  Thank you sooo much!

**One more thing,** I got trouble with the `breadcrumbs` . It missed the `/` , and  I didn't modify the `_includes/breadcrumbs.html`.

**Comment by mmistakes** [comment]
Not sure on the comments. My guess is the JavaScript embed for them isn't loading.

As far as breadcrumbs. I'd advise against using them. It's a beta feature and takes a lot of manual adjustments to make it work right. Too much can go wrong with paths that it's not worth turning on unless you really understand what's going on with all your content.

**Comment by BruceZhaoR** [comment]
Thank you for your quickly response!  The comments module worked fine couples years ago, and it worked fine locally just now ,  So  weird ...   As far as breadcrumbs,I will stop using it tomorrow.

**Comment by mmistakes** [comment]
If it's working locally then that's promising. Can be hard to troubleshoot frontend issues if you don't know what you're looking for.

I'm not familiar with the commenting platform you use to be any help there. But since that gets added to the page with JS and you had JS issues before I'd backtrace whatever changes you made to the theme. There's likely something missing or incompatible with other scripts.

Notice you have AnchorJS loaded on the page as well. Maybe disable all the JS and start turning scripts on one by one to identify what's causing the problem.

Stackoverflow can be helpful in these cases too since this is more of a frontend dev question than something I can fix with the theme.

**Comment by BruceZhaoR** [comment]
@mmistakes  I figured out the problem! The cause is that I used the compress in the default layout. Maybe you should mention that those who use Chinese comments system --`duoshuo.com` may encounter Problems when use compress layout.

BTW, I used a new archive layout ,[see detail](http://bzrlc.tech/archive/), which copied from my personal blog, [see detail](http://brucezhaor.github.io/archives/).  Do you need the layout?  If so, I could make a PR.

At last, Thank very much for your work, Great Theme! :+1:

**Comment by mmistakes** [comment]
Good to know. I can add a note about inline JavaScript comments `//` causing issues with `layout: compress`. It's [documented on their site](http://jch.penibelst.de/) and didn't even think to mention it on my theme docs.

**Comment by BruceZhaoR** [comment]
It has some additional settings , I will try not compress all parts.  Thanks for your help！
