### ISSUE TITLE
How do you sort a collection? 

### ISSUE THREAD

**Issue by zfrenchee** [mmistakes/minimal-mistakes#491]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

I was curious about how to sort a collection. I see that you've prefixed the files in your docs collection with numbers, but when I do so I still don't get a sorted collection. I am not using the date in the filenames, as it seems that's conventional for posts but not members of collections.

**Comment by mmistakes** [comment]
I believe by default collections are sorted alpha-numeric, which is why I prefixed the filenames with numbers. If that's not happening for you then something else is at play and best to ask help on talk.jekyllrb.com

Otherwise, you'll find a few solutions out there for other sorting options. The most common pattern I've seen is to add something like `order: 1` , `order: 2`, `order: 3`, etc. to the YAML Front Matter.

Then you can use Liquid's `sort` filter to reorder them referencing that field:

```yaml
{% for c in site.your_collection_name | sort: 'order' %}
```

**Comment by zfrenchee** [comment]
thanks!

**Comment by zfrenchee** [comment]
ahh -- I see why the prefixing doesn't work. It's because it's very naive. 

It goes 10, 11, .. 19, 1, 20, 21, ... 29, 2, 30, ...

The way to fix this is to make 1 -> 01. Somehow it seems you got away without this @mmistakes ?

**Comment by mmistakes** [comment]
Been awhile since I set up the pages for the docs collection, but that sounds about right.

The better solution is add a key to the YAML Front Matter and sort on that instead of having to change filenames anytime you want to update the order.

Potentially gotcha would be to make sure you don't wrap the numbers in quotes or apostrophes as that would imply a string and I think you'll run into the same sort order issue with `1 != 01`. So do `order: 1`.

**Comment by mmistakes** [comment]
And if that doesn't work @zfrenchee check out the FAQ collection on my personal site.
I'm setting order in each document there `order: 1`, `order: 2`, etc.

Then I spit them out like this

```
{% assign other_faqs = site.faqs | where: "type", "other" | sort: "order" %}

<ul>
{% for faq in other_faqs %}
<li><a href="{{ faq.url }}">{{ faq.title }}</a></li>
{% endfor %}
</ul>
```

https://github.com/mmistakes/made-mistakes-jekyll/tree/master/src/_faqs
https://github.com/mmistakes/made-mistakes-jekyll/blob/master/src/_pages/faqs.md

**Comment by zfrenchee** [comment]
Can you do a reverse sort? @mmistakes

**Comment by mmistakes** [comment]
Yes. With `reverse`

https://help.shopify.com/themes/liquid/filters/array-filters#reverse

**Comment by CharlieLiu17** [comment]
Where would we add the liquid sort code? To the collection page's md? I'm also unsure I'm using the correct site variable, getting an "Liquid Warning: Liquid syntax error (line 1): Expected end_of_string but found pipe in "c in site.portfolio | sort: 'order'" in _pages/portfolio.md" error.

**Comment by seasoneddevtest** [comment]
First, add `sort_by` and `sort_order` to your collection page, for example `_pages/experience-archive.md`:

```
---
title: Experience
layout: collection
permalink: /experience/
collection: experience
classes: wide
sort_by: order
sort_order: reverse
---
```

Second and last, add `order` to your collection documents, for example `_experience/2008.md`:

```
---
title: "2008 - 2012"
order: 1
---
```
