### ISSUE TITLE
How do we modify images during local testing?

### ISSUE THREAD

**Issue by DanielSank** [mmistakes/minimal-mistakes#497]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

## Environment information

* github-pages 94
* Ubuntu 14

## Expected behavior

I expect to be able to change the images rendered during local testing.

## Reproduce the behavior

* Clone the git repo
* `$ bundle install`
* `$ bundle exec jekyll serve`
* At `localhost:4000` I see the silhouette coming from `bio-photo.jpg`. I note that this image is being served from the web, not from my local disk.
* Change the file name in `_config.yml` to `my-photo.jpg` and put `my-photo.jpg` into the images directory.
* `$ bundle exec jekyll serve`
* The image on the index page is a broken link. This isn't surprising because the image URL is `http://danielsank.github.io/images/my-photo.jpg` which doesn't exist because I've only made local changes.

**Comment by mmistakes** [comment]
When working locally you need to change `url` in _config.yml to `http://localhost:4000`. Otherwise all of the asset links will still be using `http://danielsank.github.io`.

If you do this restart the server with `bundle exec jekyll serve` and all your assets (images, CSS, and JS) should all have paths starting with `http://localhost:4000` and pull in the local versions.

**Comment by DanielSank** [comment]
Yeah, noticed that's called out in the docs. Sorry I missed that.
