### ISSUE TITLE
Improve extensibility of theme styling and _variables.scss

### ISSUE THREAD

**Issue by vwchu** [mmistakes/minimal-mistakes#519]
- [ ] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [x] This is a feature request / enhancement / refactoring.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---
## Environment informations
- **Minimal Mistakes version:** 3.4.6

---
## Enhancement

In effort to improve maintainable, easier installation/upgrading and in preparation for the transition to Ruby gem-based theme #419, should the following refactoring be performed:
1. Move `assets/css/main.scss` to `_sass/_main.scss`
2. Add variable defaults `!default` to all variables in `_variables.scss` so that variables can be easily overridden without modifying `_variables.scss` directly. 
3. Replace assets/css/main.scss with a simple redirection to `_sass/_main.scss`
   
   ``` scss
   @import "main";
   ```

**Comment by mmistakes** [comment]
Waiting to see how the other assets part of gemified themes work before refactoring or changing anything. There might be implications there that affect what I do with the Sass partials.

**Comment by vwchu** [comment]
That makes sense. My concern is that as-is, in order to customize the theme, we need to edit main.scss or _variables.scss (causing possible merge conflicts). And in Ruby gem themes, we would have to recreate that file. That kind of defeats the pont of isolating the theme from the user's customization.

**Comment by mmistakes** [comment]
That's a valid concern. It's still early days with all of this so either way there's probably going to be some conflicts to deal with. What makes it harder is everyone tackles this a different way. When I do get around to this I will most adopt some "best practices" from the `minima` theme.

I don't plan on making any major changes to the `.scss` files and the changes I do make will be very similar to what you suggested above.

Files are just going to move around to conform to a gemified way of packaging it up. It shouldn't be that big of a deal to merge in whatever customizations you've made. If the file names aren't changing then simply placing your customized files in the appropriate locations will have them take precedence over the ones in the `gem`.

As it stands now it's kind of a clunky process because you need to create that initial `.scss` file that `@imports` all the partials. Once support is added for `.css`, JS, images, and the like I think things will get much easier.


Refs:
- https://github.com/mmistakes/minimal-mistakes/issues/419
- https://talk.jekyllrb.com/t/jekyll-theme-building-workflow/2841
- https://github.com/jekyll/jekyll/issues/5341
- https://github.com/jekyll/jekyll/issues/5343

**Comment by DanielSank** [comment]
Would the changes proposed here allow users to edit e.g. the color of the title of individual posts? To do this now, it seems we need to modify the hard-coded rbg value in `_sass/_page.scss.

**Comment by mmistakes** [comment]
@DanielSank this proposed pull requests doesn't add any new functionality or change how you currently customize your site's CSS. It's more of a "house-keeping" thing as part of [gemifying the theme](http://jekyllrb.com/docs/themes/) down the road.

On that note, @vwchu have you seen this [PR to jekyll/jekyll](https://github.com/jekyll/jekyll/pull/5364)? I think once this lands your PR won't be needed as the entire contents of `/assets/` will be bundled into the gem. Which means `assets/css/main.scss` can stay put.

There's still probably a case to be made for adding `!default` to the Sass variables in **_variables.scss**...

**Comment by vwchu** [comment]
@mmistakes Thanks for the heads up. I think the bundling of the `assets` directory is great. However, to custom the theme, still when require overwriting (copying) the main.scss into the user's files. My concern still stands, in that I much rather not overwrite theme files (so I can take advantages of updates upstream) and add customization in addition to them. That's why I suggested the move of the main.scss, that way my main.scss only how one line (to import the theme's main).

**Comment by mmistakes** [comment]
@vwchu I'd like to avoid moving things around if possible. And the fact that the entire `/assets/` folder can be bundled means nothing has to change in that regard.

Still not convinced 100% `main.scss` has to drop all the SCSS partial imports and stuff them into another folder just so it can be a 1 liner. Once you dip into the world of customizing the theme you're going to have to worry about staying in sync regardless.

An unlikely scenario, but a possible scenario none the less is variable names change in `_variables.scss`. If any of your SCSS partials reference them... boom! Things break for you and you have to make sure you're on top of what changes with each release.

**Comment by vwchu** [comment]
@mmistakes Agreed. Moving things around is kind of breaking change. The scenario you mentioned is possible. And it really isn't about `main.scss` being a one-liner, rather in a gemified theme setup, if I add my own scss file, I need to make my own copy of `main.scss` in my user project. If you later add new features (new scss files), I won't see those updates, because I will only see my own copy. That's the dilemma/issue. And it is true for any theme files. If we say we will never touch `main.scss` that file is for users to customize, we won't have these issues, and users generally never have to override any theme scss files, since they can always override the CSS rules by redefining them in their own scss files.

**Comment by mmistakes** [comment]
That logic can apply to any changes to `.scss` files though. If breaking changes occur in any of the partials you won't know about that either unless you're carefully monitoring ever change made to the gem.

**Comment by vwchu** [comment]
Of course, you have to test when updating for breaking changes.

The complication is the way Jekyll overrides theme files with user files when user files are included. I know it's simplest and most straightforward way of doing, probably the best way. But from my reading of it, themes should try best to avoid or limit the need for these kinds of overrides whenever possible. Otherwise, we defeat the benefits have themes are gems as oppose to forking.

**Comment by mmistakes** [comment]
Still early days on all of this with Jekyll and I don't think the best practices have emerged. I'm sure things will become clearer as the feature grows and is adopted. The discussion is always good to have.

Probably some good ideas to pick from how Wordpress and the like handle it with something like a child theme. Which I guess is essentially what Jekyll is doing.

1. You have the pristine theme in a gem that the user can't touch.
2. Files placed in `_sass`, `_includes`, `_layouts` and the soon to be `/assets` act as "child theme" partials that will override the gem if file names match.

I'm willing to bet most users of this theme never touch any of that and would welcome a nicely packaged theme they can just install via `Gemfile` and 1 line in their _config.yml. Purely speculative sure, but looking at most of the forks a good majority are that way or from versions I released years ago.

Afraid overrides will always exist for those who want to tinker and make the theme do what they want. No way around that, unless config switches and custom code injection points/hooks are added everywhere... which I have no intention of tackling.

**Comment by vwchu** [comment]
Agreed. This is probably a discussion that is happening in many parts of the Jekyll community. What conventions and best practices will allow for themes and child-themes to coexist and benefit from each other while not stepping on each other's toes.

**Comment by publicimageltd** [comment]
I know the issue is closed, but I like to add +1 to the request. I think "tinkering with the css" is relative. I would just like to add some additional classes without having to bother about the updates. If my site does not work, I would just "turn off" the additions and then look what's causing the error by successively commenting in the style definitions. 

So my suggestion: Why can't we add the path to an additional style files in the config.yml, which are then included in the main page? This way, I do not have to bother about the gemified files and can still add my little helper classes.

**Comment by mmistakes** [comment]
@publicimageltd I'm not that keen on adding some sort of path variable to `_config.yml` as that would be really limiting. The second after I add support for that someone would want the ability to add two CSS files to the head.

That said I've built in a way to add whatever you want to the `<head>` element... additional CSS files, scripts, etc.

Through the magic of gemified theme gems you just need to add `_includes/head/custom.html` to the root of your site, and then put in there whatever you want. The theme gem is bundled with that file, which is completely blank. So anything you put in your local version will override it.

You could add a `link` element that points to a `.css` file. Or you could just drop the CSS in like:

```html
<style>
.foo {
  font-weight: bold;
}
</style>
```

Now if you're performance minded you might not like the idea of having additional HTTP requests in your `head`. If you'd prefer to bundle your custom CSS in with `main.scss` you can do that as well with a theme override.

Simply copy [`main.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/css/main.scss) to your site's root and put it in `/assets/css/`. After all the `@import`s you could add your custom styles.

On build the theme SCSS will preprocess as usual and then tact on anything you add at the end.

This method is slightly fragile because if the theme ever adds/removes a SCSS partial you'd need to make that change to your local `main.scss` file. But that rarely happens so it shouldn't be a big deal.

---

The ideal situation would have a `/_sass/_custom.scss` file that you could override locally. Problem is the way Jekyll currently works you can't override a single static file in that way. Not sure if that will ever change but there is [an issued](https://github.com/jekyll/jekyll/issues/5676) opened for it.

**Comment by publicimageltd** [comment]
Thanks for the fast reply! That's a good solution, since it enables me to have a global style sheet with no hassle. Would be perfect if one could access all the SCSS vars, but I understand that this is another (more complicated) issue. 

One idea would be to WARN the user when upgrading a gem and the upgrade affects a file which has a local overriding copy. This way, at least, one is informed when updating.

Anyways, thanks for the great theme and the good support!
