### ISSUE TITLE
GitHub Metadata Warnings/Errors

### ISSUE THREAD

**Issue by justinrummel** [mmistakes/minimal-mistakes#570]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: current master** 
- **`github-pages` or `jekyll` gem version: 3.2.1** 
- **Operating system: macOS** 

---

## Steps to reproduce the behavior

When running bundle exec jekyll serve I keep getting these GitHub Errors/warnings.  I'm not sure if there is an issue, or if something is not configured correctly in the [_config.yml](https://github.com/justinrummel/jr.com-mm/blob/jr-branch/_config.yml).  My site is hosted on a 3rd party service and NOT on GitHub.  I use [octopress deploy](https://github.com/octopress/deploy) jekyll plugin to make rsync work in a simple fashion. 

``` bash
justinrummel@Rummel-MBPr ~/D/G/jr.com-mm> bundle exec jekyll s -c _config.yml,_AccessKeys.yml,_localhost.yml
Configuration file: _config.yml
Configuration file: _AccessKeys.yml
Configuration file: _localhost.yml
            Source: /Users/justinrummel/Documents/GIT/jr.com-mm
       Destination: /Users/justinrummel/Documents/GIT/jr.com-mm/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: GET https://api.github.com/repos/justinrummel/jr.com-mm/pages: 404 - Not Found // See: https://developer.github.com/v3
                    done in 26.898 seconds.
 Auto-regeneration: enabled for '/Users/justinrummel/Documents/GIT/jr.com-mm'
Configuration file: _config.yml
Configuration file: _AccessKeys.yml
Configuration file: _localhost.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

**Comment by mmistakes** [comment]
I haven't seen these particular errors before, but have seen similar related to the [`jekyll-github-metadata`](https://github.com/jekyll/github-metadata) gem used by GitHub Pages.

I don't know much about how that gem works other than it helps populate some site variables that GitHub Pages hosted sites can leverage. Setting `repository` in your `_config.yml` does most of the heavy lifting as does setting `origin` on your site's remote to a github.com URL.

Since you're not hosting with GitHub then there's no reason for you to use it I would assume. Here's what I would do:

**Step 1.** In your `Gemfile` replace `gem "github-pages", group: :jekyll_plugins` with `gem "jekyll"` and add all of the Jekyll plugins used in your `_config.yml` (they're under `gems:`). You need to do this because `github-pages` automatically installs them and the vanilla `jekyll` gem does not.

You'll end up with something like this:

```ruby
source "https://rubygems.org"

gem "jekyll"
gem "wdm", "~> 0.1.0" if Gem.win_platform?

group :jekyll_plugins do
  gem 'octopress'
  gem 'jekyll-archives'
  gem 'jekyll-twitter-plugin'
  gem 'jekyll-lunr-js-search'
  gem 'jekyll-paginate'
  gem 'jekyll-sitemap'
  gem 'jekyll-gist'
  gem 'jekyll-feed'
  gem 'jemoji'
end
```

**Step 2.** Run `bundle update`

**Step 3.** Run `bundle exec jekyll s -c _config.yml,_AccessKeys.yml,_localhost.yml` and see if everything works. If you get any errors about missing gems add them to your `Gemfile`, `bundle install`, and try to fire up Jekyll again. There may be a gem or two that `github-pages` loaded as a dependency that `jekyll` does not.

**Optional?** You can probably safely remove `repository: justinrummel/jr.com-mm` from `_config.yml`.

**Comment by justinrummel** [comment]
Thank you!  This solved the warnings, plus helped fix the lunr search all in one step!!!

**Comment by mmistakes** [comment]
Good good.
