### ISSUE TITLE
Problems with custom sidebar

### ISSUE THREAD

**Issue by jonbra** [mmistakes/minimal-mistakes#571]
- [x] This is a question about using the theme.

---

## Environment informations

- **Minimal Mistakes version:** 3.4.8
- **`github-pages` or `jekyll` gem version:** Github online
- **Operating system:** Online only

---

## Expected behavior

I want to add several documents with a common custom sidebar such as you have here: https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

## Steps to reproduce the behavior
I have added _resources to collections in _config.yml, added a custom sidebar with urls in navigation.yml called resources with sub-urls such as /resources/intro/ and /resources/setting-up-project/, and the main links in navigation.yml point to /resources/, and the files in the directory _resources have permalinks: /resources/intro/, /resources/setting-up-project/

https://github.com/jonbra/jonbra.github.io
https://jonbra.github.io/resources/

At one point the sidebar was showing, but the links did not work. But I was able to press the "next" box at the bottom of the page. But now nothing is showing up now.

**Comment by mmistakes** [comment]
Something is up with your Resources collection as it's not even building those pages. I'm not seeming anything obviously wrong so not sure what's going on there.

**Comment by mmistakes** [comment]
I built your site locally and the resource pages built. There's some issues you need to fix though.

1. `/resources` throws a 404 because an `index.html` doesn't exist for it.  `resources/intro` and `resources/setting-up-project` build though as they're in your collection.

![resources](https://cloud.githubusercontent.com/assets/1376749/19190781/660afb84-8c6d-11e6-9f36-ad2a5912465c.jpg)

You have some bad YAML in `navigation.yml` which is breaking the sidebar links and styling. Remove the hyphens from `url` lines to clear that up. Should be:

```yaml
# Abel navigation links
resources:
  - title: Working with Abel
    children: 
      - title: "Introduction"
        url: /resources/intro/
      - title: "Setting up a project"
        url: /resources/setting-up-project/
```

Which will give you the working sidebar.

![corrected](https://cloud.githubusercontent.com/assets/1376749/19190872/cdbb6ed0-8c6d-11e6-9a64-b44a894a697a.jpg)

**Comment by jonbra** [comment]
Thanks. Didn't notice the extra hyphens... 
Do you have any idea why the resource collection doesn't build? I tried adding a new collection, but same problem. Is there a maximum number of collections in the template? The other collections are working fine...

**Comment by mmistakes** [comment]
Not sure. When I cloned your repo it the resources collection build fine for me minus the sidebar issues due to the extra hyphens.

**Comment by jonbra** [comment]
Ok, but thanks for the help. I can see the pages fine, including the sidebar, if I put them in a regular directory with an index.md in it. So this is working for now.
