### ISSUE TITLE
Google AMP Support

### ISSUE THREAD

**Issue by Wferr** [mmistakes/minimal-mistakes#584]
Baking in support for Google AMP (https://www.ampproject.org/docs/reference/components) would be pretty awesome.  Id be up to help. Doesnt seem that bad. And the Page speed is amazing.

**Comment by mmistakes** [comment]
I've considered it but it takes more than just some theme changes I'm afraid. To do it right you really [need a plugin](https://github.com/juusaw/amp-jekyll) that can do some of the heavy lifting for you:

- RegEx over your content and replace `img` elements (and the like) with `amp` ones
- Generate `amp` pages of all your content

I'm much more in favor of making the site as optimized as possible without being too opinionated with the defaults. Especially since there are a few things AMP doesn't really do yet or have specs for (e.g. navigation menus). 

For more context I hammered out [some thoughts on the subject](https://github.com/mmistakes/made-mistakes-jekyll/issues/21) here.

**Comment by cortix** [comment]
I tried to install plugin but somehow it didn't work. By the way, I found a solution outside the AMP pages. 

You only need to add a **loading attribute** with a value of lazy to the img tag in the HTML markup.

`loading="lazy"` - add to images that should be lazy loaded

`<img src="{{ site.url }}{{ site.baseurl }}/assets/images/sample.webp"   width="100%" height="100%"  loading="lazy" alt="sample">`

The loading attribute also supports two other values:

- `eager` - for images that shouldn’t be lazy loaded;

- `auto` - lets the browser decide if an image should be lazy loaded.

As far as I can see, many browsers support it. I hope it helps.
