### ISSUE TITLE
Optional Author Bio?

### ISSUE THREAD

**Issue by ozank** [mmistakes/minimal-mistakes#6]
Thank for making this beautiful template available.

What would be the easiest way to remove the author bio in the main page? I've tried to comment out 

```
{% include author-bio.html %}  
```

section in the home.html, but now article lists aligned to left (see: http://ozank.github.io/asuyatuyolar/ )

**Comment by stanstrup** [comment]
I'd like to do this too. But I can only find the right CSS in the generated CSS file. Which source file and where do I change this?

**Comment by mmistakes** [comment]
@stanstrup The source files are all in `/_sass/`, you'll probably find what you need in the [page.scss](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/page.scss) partial.

**Comment by stanstrup** [comment]
Thanks again for your help and patience. I cannot for the life of me figure which line to change. If I simply add

```
#index {
    margin-left: 25%;
}
```

to the end of the document it works though.

**Comment by mmistakes** [comment]
The `#index` declarations are all around [line 248](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/page.scss#L248). The media query mixins are probably what is tripping you up. Because the theme is responsive the column widths change depending on the screen size. Depending on where you place `margin-left: 25%;` will have different results.

You'll probably want to add it here so it pushes the main column over on larger screens only since on mobile the theme defaults to a single tube of content.

```
@media #{$x-large} {
    @include grid(12,4.5);
    margin-left: 25%;
}
```

The smarter thing would be to use `prefix` mixin to pad the left and fill the space originally occupied by the author sidebar.

```
@media #{$x-large} {
    @include grid(12,4.5);
    @include prefix(12,3); // adds 3 columns of blank space to the left
}
```

**Comment by stanstrup** [comment]
Thanks so much! It works great. And you are right. I thought I had a decent grasp of basic CSS but I am wholly unfamiliar with this syntax.

**Comment by mmistakes** [comment]
@stanstrup For the most part Sass is CSS, it just has a few tricks up its sleeve like nesting, variables, and mixins to augment things. The [basics are documented here](http://sass-lang.com/guide) if you're interested.

**Comment by stanstrup** [comment]
Thanks for the pointer. I will read up on this as I move along with my own site.

**Comment by stanstrup** [comment]
For reference [here](https://github.com/stanstrup/stanstrup.github.io/tree/891ffa569ab606b5170ea3673a587b0ed043871f) is a version with no sidebar and more space in the middle based on @srijanshetty's fork ([has categorized posts](https://github.com/mmistakes/minimal-mistakes/issues/184)).
It has been cleaned up (stuff deleted) to be a minimal starting point for a new site.
