### ISSUE TITLE
What would be the best way to have archive layout show full posts, rather than excerpts?

### ISSUE THREAD

**Issue by skinnylatte** [mmistakes/minimal-mistakes#601]
Hi there,

Using your theme on [Popagandhi.com](http://popagandhi.com), my personal blog. 

I previously had a Jekyll blog that had full posts using the post.content tag. I haven't quite figured out the structure of your theme — do you mind pointing me to where I could edit that file to show full posts rather than excerpts on my index page?

**Comment by mmistakes** [comment]
You'll want to replace `{{ post.excert }}` with `{{ post.content }}`. The index pages use [**_includes/archive-single.html**](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/archive-single.html#L38) which is where you'll want to make the modification.

Change this line:

```html
{% if post.excerpt %}<p class="archive__item-excerpt" itemprop="description">{{ post.excerpt | markdownify | strip_html | truncate: 160 }}</p>{% endif %}
```

to this:

```html
{{ post.content }}
```

And it should do what you want. You may need to do additional styling since the theme wasn't built to support full post content on the archive pages.

**Comment by justinrummel** [comment]
I've done this also with my site.  I would recommend duplicating the archive-single.html to a new file and call that on your root index.html file.  archive-single.html is used in several other places and may cause undesired effects (e.g related stories). 

- [index.html](https://github.com/justinrummel/jr.com-mm/blob/jr-branch/index.html)
- [archive-single-main.html](https://github.com/justinrummel/jr.com-mm/blob/jr-branch/_includes/archive-single-main.html)

**Comment by skinnylatte** [comment]
Thank you, both! @mmistakes @justinrummel
