### ISSUE TITLE
Efficiency of self hosting font-awesome.

### ISSUE THREAD

**Issue by vg** [mmistakes/minimal-mistakes#610]
I would just like to ask, if there is any specific reason that you have decided to self host font-awesome typefaces. Does not it make more sense to load them off cdn.fontawesome.com.
Which in turn would speed up load times, and there is a big possibility that the fonts are already cached on the client.

- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---
## Environment informations

- **Minimal Mistakes version:** 
- **`github-pages` or `jekyll` gem version:** 
- **Operating system:** 

---

**Comment by mmistakes** [comment]
Simple. It's included with the global style sheet to eliminate the extra HTTP request which has performance benefits. I won't argue that using a CDN version of FA or jQuery, or any other assets have their merit.

It mostly boils down to me liking the idea of including those dependencies directly in the project rather than hotlinking to a bunch of external hosts.
