### ISSUE TITLE
Is there some easy/elegant way to change the footer

### ISSUE THREAD

**Issue by zfrenchee** [mmistakes/minimal-mistakes#615]
- [x] This is a question about using the theme.

Hi Michael, 

Thanks as always for providing this marvelous theme. 

I was wondering if there was a way of editing the footer other than just editing the raw footer.html and associated css. I want to add an image to the center of the footer, and perhaps a button in the bottom right. 

Thanks, 
--Alex

**Comment by mmistakes** [comment]
Editing Jekyll templates in an elegant way is kind of an oxymoron :wink: You either edit the files directly or you don't. Well not completely true... 

If you're using the [gemified version of the theme](https://mmistakes.github.io/minimal-mistakes/jekyll/gemified-theme-beta/) (currently in beta) you can add your own files that will override the default `_layouts`, `_includes`, and `_sass` files provided with the theme.

You get the benefit of customizing the files how you want and not having to worry about upgrading as it's as simple as `gem update minimal-mistakes-theme`. 

Unfortunately you have to be on Jekyll 3.3 and it doesn't currently work with GitHub Pages hosted sites since 3rd party gem themes (other than `minima`) aren't supported yet. So it's not a solution for everyone.

Also, if you want add content before the footer the theme ships with an include to do that. It's blank by default, but you can populate with whatever HTML you want.

- [_includes/footer/custom.html](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/footer/custom.html) -- injects right before footer.html (good for adding banner ads and the like)
- [_includes/head/custom.html](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/head/custom.html) -- injects right after head.html (good for adding favicon images and the like)

**Comment by zfrenchee** [comment]
Okay, assuming I'm using gh-pages, and I want to add an image in the middle of the footer, I should just edit the footer.html file in that case?

**Comment by mmistakes** [comment]
Yes
