### ISSUE TITLE
 Font Awesome icons subset for increased performance

### ISSUE THREAD

**Issue by kelstra** [mmistakes/minimal-mistakes#617]
The theme would benefit from using a subset of the Font Awesome icons.  Only those icons referenced in the theme would be included.

For example, I am currently using eleven icons:

fa-calendar, fa-chain, fa-clock-o, fa-envelope-square, fa-facebook, fa-google-plus, fa-linkedin, fa-map-marker, fa-rss-square, fa-twitter, fa-twitter-square

I stripped the unused icon styles from _icons.scss, resulting in a file size of 764 bytes, down from 46,979 bytes. A 98.37% reduction.

I then stripped the unused icons from the font files.

Some figures\* for one of the font files, fontawesome-webfont.woff2?v=4.6.3 :

Full font: Load time = 3730 milliseconds ; File size = 71,896 bytes

Subset font: Load time = 468 milliseconds ; File size = 2,312 bytes

Load time and file size are reduced by 87.45% and 96.78%, respectively.

\* Offline test via Google Chrome's Developer Tools, bandwidth throttled to Regular 3G.
  Theme version: 3.4.8

**Comment by mmistakes** [comment]
I agree this is a good idea as far as optimizing your site. I've done this with previous incarnations of the theme and then requests start coming in to add all the icons back.

The issue is people like to use them in their posts, change the table of contents icon, put in menus, etc.

The better solution is if you're only using that limited set you pull them out yourself and trim down the CSS and font files.

Even better you don't use Font Awesome at all and instead go with a SVG icon solution (I've done this with my personal blog) to get even more performance out of your pages.

**Comment by hakeryk2** [comment]
I have a question: how did You stripped font file from fonts that You are not using?

**Comment by mmistakes** [comment]
@hakeryk2 You can use something like [**IcoMoon**](https://icomoon.io/app/#/select). It'll let you add various font sets (eg. Font Awesome) and allow you to select which icons you want. Then it generates the font files and CSS that you could replace with what is included with the theme already.
