### ISSUE TITLE
Help? - CSS Conflicts with jquery css Used for Collapsible Blocks

### ISSUE THREAD

**Issue by danjump** [mmistakes/minimal-mistakes#630]
- [x] This is a question about using the theme.

Hello,

First of all, I'm using your theme for [my small personal/professional blog](www.danieljumper.com) and it's great! thanks so much for sharing your good work. Now, please excuse me in advance if this is more of an issue of my education on web development than an issue with the theme. Either way, help or good references would be greatly appreciated.

My problem is in this post specifically: [http://danieljumper.com/used_car_pricing_trends_1/](http://danieljumper.com/used_car_pricing_trends_1/). I used jquery for collapsible code blocks as implimented in [this example](http://www.w3schools.com/jquerymobile/tryit.asp?filename=tryjqmob_collapsible). It seems that using this style sheet:

> `<link rel="stylesheet" href="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">`

Is necessary for the proper collapsing block behavior, but it conflicts with aspects of the page style. For example, Font size and link colors are different and the background color on the page header (and other places) is white instead of slightly off-white.

I tried to investigate how to handle CSS conflicts, but i'm not very educated on the issue. The way I implimented the collapsing feature is by including the  `<link rel="stylesheet"` in the post .md file itself. I tried instead, including the .css file in the compiled webpage code attempting to order it after the rest of the stylesheets to give other styles precedent. But giving other stylesheets priority ruins the collapsing block behavior (they show up as expanded on page load and don't collapse). I tried to grep the stylesheet contents to find where the collapse specific tags are implimented and just use that part of the stylesheet but I was unsuccessful in finding the proper section. 

I'd love to keep using this collapsing box feature, but i hate how it's mildly ruining the page style. Do you have any suggestions or fixes for me here? 

Thanks!

**Comment by mmistakes** [comment]
You had the right idea trying to change the source order of the jQuery mobile CSS file, it definitely is overriding some of the theme's styles like `<a>` text color and the background due to the cascade.

To do it right I think you'll have to add just the styles for the accordion and stay away from anything that might impact the theme globally. But if you're not all that familiar with CSS that can be tricky.

Maybe try a simpler accordion. There's a fairly well supported "checkbox" accordion you can hack together that doesn't require any sort of JavaScript. It's purely CSS.

I use a version of it on my personal site to do a collapsible "Table of Content" (example: https://mademistakes.com/articles/using-jekyll-2016/)

There's several examples with code on Codepen.io if you want to try that method instead.

http://codepen.io/search/pens?q=accordion%20css&limit=all&order=popularity&depth=everything&show_forks=false

**Comment by danjump** [comment]
Hi Michael. Thanks for the help (and especially such a quick reply!). 

I appreciate the references - I'll do some reading there. I'll have to refresh my memory because it was a little while ago that I first did this, but a constraint I had was that I wanted to use markdown for code syntax highlighting INSIDE the pull down box. So I had html in the post .md file, but then wanted markdown inside that html. I think the solution I found at the end of the day was to use `<div markdown="1"> content </div>` inside the accordion html chunk. And I think this should be compatible with most CSS implementations you referenced? 

One last thing, can I impose on you again to get a kick in the right direction for implementing CSS accordian? Is the right order of affairs to add a new css file to `./sass/<accordian css (scss?) file>` and then add an `@import  "<accordian css(scss?) file>";` line to `./assets/css/main.scss`? On a separate note, I'm learning about but not greatly familiar with SASS. Can I get by with just renaming `.css` files to `.scss` in `./sass/`? I think that's what I did when attempting to include the jQuery mobile CSS.

Thanks again and sorry for the basic level questions! You're very kind to help.

**Comment by mmistakes** [comment]
Yes you'll likely need to wrap HTML `<div markdown="1"></div>` in your Markdown file if Kramdown doesn't parse it correctly. It usually has trouble with indented HTML because it treats it like a blockquote or code block. Usually takes some trial and error to get that all sorted.

And yes that's the correct way to approach getting the accordion (or any other CSS modules you add) into the main stylesheet. Just add it as `_whatever.scss` to the `_sass` folder then `@import` it in `/assets/css/main.scss`.

It's perfectly fine to just change a `.css` file to `.scss` without making any other changes. That's one of the benefits of using SCSS over SASS. It's just standard CSS... where you can add all the extra stuff like variables, mixins, etc.

**Comment by danjump** [comment]
Excellent, sounds good. Once I get everything fixed and working properly on my end I'll leave a final update for posterity and close the issue. Thanks a ton!

**Comment by mmistakes** [comment]
Closing this issue as it appears to be addressed. If not feel free to re-open.
