### ISSUE TITLE
Is there an option to disable fade-in animations?

### ISSUE THREAD

**Issue by vlsi** [mmistakes/minimal-mistakes#644]
- [x] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [x] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.0.5
- **`github-pages` or `jekyll` gem version:** 3.3.0
- **Operating system:** macOS 10.12.1 Sierra

---

Fade-in animation appears great when you open the site for the first time. However when you navigate between pages that fade effect makes the page "blink". I'm not saying it is a browser's issue. It is just a perceived blink when the page first becomes blank, then the content fades in.

Is there a configuration option that can disable fade animations?

**Comment by mmistakes** [comment]
No option. Just remove these [two lines of CSS](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/_page.scss#L11-L12) in /_sass/_pages.scss

**Comment by vlsi** [comment]
There is a bunch of other `animation: intro 0.3s both`. For instance, `page__hero--overlay` makes splash overlay image to fade in in the same way.

It looks like I need to copy&change large files just in order to augment a couple of styles. That would make upgrade hard.

Do you have any suggestion for "upgrade" scenario?

E.g.
1) Move animation and animation-delay into variables.scss or mixins.scss
1) Add some kind of "last.scss" that would get included the last into main.css, so I could put just those styles that I want to alter

**Comment by mmistakes** [comment]
Since all of those use the `intro` animation, if you remove that from [**_animations.scss**](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/_animations.scss) the animations will stop. Then you don't have to bother removing `animation: intro 0.3s both` that is sprinkled around the rest of the stylesheet.

If you going the forked method just comment out @import "animations";` in **/assets/css/main.scss**.

If you're using the gem theme then add a blank `_animations.scss` to **<site root>/_sass/_animations.scss** and it will override the one bundled in the gem --- effectively disabling all of the animations.

**Comment by vlsi** [comment]
I'm just trying to think what is the viable option to avoid "copy&paste lots of mm sources into my own site repository" and keep upgrade possibility.

It seems I have to fork & publish my own gem. I just thought the idea of mm-gem was to avoid everybody copy-pasting mm sources.

PS. animation of button background looks good. It is just a flash of white between navigations that looks odd to me.

**Comment by mmistakes** [comment]
I'm afraid that's the reality when you want to customize your site and diverge from the canonical version of the theme.

You're right, the theme gem is meant to make installing and upgrading easier. But since you're customizing the source the copy/pasting is necessary.

You don't have to copy the entire MM source when using the gem. You only need to add those files you want to change, and [they will override the ones in the theme](http://jekyllrb.com/docs/themes/#overriding-theme-defaults).

Since you just want to kill the animations of the theme I would just add a blank _animations.scss partial. That would be the easiest path the maintaining a custom version of the theme. Since that file is rarely touched you won't really have to worry about things breaking or missing updates. Anytime the theme has a new release you'd run `bundle update minimal-mistakes-theme` and you'll be all set.

**Comment by vlsi** [comment]
> You don't have to copy the entire MM source when using the gem. You only need to add those files you want to change, and they will override the ones in the theme.

I did check that out, however I find copy pasting specific files would complicate things in a way that I would no longer know which files override mm files and which are just my own.

Other things I'm running into:
* I would like to have `_data/navigation.yml` on a per-language basis
* I think I would hit some of coloring walls. For instance, button colors are hard-coded into _buttons.scss.
* I want just `linear-gradient` instead of image on a page_hero (that is `feature_row id="intro"`)
* I'm not sure I like absolute links that mm produces. It is incompatible with https://github.com/untra/polyglot, so I would either teach polyglot to support absolute urls, or teach mm to avoid usage of that kind of links.

On the other hand, it looks like minimal-mistakes suits me.
