### ISSUE TITLE
Odd CSS Borders around Google Site Search Results

### ISSUE THREAD

**Issue by vsential** [mmistakes/minimal-mistakes#759]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.1.1 
- **`github-pages` or `jekyll` gem version:** 3.3.1
- **Operating system:** Ubuntu 16.04

---

## Expected behavior

No boarder around the elements.  I am pretty sure this is something simple but I can't seem to find the fix.  See screenshot.
![css-border-issue](https://cloud.githubusercontent.com/assets/4664215/21754635/f662e598-d5c9-11e6-9980-db0dd43d385d.png)

Here is the page generating this:

```markdown
---
type: pages
title: ""
sitemap: false
permalink: /search/
---
 <div id="search">
   <form role="search" method="get" action="/search/">
   <input id="q" name="q"
          placeholder="vRealize Orchestrator, Containers, etc." type="text">
   <input id="searchButton" name="googleSearchName" type="submit" value="Search">
   </form>
 </div>

 <script>
   (function() {
     var cx = '';
     var gcse = document.createElement('script');
     gcse.type = 'text/javascript';
     gcse.async = true;
     gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
     var s = document.getElementsByTagName('script')[0];
     s.parentNode.insertBefore(gcse, s);
   })();
 </script>
 <gcse:searchresults-only queryParameterName="q"></gcse:searchresults-only>

**Comment by mmistakes** [comment]
Do you have this page live somewhere? I can't seem to test it locally since it relies on Google indexing the site for it to produce search results.

All I get is the search box, which doesn't return anything for me to troubleshoot what CSS is adding the borders.

![screen shot 2017-01-09 at 8 58 38 pm](https://cloud.githubusercontent.com/assets/1376749/21791065/6a1ca8c2-d6ae-11e6-897f-fc40f30143f3.png)

Your best bet would be to use your browser's web developer tools to inspect the elements with borders and see what CSS is being declared. 

Only thing I can think of off-hand might be if those elements are constructed with [`table`](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/_tables.scss). There are some border styles in the theme for that, so they might need to be adjusted based on how things are cascading.

But hard for me to say since I can't see the actual HTML and CSS class names Google uses for the search widget.

**Comment by vsential** [comment]
I do have it live for you to check out now, here is the link to it:

http://aws-dev1.vsential.com:4000/search-test/

Thanks for looking at this, I truly appreciate it!

**Comment by mmistakes** [comment]
Sure no problem!

As I suspected it's the borders being applied to `table`, `tr`, and `td`. I'll eventually add some small CSS to the theme to zero them out but if you want a quick fix add these CSS styles after the `_table.scss` ones.

```css
.gsc-control-cse table, 
.gsc-control-cse tr, 
.gsc-control-cse td {
    border: 0;
}
```

**Comment by vsential** [comment]
Awesome, that worked perfectly!  I really appreciate your work and help on this!
