### ISSUE TITLE
Link on navigation page not working

### ISSUE THREAD

**Issue by pjpaulpj** [mmistakes/minimal-mistakes#768]
Hi my blog is at https://pjpaulpj.github.io/. As you can see the link titled "Posts" is broken. I'm not sure why since I've defined the link in _data/navigation.yml, and there's a directory named posts in the repo.

I'm using this site http://rudvfaden.github.io/posts/ as a guide to imitate. Could you suggest other better structured sites using only github pages?

What am I missing?

**Comment by mmistakes** [comment]
Defining links in `_data/navigation.yml` doesn't actually build the pages. You need to physically build the `/posts/index.html` page.

Depending on how you want to set that up you could grab this [sample from the demo site](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_pages/year-archive.html).

1. Rename it to `posts.html` and place it in the root of your project.
2. Change the permalink to `permalink: /posts/` in its YAML Front Matter.
3. Rebuild your site and `https://pjpaulpj.github.io/posts/` should work.

**Comment by pjpaulpj** [comment]
Thanks for the great support and guidance.

I'm a complete Noob when it comes to Jekyll blogs and github pages. Could you recommend a reference that starts from scratch- and deals with questions like this one? I don't care much for Jekyll and heavy duty designing- I just want a blog I can upload posts to in markdown which allows for easy (relatively) extensions and modifications.

 I've already tried the 'Quick Start Guide'- it's a bit too advanced/ Jekyll focused; the official Jekyll guide- too advanced and detailed. 

Thanks once again.

**Comment by mmistakes** [comment]
http://jekyll.tips/

**Comment by pjpaulpj** [comment]
A quick follow-up:

I looked at the demo site, and the [About](https://mmistakes.github.io/minimal-mistakes/about/) page at  is defined at `url: /about/`. However, the actual `about.md` page is located at `_pages/about.md`.

What's happening here? I noticed that you suggest this as best practise in your Guide.

**Comment by mmistakes** [comment]
It's purely an organizational thing. You can consult the Jekyll docs for more, but what is going on is instead of putting `about.md` in the root, I prefer to keep all my pages in ` _pages` folder.... similar to `_posts`.

If you do that you need the `permalink` override so Jekyll places the rendered `index.html` in the right location. You also need to tell Jekyll to look at `_pages` since underscore files and folders are ignored by default. 

To do that `_pages` is added to the `include` array in [**_config.yml**](https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml#L113).
