### ISSUE TITLE
How to center Liquid generated text in an html page

### ISSUE THREAD

**Issue by pjpaulpj** [mmistakes/minimal-mistakes#774]
Hi, 

I'd like my blog's home page to show five of the most recent posts and a Github calendar. So far, [this is what I have](https://pjpaulpj.github.io/). The source for the page is[ here.](https://github.com/pjpaulpj/pjpaulpj.github.io/blob/master/index.html)

 I'd like to center the listing of the recent posts, and make sure that they follow the black colour scheme.

**Comment by mmistakes** [comment]
You'll need to write some custom CSS or edit what is currently in the theme to center and change colors.

**Comment by pjpaulpj** [comment]
Could you point me to an example?

**Comment by mmistakes** [comment]
I don't have one. You'll need to use CSS to write the styling to center text and all that. Try a CSS tutorial or reference site to learn more about it.

**Comment by mmistakes** [comment]
Not sure. I don't think there is a simple "plug and play" solution here. CSS by design can cascade and depending on what styles you're dropping in could override something else.

You really just need to get in there and start writing style declarations and see what happens. Even better you use the web developer tools of any modern browser to inspect elements and see if modifying existing styles is possible or if you need to rewrite some of the HTML too.

**Comment by pjpaulpj** [comment]
I resolved this be deleting the Github calendar, and using the `archive` layout for the index page.
