### ISSUE TITLE
Use bundled jquery?

### ISSUE THREAD

**Issue by desilinguist** [mmistakes/minimal-mistakes#794]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.3.3
- **`github-pages` or `jekyll` gem version:** 3.1.6
- **Operating system:** macOS Sierra 10.12.2

---

First of all, thanks for the amazing theme. It's so nice to have a github-pages theme that pays attention to all the little details and looks great.

I am assuming there's a way to use the jQuery library that's already bundled inside `main.min.js` in my pages and I am just being really dumb and can't get it to work. I keep getting errors like `Can't find variable: $`. Is there some documentation on how to use the bundled jQuery in a page?

**Comment by mmistakes** [comment]
My guess is you're calling a jQuery function before `main.min.js` is pulled in. It's [in the footer](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/scripts.html#L1) so any scripts you add that rely on jQuery need to occur after it or else you'll get that `Can't find variable: $`.

**Comment by desilinguist** [comment]
I see So, how do I ensure that `main.min.js` is loaded first before I do anything with jQuery in a markdown file under  `_pages`.

**Comment by mmistakes** [comment]
You'll have to make some modifications to the theme to do that.

Since `main.min.js` is in the footer it will always load after anything you put into a post or page's content. If it's only a small bit of jQuery you could add it after that line I referenced above.

You could probably rig it so you put the unique scripts in the page's Front Matter YAML and then reference that in some sort of `page.script` variable in the footer.

Or maybe even easier just move `main.min.js` from the footer to the `<head>`. Downside to that is you might get a performance hit since loading scripts in the head typically block rendering of a page.

**Comment by desilinguist** [comment]
Got it. I will try one of those options and report back. Thanks for the quick response!

**Comment by desilinguist** [comment]
I added the script to the page's Front Matter YAML and then added the following to `_includes/scripts.html` and it works great!  Thanks!

```
{% if page.script %}
    {{ page.script }}
{% endif %}
```
