### ISSUE TITLE
How to generate grid effectively with theme

### ISSUE THREAD

**Issue by desilinguist** [mmistakes/minimal-mistakes#801]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.3.3
- **`github-pages` or `jekyll` gem version:** 3.1.6
- **Operating system:** MacOS 10.12.3

---

I apologize for posting so many questions but I am a little stuck on trying to figure out best to lay out a grid with the theme. I am trying to replicate a grid-based conference schedule as seen [here](http://naacl.org/naacl-hlt-2016/program.html). I have had good success with the full-width items but when it comes to the parallel sessions (the light purple ones), I am having trouble getting it to behave as it should: basically, I'd like the columns to stack one on top of each other responsively but that doesn't seem to happen.

Here's the HTML for the row:

```html
 <div class="day" id="first-day">Monday, June 13</div>
<div class=" session-papers1" id="session-1a">
    <div class="session-details">
        ...
    </div> 
</div>
<div class=" session-papers2" id="session-1b">
    <div class="session-details">
        ...
    </div> 
</div>
<div class=" session-papers3" id="session-1c">
    <div class="session-details">
        ...
    </div> 
</div>
```

and here's the CSS:

```css
    &.session-papers1 {
        @include span(4 wide of 12 (gutter-override: 0));
    }

    &.session-papers2 {
        @include span(4 wide of 12 (gutter-override: 0));
    }

    &.session-papers3 {
        @include span(4 last (gutter-override: 0));
    }
```

This looks fine in desktop mode:

<img width="1027" alt="screen shot 2017-01-27 at 3 58 11 pm" src="https://cloud.githubusercontent.com/assets/161680/22387439/a714b95a-e4a9-11e6-9b8e-d9865d526b06.png">

but in responsive mode, it doesn't follow the expected behavior:

<img width="297" alt="screen shot 2017-01-27 at 4 00 25 pm" src="https://cloud.githubusercontent.com/assets/161680/22387467/bd15e170-e4a9-11e6-85c8-255a01af1e1c.png">

Am I doing something wrong? Do I have to explicitly encode the responsive layouts myself in the CSS? I was hoping that the theme would take care of it.

**Comment by mmistakes** [comment]
You'll need to add the widths for various screen width breakpoints. Basically the way I've done it is using a "mobile-first" philosophy.

Start with how you want things to look for small screens, then add a breakpoint when you want it to change. Repeat.

Since you want them to stack you'll want to start with them spanning then entire set of columns `12 of 12`. Then when you hit tablet or desktop screen sizes you can have them shrink down to `4 of 12` so you can do 3 in a row.

To do that you can use the [breakpoint mixins](http://breakpoint-sass.com/).

Something like this.

```scss
.your-class {
  // mobile first styles here

  @include breakpoint($medium) { // will convert to a max-width:768px media query
    // 600px wide and up styles here
    // column width 100%
  }

  @include breakpoint($large) { // will convert to a max-width:1024px media query
    // 1024px wide and up styles here
    // column width 33.3333%
  }
}
```

The `$medium` and `$large` variables are just [widths for common screen sizes](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/_variables.scss#L104-L108). You can use them or be more specific if you have a need for that.

**Comment by desilinguist** [comment]
This works beautifully! Thanks so much for your guidance.
