### ISSUE TITLE
Justified text by default

### ISSUE THREAD

**Issue by juliohm** [mmistakes/minimal-mistakes#883]
First of all, thank you very much for this awesome project, it is incredible :+1: 

I am trying to make the contents of the posts and pages all justified by default, but I am very new to Jekyll and not an expert in web programming.

How would you change the configuration files for adding a `{: text-justify}` everywhere in the body of the pages?

**Comment by mmistakes** [comment]
You'll have to modify the theme's CSS to do this. If you set the following declaration it will justify the post/page content.

```css
.page__content {
  text-align: justify;
}
```

**Comment by juliohm** [comment]
Thank you @mmistakes , what is your suggestion about the file where I should add these lines? I am seeing many files inside of `_sass`, is that the right place?

**Comment by mmistakes** [comment]
Yes, that's the right place. Here would work https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/_page.scss#L53

**Comment by juliohm** [comment]
Awesome @mmistakes, problem solved. Closing the issue.

**Comment by YannisPap** [comment]
Hello @mmistakes and thanks for this awesome theme.
I tried the above but the right sidebar is part of the page__content and sometimes creates this ugly result:
![fraud detection using machine learning analysis just another data science blog](https://cloud.githubusercontent.com/assets/10160052/24951961/bab34c1e-1f7e-11e7-87c8-c546ab0c1916.png)

Is there a way to exclude the sidebar?

Thank you.

**Comment by mmistakes** [comment]
@YannisPap Sure... with more CSS.

```css
.sidebar__right {
  text-align: left;
}
```

**Comment by YannisPap** [comment]
You are right. Very nubby on CSS.

Thanks you.

**Comment by badouralix** [comment]
Would it be relevant to make a PR adding a new variable in [_sass/_variables.scss](https://github.com/mmistakes/minimal-mistakes/blob/eaf366e405a0f988fa90cd7fe0bc136df60ea34b/_sass/_variables.scss) setting the default alignment, instead of manually patching the theme when one wants to override it?

**Comment by NickleDave** [comment]
In case anyone else comes upon this issue ...

I was able to achieve what's described here
https://github.com/mmistakes/minimal-mistakes/issues/883#issuecomment-283648056
by adding it in `/* paragraph indents */` in the current `_page.scss`

https://github.com/mmistakes/minimal-mistakes/blob/8a67ce8e41ec850f2d7c373aa47739b2abfee6f1/_sass/minimal-mistakes/_page.scss#L121
```
  /* paragraph indents */
  p {
    text-align: justify;  /* added here */

    margin: 0 0 $indent-var;
```

I chose not to add it above in the declaration block above that one which includes `p, li, di` elements because I only wanted to modify paragraphs. 

Alternatively, if you add the `text-align` right when `.page__content` opens, that will work, but it will also affect all the headings, which may look weird especially for shorter headings
https://github.com/mmistakes/minimal-mistakes/blob/8a67ce8e41ec850f2d7c373aa47739b2abfee6f1/_sass/minimal-mistakes/_page.scss#L90
```
.page__content {
  text-align: justify;
  h2 {
    padding-bottom: 0.5em;
    border-bottom: 1px solid $border-color;
  }
```

I am definitely not a css expert so feel free to tell me there's a better way to do this
