### ISSUE TITLE
Sass compile errors using Bigfoot.js

### ISSUE THREAD

**Issue by twhite96** [mmistakes/minimal-mistakes#894]
I found an issue about a compile error using Bigfoot.js but it wasn't *quite* the same issue.

My issue is `Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    File to import not found or unreadable: bigfoot-default. Load path: /Users/tiffanywhite/.rvm/gems/ruby-2.2.1/gems/minimal-mistakes-jekyll-4.2.1/_sass on line 38`

Basically I found a guy showing how to use Bigfoot in jekyll, but I am not sure how he got it to work. Followed the example, but the Sass compile error keeps happening. Repo is [here](https://github.com/twhite96/twhite96.github.io).

Thanks for your help.

**Comment by mmistakes** [comment]
Questions of this nature are good candidates for asking the Jekyll community over on [talk.jekyllrb.com](https://talk.jekyllrb.com/) since it's not Minimal Mistakes or theme specific.

The error above is actually pretty descriptive of the issue. It's telling you there is a problem with your Sass in `assets/css/main.scss`. It references line 38 so that's a good place to start.

Pretty sure the problem are [these lines](https://github.com/twhite96/twhite96.github.io/blob/master/assets/css/main.scss#L40-L43):

```scss
@import "base",
        "bigfoot-default", // hello there
        "layout",
        "syntax-highlighting";
```

They're trying to load Sass partials that don't exist in `_sass` directory as indicated by the error. Because you're using a Ruby theme gem it's looking for them there... 

If you're trying to customize BigFoot.js's CSS then I would remove those lines from `main.scss`. You have `assets/css/bigfoot-default.scss` already created, just add YAML Front Matter to it and Jekyll will process it.

```yaml
---
---
```

Then you can drop a `<link>` element into your head to pull it in.

The other option is drop the [compiled CSS](https://github.com/lemonmade/bigfoot/blob/master/dist/bigfoot-default.css) for BigFoot into your `/assets/css/` directory, create a local copy [`/_includes/head/custom.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/head/custom.html) and add it there if you don't want to bother with the SCSS version.

**Comment by twhite96** [comment]
I am unable to get this to work. So you're saying this is a Jekyll issue? I'll check out the forums as I haven't found a good article on how to implement this.

**Comment by mmistakes** [comment]
Closing. Feel free to re-open with updates or more information to help resolve the issue.

**Comment by twhite96** [comment]
No worries. Got it to work. Thanks Michael.
