### ISSUE TITLE
Google Analytics optimization

### ISSUE THREAD

**Issue by YannisPap** [mmistakes/minimal-mistakes#948]
Hello,

I'm not sure if this is a support request or an improvement.

Google Tag Assistant was complaining that the tracking code was outside the ```<head>```, so I removed the

```{% include analytics.html %}```

from ```_includes/scripts.html``` and add in in the ```<head>``` section of ```_layouts/default.html``` and it seems to work nice.

Does this sound right?

Thanks

**Comment by mmistakes** [comment]
I have it near the footer as a common best practice to avoid impact page load speed negatively. Scripts can block the loading of the main content so moving them after is one way to avoid that.

You can certainly move it to the top if you want. In my experience having GA in the footer doesn't affect analytics gathered much. Google is wants you to load it first to grab everything about the user. There's a chance with it in the bottom that someone visits your page, abandons before the GA script loads and it won't capture that data.

Personally I'd rather give priority to the page content and not an analytics package, especially since the user could care less about that.

**Comment by YannisPap** [comment]
Understood.

Thank you.
