### ISSUE TITLE
4.4.0 Release and SCSS

### ISSUE THREAD

**Issue by justinrummel** [mmistakes/minimal-mistakes#957]
In your release notes for 4.4.0, there is this bullet: 

> Move SCSS partials to /_sass/minimal-mistakes for easier CSS customization

What does this actually mean?  I noticed all my customizations are gone so I moved them to the new /_sass/minimal-mistakes/ folder, but I don't see how this allows easier CSS customization.  What am I missing? 

Thanks!

**Comment by mmistakes** [comment]
This was done to ease the pain of those using the theme gem version who just want to modify some of the values in `_variables.scss`. Which I find is the vast majority of users of the theme.

Previously the only way to do that was to copy the entire set of `_sass` partials into your local files to override them all because of how Jekyll processes them. This defeats the whole point of having a theme gem.

By placing all of the theme's `_sass` partials in subfolder it allowed me to pull all of the `@import`s out of `/assets/css/main.scss` and clean things up. It also allows a user to add Sass variable overrides or custom CSS directly to `main.scss`.

Now you can do something like this with `main.scss`:

```scss
---
# main.scss
---

@charset "utf-8";

/* Theme overrides */
$paragraph-indent: true;
$link-color: red;
@import "minimal-mistakes";
```

Versus the old way where you'd need to copy all of the partials too. Which could isn't really that great in the long run, especially if I add, remove, or rename partials.

```scss
---
# main.scss
---

/*!
 * Minimal Mistakes Jekyll Theme 4.3.1 by Michael Rose
 * Copyright 2017 Michael Rose - mademistakes.com | @mmistakes
 * Licensed under MIT (https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE.txt)
*/

/*
   Variables
   ========================================================================== */

@import "variables";


/*
   Vendor
   ========================================================================== */

/* Breakpoint - media query mixins */
@import "vendor/breakpoint/breakpoint";
@include breakpoint-set("to ems", true);

/* Font Awesome - icon font set */
@import "vendor/font-awesome/font-awesome";

/* Magnific Popup - responsive lightbox */
@import "vendor/magnific-popup/magnific-popup"; // Magnific Popup

/* Susy - grid mixins */
$susy: (
  columns: 12,
  gutters: 1/4,
  math: fluid,
  output: float,
  gutter-position: after,
  container: $large,
  global-box-sizing: border-box,
  // debug: (
  //   image: show,
  //   color: blue,
  //   output: overlay,
  //   toggle: top right,
  // ),
);
@import "vendor/susy/susy";


/*
   Base
   ========================================================================== */

@import "mixins";
@import "reset";
@import "base";
@import "utilities";
@import "animations";
@import "tables";
@import "buttons";
@import "notices";
@import "masthead";
@import "navigation";
@import "footer";
@import "syntax";
@import "forms";


/*
   Layout specific
   ========================================================================== */

@import "page";
@import "archive";
@import "sidebar";
@import "print";

/* Them overrides */
$paragraph-indent: true;
$link-color: red;
```

---

This is a pattern adopted by several other themes, the biggie being Jekyll's default [Minima](https://github.com/jekyll/minima/pull/117).

**Comment by justinrummel** [comment]
Finally getting to test some changes so I can update to the latest version of the theme.  When moving my file overrides out of _sass, and creating a new main.scss with the below code, I'm not seeing my modifications being available in the page source.

I'm sure I'm not doing something correctly, just looking for some guidance.

``` css
---
# main.scss
---

@charset "utf-8";

/* Theme overrides */

/*
   Media and embeds
   ========================================================================== */

/* Figures and images */

  iframe {
    display: block;
    margin-left: auto;
    margin-right: auto;
  }

  &.fourth {
    > a,
    > img {
      @include breakpoint($small) {
        width: calc(25% - 0.5em);
      }
    }

    figcaption {
      width: 100%;
    }
  }

  &.fifth {
    > a,
    > img {
      @include breakpoint($small) {
        width: calc(20% - 0.5em);
      }
    }

    figcaption {
      width: 100%;
    }
  }

# trimmed

```

**Comment by mmistakes** [comment]
Put your SCSS/CSS overrides after the `@import "minimal-mistakes"`, placing them before won't override anything.

The only stuff you want to put before the `@import` would be any Sass variables you're changing. Because of the way those are read in by the Sass parser they need to come before.

**Comment by justinrummel** [comment]
OK, moved my CSS below the ```@import "minimal-mistakes"```.  

I Still wasn't getting anything.  I was re-reading [https://github.com/jekyll/minima#customization](https://github.com/jekyll/minima#customization) and noticed that the placement of main.css was to be in /assets/.  

I moved my file from /_sass to /assets and was able to see a bunch of CSS errors.  Cleaned those up now without any errors, but still don't see an updated version of localhost:4000/assets/css/main.css that has my CSS.

I can't commit my changes to my repo, as the site then looses all my customizations as Travis is triggered on commit.  Thoughts?

**Comment by mmistakes** [comment]
What files have you made customizations to? Layouts and includes aren't a problem since you can override them one by one with local copies in `_layouts` and `_includes`. 

`_sass` files on the other hand are problematic because of how Jekyll process them. It's an all or nothing which means you have to take the entire `_sass` folder from the bundled theme gem and copy it locally... then make your edits there. Which as you guessed has a lot of issues if you want to stay in sync with the theme.

When I tested this all out I created a local copy of `assets/css/main.scss` and added my new CSS after the `@import`. Those styles were appended right after the core styles of the theme.

If you want to change any of the values found in `_sass/minimal-mistakes/_variables.scss` then you add those before the `@import` and because of the way Sass handles `!default` values they will be applied in place of the core values.

Just to make sure you don't have some files in the wrong location I would suggest adding this to `/assets/css/main.scss` as a test,

```scss
.foo {
  display: block;
}
```

Then build your site and look at `/css/main.css` and at the end you should see `.foo { display: block; }`. If you don't then the file structure is likely off.

Also I would suggest creating a branch off of `master` and push those changes up to your repo to get Travis to ignore. Then I can see your actual code since I can only speculate what the issue is.

**Comment by justinrummel** [comment]
That was it!  File needs to be in /assets/css/main.scss

I was talented and picked two wrong locations.  You can close this if needed.
