### ISSUE TITLE
Pagination link broken

### ISSUE THREAD

**Issue by wvengen** [mmistakes/minimal-mistakes#997]
When I'm using

```yaml
paginate_path: /pages/:num/
```

the pagination link for the first page appears to be broken, for example see [page 3](https://foodcoops.github.io/page/3/), where page two is referenced correctly, but the first page shows as `/page/:num/`. Sounds a like a bug - or did I do something unsupported in the [configuration](https://github.com/foodcoops/foodcoops.github.io/blob/master/_config.yml#L149)?

**Comment by mmistakes** [comment]
What you have should work, not sure why it's not.

What happens if you remove `/` and do this in your `_config.yml` instead?

```
paginate_path: /page:num/
```

**Comment by wvengen** [comment]
Thanks for your quick reply! It does work when I accept your suggestion (though I'm trying to get it working with the slash).

**Comment by mmistakes** [comment]
Think you're out of luck then as it appears to be a limitation with Jekyll's pagination plugin. All of their examples use `page:num` vs what you want `page/:num`.

The plugin is no longer being developed so not sure if filling a bug there will have any effect. 

https://github.com/jekyll/jekyll-paginate

As an alternative Jekyll Paginate v2 is pretty great and more feature filled but it doesn't work with GitHub Pages unless you're building locally and pushing the built`_site` folder instead of having GH build.

https://github.com/sverrirs/jekyll-paginate-v2

**Comment by wvengen** [comment]
Ah, sorry to bother you. Thanks!

**Comment by mmistakes** [comment]
No worries.
